import type { Puzzle } from '../puzzle-types'

export const PUZZLES_CASH_SRP: Puzzle[] = [

  // ── srp-n01: BB two-pair protection on connected board ───────────────────
  {
    id: 'srp-n01-bb-two-pair-protection',
    title: 'BB Two-Pair — Protection on a Wet Board',
    description: 'You defend BB with Th9h and flop two pair on a connected board. Navigate three streets balancing protection and value.',
    difficulty: 'intermediate',
    category: 'SRP',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Th', '9h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    summary: '',
    tags: [],
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to BTN who raises to $5. SB folds.',
        prompt: 'BB with Th9h. BTN opens from the button. How do you proceed?',
        options: [
          { id: 'fold', label: 'Fold', quality: 'mistake', evLoss: 3.2, coaching: 'T9s is a slam-dunk defend from BB. You have excellent pot odds, strong implied odds vs BTN\'s wide range, and good playability on many boards. Never fold this.' },
          { id: 'call', label: 'Call $3', quality: 'perfect', evLoss: 0, coaching: 'Standard. T9s connects with a huge range of flops — straights, two pairs, flush draws. You close the action at good odds. The implied-odds potential makes this a clear defend.' },
          { id: '3bet', label: '3-bet to $18', quality: 'mistake', evLoss: 1.8, coaching: 'T9s is too weak to 3-bet for value OOP vs BTN. It doesn\'t want a large pot without a made hand. Flatting keeps pot small and lets you realize equity in position parity.' },
        ],
      },
      {
        street: 'flop',
        board: ['Ts', '9d', '6c'],
        context: 'BTN calls. Pot $10bb. Flop: Ts9d6c. You act first OOP.',
        prompt: 'You flopped top two pair on Ts9d6c. The board is very connected — straights and sets are possible. Do you bet for protection, check-raise, or slowplay?',
        options: [
          { id: 'check', label: 'Check (plan to check-raise)', quality: 'good', evLoss: 0.4, coaching: 'Check-raising is viable — BTN will c-bet wide on this board and you can build a big pot. The risk: BTN checks back and you give a free turn to combo draws. Leading is slightly better on such a wet board.' },
          { id: 'bet-small', label: 'Bet 4bb (40% pot)', quality: 'good', evLoss: 0.3, coaching: 'Small lead charges draws and keeps BTN\'s wide range in. But the board is dangerous enough that a larger sizing is preferred for protection.' },
          { id: 'bet-large', label: 'Bet 8bb (80% pot)', quality: 'perfect', evLoss: 0, coaching: 'Top two pair on Ts9d6c demands a large bet. You need to charge straight draws (78, J8, 87) and protect against flush draw run-outs. A big bet now gets value AND protection simultaneously.' },
        ],
      },
      {
        street: 'turn',
        board: ['Ts', '9d', '6c', '7h'],
        context: 'BTN calls flop. Pot $26bb. Turn: 7h — straight completed. You act first OOP.',
        prompt: 'The 7h completes 87, 8T straights. BTN called your large flop bet. Do you continue betting to protect remaining value, or slow down?',
        options: [
          { id: 'check-fold', label: 'Check-fold', quality: 'mistake', evLoss: 4.1, coaching: 'Giving up two pair on the turn is a massive mistake. BTN\'s range that called the flop still contains many bluffs, flush draws, and worse made hands. You still have significant equity even vs straights.' },
          { id: 'check-call', label: 'Check-call', quality: 'good', evLoss: 1.2, coaching: 'Check-calling is reasonable — you control pot size and keep bluffs in BTN\'s range. But leading keeps pressure on draws and combo hands that might check back.' },
          { id: 'bet-half', label: 'Bet 13bb (half pot)', quality: 'perfect', evLoss: 0, coaching: 'Keep betting for protection and value. BTN\'s range includes flush draws, combo draws, worse two pairs, and overcards with draws. A half-pot bet charges them all while building a pot when you\'re good.' },
        ],
      },
      {
        street: 'river',
        board: ['Ts', '9d', '6c', '7h', '2s'],
        context: 'BTN calls turn. Pot $52bb. River: 2s — blank. You act first OOP.',
        prompt: 'River bricks. BTN called two streets of large bets. What is your river strategy with top two pair?',
        options: [
          { id: 'check', label: 'Check (give up)', quality: 'mistake', evLoss: 5.8, coaching: 'Checking here is a large EV leak. After two calls on a very wet board, BTN\'s range includes busted draws that will fold, worse two pairs, and trips — all of which you beat or value target. Never give up your value hand on a blank river.' },
          { id: 'bet-small', label: 'Bet 18bb (35% pot)', quality: 'good', evLoss: 1.5, coaching: 'A small bet is fine to extract thin value. However, given BTN called two large bets, their continuing range on this river can handle a bigger sizing.' },
          { id: 'bet-large', label: 'Bet 35bb (67% pot)', quality: 'perfect', evLoss: 0, coaching: 'After two streets of large bets and a blank river, a river value bet at 67% pot is optimal. BTN\'s range calling flop+turn includes many hands that will call the river — trips, overpairs, busted draws calling out of stubbornness. Get paid.' },
        ],
      },
    ],
  },

  // ── srp-n02: BTN JhTh — NFD + gutshot, semi-bluff, free card, river value ─
  {
    id: 'srp-n02-btn-jhth-combo-draw',
    title: 'BTN Combo Draw — NFD + Gutshot Semi-Bluff',
    description: 'You open BTN with JhTh and flop a nut flush draw plus gutshot on a two-tone board. Play the draw aggressively across three streets.',
    difficulty: 'intermediate',
    category: 'SRP',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Jh', 'Th'],
    effectiveStack: 100,
    stakes: '$1/$2',
    summary: '',
    tags: [],
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to BTN. You raise to $5. SB folds. BB calls.',
        prompt: 'Standard BTN open with JhTh. BB defends. Pot $10bb. Ready for the flop.',
        options: [
          { id: 'continue', label: 'Note: standard open — proceed to flop', quality: 'perfect', evLoss: 0, coaching: 'JTs is a premium BTN open — strong equity, connectivity, and positional playability. Standard raise to 2.5bb. BB\'s defend is expected.' },
        ],
      },
      {
        street: 'flop',
        board: ['Qh', '8h', '3d'],
        context: 'BB checks. Pot $10bb. Flop: Qh8h3d. You are IP.',
        prompt: 'BB checks to you. You have JhTh — nut flush draw (9 outs) + gutshot to J-high straight (3 outs) = 12 outs. Do you c-bet as a semi-bluff, take a free card, or raise big?',
        options: [
          { id: 'check', label: 'Check back (free card)', quality: 'mistake', evLoss: 2.1, coaching: 'Taking a free card with 12 clean outs is a large mistake. You\'re giving up the semi-bluff fold equity that makes draws so profitable. This combo draw plays MUCH better as a bet — you can win immediately or build a pot to get paid when you hit.' },
          { id: 'bet-small', label: 'Bet 4bb (40% pot)', quality: 'good', evLoss: 0.6, coaching: 'A smaller sizing keeps BB\'s range wide for later streets. With 12 outs, small bets are fine, but a larger sizing charges draws-vs-draw situations better.' },
          { id: 'bet-large', label: 'Bet 8bb (80% pot)', quality: 'perfect', evLoss: 0, coaching: 'A large c-bet is optimal. You have immense equity (12 outs × 4% = ~48%), so a large bet builds the pot when you\'re a coin flip, and folds out hands with 6-8 outs that are also semi-bluffing against you. Maximum pressure.' },
        ],
      },
      {
        street: 'turn',
        board: ['Qh', '8h', '3d', '2c'],
        context: 'BB calls flop. Pot $26bb. Turn: 2c — blank. BB checks.',
        prompt: 'Turn blanks. BB called your large flop bet and checks. You still have 12 outs. What is your turn plan?',
        options: [
          { id: 'check', label: 'Check back (pot control)', quality: 'mistake', evLoss: 2.8, coaching: 'Checking back with 12 outs and a pot that needs building is a significant EV loss. When BB checks to you in position, you need to decide between a value/bluff bet or taking a free card. With 12 outs (~24% equity to improve), betting keeps pressure on and charges BB to see the river.' },
          { id: 'bet-half', label: 'Bet 13bb (half pot)', quality: 'perfect', evLoss: 0, coaching: 'Continue the aggression. A half-pot turn bet maintains pressure, charges draws, and sets up a profitable river jam if the flush completes. BB\'s range after flop call includes many one-pair hands that will fold to consistent pressure.' },
          { id: 'jam', label: 'Jam all-in ($74bb)', quality: 'good', evLoss: 0.9, coaching: 'Jamming the turn is aggressive but not optimal. It\'s better to bet half-pot and jam the river — the two-street approach extracts more EV from BB\'s calling range and keeps bluff-catchers in for one more decision.' },
        ],
      },
      {
        street: 'river',
        board: ['Qh', '8h', '3d', '2c', '6h'],
        context: 'BB calls turn. Pot $52bb. River: 6h — flush completes! BB checks.',
        prompt: 'You rivered the nut flush! BB checks. Effective stacks ~$48bb. How do you size for maximum value?',
        options: [
          { id: 'bet-small', label: 'Bet 20bb (38% pot)', quality: 'mistake', evLoss: 5.2, coaching: 'Tiny bet with the nuts is a massive value cut. After three streets of heat on a flushed board, BB\'s calling range is condensed to made hands and stubborn bluff-catchers. They will call a large sizing. Small bets leave money on the table.' },
          { id: 'bet-large', label: 'Bet 40bb (77% pot)', quality: 'perfect', evLoss: 0, coaching: 'Bet large — near pot. You have the nuts. BB called flop and turn with something. Whether it\'s two pair, a set, or a worse flush, they have enough invested to call a large river bet. Size for maximum extraction.' },
          { id: 'jam', label: 'Jam all-in ($48bb)', quality: 'perfect', evLoss: 0.1, coaching: 'Jamming is essentially the same as betting large here — the stacks are shallow enough that a jam and a large bet are nearly equivalent. Fine play. BB will call with any made hand after two calls.' },
        ],
      },
    ],
  },

  // ── srp-n03: CO AcKs — TPTK 3-street value OOP ──────────────────────────
  {
    id: 'srp-n03-co-ak-tptk-oop',
    title: 'CO vs BTN — AK Top Two Pair OOP Value',
    description: 'You open CO with AcKs and the BTN calls. Flop gives you top two pair. Drive value across three streets from OOP.',
    difficulty: 'beginner',
    category: 'SRP',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BTN',
    heroCards: ['Ac', 'Ks'],
    effectiveStack: 100,
    stakes: '$1/$2',
    summary: '',
    tags: [],
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'You raise CO to $5. BTN calls. Pot $11bb.',
        prompt: 'Standard CO open with AcKs. BTN flats. Ready to play a SRP OOP with the best non-pair hand.',
        options: [
          { id: 'continue', label: 'Note: standard open — proceed to flop', quality: 'perfect', evLoss: 0, coaching: 'AKs is an obvious open from CO. BTN calling is very common — they defend wide from the button. No further action needed preflop. Your challenge begins postflop OOP.' },
        ],
      },
      {
        street: 'flop',
        board: ['Ac', 'Kd', '7h'],
        context: 'Pot $11bb. Flop: AcKd7h. You act first OOP.',
        prompt: 'You flopped top two pair on a dry board — AcKd7h. BTN\'s range is wide. Do you lead for value, check-raise, or check-call?',
        options: [
          { id: 'check-call', label: 'Check-call', quality: 'good', evLoss: 0.8, coaching: 'Check-calling gives BTN a free c-bet with AK. You let them barrel air into you, which is fine — but you miss value when BTN has a medium pair and checks back. Leading builds the pot directly.' },
          { id: 'check-raise', label: 'Check (plan to check-raise)', quality: 'good', evLoss: 0.5, coaching: 'Check-raising is viable and polarizes your range well. Risk: BTN checks back, giving free turn cards. Leading is slightly better on dry boards where BTN won\'t always c-bet.' },
          { id: 'bet', label: 'Bet 7bb (65% pot)', quality: 'perfect', evLoss: 0, coaching: 'Lead for value. On AK7 dry, you have the nuts (essentially). BTN\'s range includes many pairs — pairs of 7s through Ks — that will call. A 65% sizing targets all of those hands. Build the pot now.' },
        ],
      },
      {
        street: 'turn',
        board: ['Ac', 'Kd', '7h', '4s'],
        context: 'BTN calls flop. Pot $25bb. Turn: 4s — blank. You act first OOP.',
        prompt: 'BTN called your flop bet. Blank 4s turn. Board stays dry: AK74 rainbow. Continue for value?',
        options: [
          { id: 'check', label: 'Check (pot control)', quality: 'mistake', evLoss: 3.5, coaching: 'Pot control with top two pair on a dry board is a mistake. BTN called the flop — their range is populated with single pairs that are drawing thin. You must keep betting to extract value before they give up. Checking lets them realize equity for free.' },
          { id: 'bet-small', label: 'Bet 8bb (32% pot)', quality: 'good', evLoss: 1.1, coaching: 'A small turn bet keeps BTN\'s weak pairs in. However, hands like KQ, K9, A9 will also call a large sizing — you\'re leaving money on the table by betting small.' },
          { id: 'bet-large', label: 'Bet 17bb (68% pot)', quality: 'perfect', evLoss: 0, coaching: 'Bet large again. BTN\'s range after calling a flop bet on AK7 dry includes exactly the medium-strength hands (KQ, KJ, A9, 77) that will call a large turn bet. Keep building the pot.' },
        ],
      },
      {
        street: 'river',
        board: ['Ac', 'Kd', '7h', '4s', 'Jc'],
        context: 'BTN calls turn. Pot $59bb. River: Jc. You act first OOP.',
        prompt: 'River Jack brings a backdoor club draw and creates QT straight. You still have top two pair. BTN called two large bets. Bet river or check?',
        options: [
          { id: 'check', label: 'Check-call', quality: 'good', evLoss: 2.1, coaching: 'Checking is reasonable — the Jc is a scare card that might have helped BTN (KQs, QTs, JJ). But after two large calls, BTN\'s range is capped below two pair mostly. Leading extracts value from KJ, AJ, and worse two pairs.' },
          { id: 'bet-small', label: 'Bet 20bb (34% pot)', quality: 'good', evLoss: 0.8, coaching: 'Small bet is fine for thin value but undersizes given pot and BTN\'s calling range. Hands like AJ, KJ, 77 that hit the river will call larger.' },
          { id: 'bet-large', label: 'Bet 40bb (68% pot)', quality: 'perfect', evLoss: 0, coaching: 'Three streets of large bets is the correct line. Your two pair is strong. BTN called flop and turn — they have something. On a non-draw-completing river, a large bet extracts max value from all the single pairs, two pairs, and sets in BTN\'s range that will call.' },
        ],
      },
    ],
  },

  // ── srp-n04: BTN 6s6c — set slowplay → raise turn → river jam ───────────
  {
    id: 'srp-n04-btn-set-slowplay',
    title: 'BTN Set of Sixes — Slowplay Flop, Build Turn, Jam River',
    description: 'You open BTN with 6s6c, BB defends, and you flop a set on a coordinated board. Execute a multi-street slow-play and convert on the river.',
    difficulty: 'intermediate',
    category: 'SRP',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['6s', '6c'],
    effectiveStack: 100,
    stakes: '$1/$2',
    summary: '',
    tags: [],
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to BTN. You raise to $5. SB folds. BB calls.',
        prompt: '66 on the BTN — open, 3-bet, or limp?',
        options: [
          { id: 'limp', label: 'Limp $1', quality: 'mistake', evLoss: 1.5, coaching: 'Limping from BTN is a mistake. 66 is a standard open from any late-position seat. Opening forces SB to fold, builds the pot when BB folds, and builds your opening range credibility.' },
          { id: 'raise', label: 'Raise to $5', quality: 'perfect', evLoss: 0, coaching: 'Standard raise. 66 has strong set-mining equity and playability IP. Opening to 2.5bb is correct from BTN.' },
          { id: '3bet', label: 'Only if faced with a 3-bet', quality: 'good', evLoss: 0.3, coaching: '66 is a borderline cold-4bet hand vs very wide 3-betters, but just opening is standard in this spot.' },
        ],
      },
      {
        street: 'flop',
        board: ['6h', '8d', '9s'],
        context: 'BB checks. Pot $10bb. Flop: 6h8d9s. You are IP with bottom set.',
        prompt: 'You flopped bottom set on 6h8d9s — a very coordinated board with straight possibilities. BB checks. Do you c-bet to protect, slowplay, or bet small?',
        options: [
          { id: 'check', label: 'Check back (slowplay)', quality: 'good', evLoss: 0.5, coaching: 'Checking back with bottom set on this wet board is a valid deceptive line. You disguise your hand and let BB barrel bluffs on the turn. Risk: you give free equity to BB\'s straight draws (75, T7, JT).' },
          { id: 'bet-small', label: 'Bet 4bb (40% pot)', quality: 'perfect', evLoss: 0, coaching: 'Small bet is optimal — you build a pot while keeping BB\'s wide range in. A larger sizing might fold out medium hands (top pair) that would continue for multiple streets.' },
          { id: 'bet-large', label: 'Bet 9bb (90% pot)', quality: 'good', evLoss: 0.7, coaching: 'Large bet protects against straight draw run-outs but folds out too much of BB\'s range on the flop. With a set, you want to keep hands in the pot, not fold them.' },
        ],
      },
      {
        street: 'turn',
        board: ['6h', '8d', '9s', 'Tc'],
        context: 'BB calls flop. Pot $18bb. Turn: Tc — straight completed. BB bets 12bb.',
        prompt: 'Turn Tc completes JT, T7, T8 straights. BB wakes up and leads into you for 12bb (67% pot). Do you call, raise, or fold?',
        options: [
          { id: 'fold', label: 'Fold (scared of the straight)', quality: 'mistake', evLoss: 8.5, coaching: 'Folding a set on the turn to one bet is a colossal mistake. You still have massive equity — any 6 or board pair on the river gives you a full house. Folding here surrenders an enormous equity advantage.' },
          { id: 'call', label: 'Call $12', quality: 'good', evLoss: 1.3, coaching: 'Calling controls the pot and lets you see the river without bloating the stack. However, sets should generally raise the turn to protect against straights completing and to build the pot for a river jam.' },
          { id: 'raise', label: 'Raise to $36bb', quality: 'perfect', evLoss: 0, coaching: 'Raise the turn. You have 10 outs to a full house or quads. When a straight is possible, you need to charge draws AND build a pot for a river jam. Raising also protects against fifth-street cards that complete the board against you.' },
        ],
      },
      {
        street: 'river',
        board: ['6h', '8d', '9s', 'Tc', 'Jd'],
        context: 'BB calls turn raise. Pot $90bb. River: Jd. BB checks. Stacks ~$28bb each.',
        prompt: 'Jd on the river makes four straights possible (9-high through Q-high). You\'re at a crossroads — jam, bet small, or check back?',
        options: [
          { id: 'check', label: 'Check back (missed value)', quality: 'mistake', evLoss: 12, coaching: 'Checking the river with a set after raising the turn is a major value leak. You built a pot specifically to jam the river. BB calling the turn raise means they have a hand. They will call a jam.' },
          { id: 'bet-small', label: 'Bet $14bb (small)', quality: 'good', evLoss: 4.5, coaching: 'A small bet extracts some value but leaves significant money behind. Given the pot size and stack depth, jamming is clearly better.' },
          { id: 'jam', label: 'Jam $28bb all-in', quality: 'perfect', evLoss: 0, coaching: 'Jam! You raised the turn for a reason. You have a set — the board is scary, but BB called a turn raise and checked. Their range still includes straights and two pairs. If they have a straight, they beat you... but the chance they fold a straight to a river jam is worth zero since you can\'t fold out their better hands anyway. Jam and hope for a set-over-set or boat situation.' },
        ],
      },
    ],
  },

  // ── srp-n05: BB KhJd — TPGK call-down through 3 barrels ─────────────────
  {
    id: 'srp-n05-bb-kjd-calldown',
    title: 'BB Defend — KJo Top Pair Gutshot Call-Down',
    description: 'Defend BB with KhJd against BTN triple-barrel aggression. Decide when to call, raise, or give up across three streets.',
    difficulty: 'intermediate',
    category: 'SRP',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Kh', 'Jd'],
    effectiveStack: 100,
    stakes: '$1/$2',
    summary: '',
    tags: [],
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to BTN who raises to $5. SB folds.',
        prompt: 'BB with KhJd facing BTN 2.5x open. Defend or 3-bet?',
        options: [
          { id: 'fold', label: 'Fold', quality: 'mistake', evLoss: 2.8, coaching: 'Folding KJo BB vs BTN is a clear mistake. The pot odds alone (~3.5:1) justify defending, and KJo is at the top of BB\'s defending range. You close the action and have strong equity.' },
          { id: 'call', label: 'Call $3', quality: 'perfect', evLoss: 0, coaching: 'Standard defend. KJo has ~43% equity vs BTN\'s wide opening range. You\'re getting good odds, closing the action, and the hand is strong enough to call-down on many boards.' },
          { id: '3bet', label: '3-bet to $17', quality: 'good', evLoss: 0.7, coaching: 'KJo is a marginal 3-bet OOP. It can work as a bluff to fold out BTN\'s wide range but you\'d rather call and see a flop. Calling is the standard line.' },
        ],
      },
      {
        street: 'flop',
        board: ['Kd', '7s', '3c'],
        context: 'Pot $10bb. Flop: Kd7s3c — dry top pair board. You act first OOP.',
        prompt: 'You top-paired on a dry board. BTN will c-bet wide here — do you lead, check-call, or check-raise?',
        options: [
          { id: 'check-fold', label: 'Check-fold', quality: 'mistake', evLoss: 5.5, coaching: 'Folding top pair on a dry board is a disaster. TPTK is one of the best hands in your range. Even if BTN has two pair, you still have outs. Never fold top pair on K73 rainbow.' },
          { id: 'check-raise', label: 'Check-raise to $22', quality: 'good', evLoss: 0.9, coaching: 'Check-raising is reasonable to deny equity and define BTN\'s range. However, you risk folding out all of BTN\'s bluffs and semi-bluffs that would otherwise continue and pay you off.' },
          { id: 'check-call', label: 'Check-call ~$7', quality: 'perfect', evLoss: 0, coaching: 'Check-call is the optimal line. Let BTN c-bet with their air and semi-bluffs. You\'ll call the flop, re-evaluate the turn. TPTK on a dry board plays well as a call-down hand — you beat a huge portion of BTN\'s barreling range.' },
        ],
      },
      {
        street: 'turn',
        board: ['Kd', '7s', '3c', '9h'],
        context: 'BTN bets 7bb on flop. You call. Pot $24bb. Turn: 9h. You act first OOP.',
        prompt: 'Turn 9h adds a gutshot draw (J8). BTN bet the flop — you called. Now you check to BTN. They bet 15bb (62% pot). Continue?',
        options: [
          { id: 'fold', label: 'Fold (9 is scary)', quality: 'mistake', evLoss: 5.1, coaching: 'Folding top pair to one bet on the turn is almost always a mistake in SRPs. BTN is barreling with their range — not just strong hands. Your K-J beats a large portion of their barreling range here.' },
          { id: 'raise', label: 'Check-raise to $45', quality: 'good', evLoss: 1.2, coaching: 'Check-raising forces BTN to commit or fold. Good if you think BTN is over-bluffing. Risk: you fold out bluffs and get committed vs two pair+ when called.' },
          { id: 'call', label: 'Call $15', quality: 'perfect', evLoss: 0, coaching: 'Call and proceed to the river. Your hand is too strong to fold. BTN\'s range after c-betting and turn-barreling includes plenty of air, AJ, QJ, and weaker Kx. TPTK is a clear continue.' },
        ],
      },
      {
        street: 'river',
        board: ['Kd', '7s', '3c', '9h', '4d'],
        context: 'BTN bets 15bb turn. You call. Pot $54bb. River: 4d — blank. BTN jams remaining $56bb.',
        prompt: 'River 4d is a blank. BTN jams into a $54bb pot. You need to call $56bb to win $110bb — pot odds ~50%. Do you call or fold with KJo TPTK?',
        options: [
          { id: 'fold', label: 'Fold (they must have it)', quality: 'mistake', evLoss: 7.2, coaching: 'Folding after calling two streets is a huge mistake. You only need to be good ~34% of the time to call (56 to win 110). BTN\'s triple-barrel range includes tons of semi-bluffs (missed flush draws, combo draws) that turned into river bluffs. You cannot fold top pair on K7394.' },
          { id: 'raise', label: 'Raise (you\'re all-in anyway)', quality: 'good', evLoss: 0, coaching: 'Raising doesn\'t make sense here — BTN is already jamming, so you\'re either calling or folding. Select call.' },
          { id: 'call', label: 'Call $56', quality: 'perfect', evLoss: 0, coaching: 'Call. The math is clear: you need to be good ~34% of the time and KJo on K7394 is good far more than 34% vs BTN\'s triple-barrel range. BTN would have raised flop or turn with sets. River jams from BTN here are polarized — some value, many bluffs. Call and win a big pot.' },
        ],
      },
    ],
  },

  // ── srp-n06: CO JcTd — top pair + BDFD protection OOP ───────────────────
  {
    id: 'srp-n06-co-jtd-top-pair-bdfd',
    title: 'CO vs BTN — JTo Top Pair + Backdoor Draw OOP',
    description: 'Open CO with JcTd and face BTN call. Flop gives top pair with a backdoor flush draw. Navigate three streets as the OOP aggressor.',
    difficulty: 'beginner',
    category: 'SRP',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BTN',
    heroCards: ['Jc', 'Td'],
    effectiveStack: 100,
    stakes: '$1/$2',
    summary: '',
    tags: [],
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to CO. You raise to $5. BTN calls. Pot $11bb.',
        prompt: 'Standard CO open with JcTd. Heading to the flop OOP vs BTN.',
        options: [
          { id: 'continue', label: 'Note: standard open — proceed to flop', quality: 'perfect', evLoss: 0, coaching: 'JTo is a standard CO open. BTN calling IP is expected. You\'ll have to play a SRP OOP with a hand that has good connectivity but no nut potential.' },
        ],
      },
      {
        street: 'flop',
        board: ['Jh', '6c', '2d'],
        context: 'Pot $11bb. Flop: Jh6c2d — dry top pair board. You act first OOP.',
        prompt: 'Dry Jh6c2d — you have top pair and a backdoor flush draw. BTN calls wide but often has overcards, pocket pairs, and gutshots here. How do you proceed?',
        options: [
          { id: 'check', label: 'Check (too scary to bet?)', quality: 'mistake', evLoss: 2.4, coaching: 'Checking top pair OOP on a dry board is a significant mistake. You have a strong hand and a range advantage on J-high boards (you open CO, have many JX hands). Bet and build the pot.' },
          { id: 'bet-small', label: 'Bet 5bb (45% pot)', quality: 'perfect', evLoss: 0, coaching: 'A standard 45% pot c-bet is perfect. You have top pair, a dry board, and a range advantage. This bet extracts value from BTN\'s 6x, 2x, and pocket pairs while giving no free cards.' },
          { id: 'bet-large', label: 'Bet 9bb (82% pot)', quality: 'good', evLoss: 0.5, coaching: 'Larger bet is reasonable for protection but fold equity isn\'t needed here — the board is dry and you want to keep BTN\'s medium hands in. A standard sizing is preferred.' },
        ],
      },
      {
        street: 'turn',
        board: ['Jh', '6c', '2d', '8s'],
        context: 'BTN calls flop. Pot $21bb. Turn: 8s. You act first OOP.',
        prompt: '8s turn — adds straight draws for BTN (T9, 97, 79). BTN called your flop bet. Your TPTK is still strong. Bet or pot control?',
        options: [
          { id: 'check-call', label: 'Check-call', quality: 'good', evLoss: 0.8, coaching: 'Check-calling is fine — you control the pot and see if BTN bets with their range. However, leading keeps pressure on overcards and weak pairs that might check back and hit the river.' },
          { id: 'check-fold', label: 'Check-fold', quality: 'mistake', evLoss: 6.2, coaching: 'Folding top pair on the turn because of potential straight draws is a huge mistake. BTN\'s range after one flop call on J62 is mostly unpaired hands, weak pairs, and draws. Your TPTK is a huge favorite against this distribution.' },
          { id: 'bet', label: 'Bet 13bb (62% pot)', quality: 'perfect', evLoss: 0, coaching: 'Continue barreling. Your TPTK is strong, and you want to deny equity to BTN\'s straight draws. A 62% sizing maintains pressure and builds the pot for a river value bet.' },
        ],
      },
      {
        street: 'river',
        board: ['Jh', '6c', '2d', '8s', '3c'],
        context: 'BTN calls turn. Pot $47bb. River: 3c — blank. You act first OOP.',
        prompt: 'River 3c is a total blank. BTN called two streets. Your top pair is likely best. How much do you extract?',
        options: [
          { id: 'check', label: 'Check (give up the initiative)', quality: 'mistake', evLoss: 5.1, coaching: 'Checking two pair / TPTK after betting two streets on a dry board and getting called is a value cut. The river is a blank — if BTN was drawing, they missed. They\'ll call one more bet with their pair or bluff-catcher.' },
          { id: 'bet-small', label: 'Bet 18bb (38% pot)', quality: 'good', evLoss: 1.2, coaching: 'A small bet targets bluff-catchers and weak pairs. Fine, but given two streets of calls, BTN has something that can pay a larger sizing.' },
          { id: 'bet-large', label: 'Bet 30bb (64% pot)', quality: 'perfect', evLoss: 0, coaching: 'Value bet for max extraction. BTN called flop and turn — they have a hand. On a blank river, lead 64% pot. Hands like KJ, QJ, TT, 88, 66 will call, and some stubborn Ax hands will call too. Three streets of value is the correct line.' },
        ],
      },
    ],
  },

  // ── srp-n07: BTN KhQh — delayed cbet after turn check-back ──────────────
  {
    id: 'srp-n07-btn-khqh-delayed-cbet',
    title: 'BTN Delayed C-Bet — KQs Misses Flop, Hits Turn',
    description: 'You open BTN with KhQh. The flop misses you completely. You check back and hit top pair on the turn. Exploit the delayed c-bet line.',
    difficulty: 'intermediate',
    category: 'SRP',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Kh', 'Qh'],
    effectiveStack: 100,
    stakes: '$1/$2',
    summary: '',
    tags: [],
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to BTN. You raise to $5. SB folds. BB calls.',
        prompt: 'KhQh — open, limp, or call?',
        options: [
          { id: 'raise', label: 'Raise to $5', quality: 'perfect', evLoss: 0, coaching: 'KQs is a premium BTN open — connected, strong, and IP. Standard raise to 2.5bb is correct.' },
          { id: 'limp', label: 'Limp $1', quality: 'mistake', evLoss: 1.5, coaching: 'Limping KQs from BTN wastes the hand\'s value and positional advantage. Always open-raise from the button with strong hands.' },
        ],
      },
      {
        street: 'flop',
        board: ['9d', '7c', '2h'],
        context: 'BB checks. Pot $10bb. Flop: 9d7c2h — you miss completely. You are IP.',
        prompt: 'You missed the flop with KhQh — no pair, no draw. BB checks. Do you c-bet, check back, or bet small?',
        options: [
          { id: 'bet-large', label: 'Bet 8bb (80% pot)', quality: 'mistake', evLoss: 1.8, coaching: 'Large c-bet with two overcards and no equity on a board that hits BB\'s range (low cards, pairs, sets) is a high-variance bluff. You\'ll fold out some of BB\'s range but get called or check-raised by a huge portion of it. Not profitable here.' },
          { id: 'bet-small', label: 'Bet 4bb (40% pot)', quality: 'good', evLoss: 0.6, coaching: 'Small c-bet has merit — it folds out some weak hands and builds a pot. But KQh has 6 outs to top pair or better and plays well when it hits. Checking back to realize equity freely is optimal.' },
          { id: 'check', label: 'Check back (take a free turn)', quality: 'perfect', evLoss: 0, coaching: 'Checking back on a board that favors BB\'s range (low connected cards) with two overcards is correct. You deny nothing by bluffing and you get a free card to hit K or Q. This sets up a powerful "delayed c-bet" on the turn.' },
        ],
      },
      {
        street: 'turn',
        board: ['9d', '7c', '2h', 'Kc'],
        context: 'BB checks turn. Pot $10bb. Turn: Kc — top pair! BB checks again.',
        prompt: 'You hit top pair with the Kc. BB checked twice (flop and turn). Now you have TPTK with the nut flush draw. This is a high-value delayed c-bet spot. How much?',
        options: [
          { id: 'check', label: 'Check again (slowplay)', quality: 'mistake', evLoss: 4.2, coaching: 'Checking back again is a mistake. You have top pair + nut flush draw. BB\'s range after two checks is capped (no sets, no two pairs) — they would bet those. You need to bet now while you have a clear advantage.' },
          { id: 'bet-small', label: 'Bet 5bb (50% pot)', quality: 'good', evLoss: 0.9, coaching: 'Small bet to pick up the pot and start building. But you have too much value here — TPTK + NFD — to bet small. A larger sizing extracts more from BB\'s second pair and Kx hands.' },
          { id: 'bet-large', label: 'Bet 9bb (90% pot)', quality: 'perfect', evLoss: 0, coaching: 'Large delayed c-bet. You checked back the flop (BB noted weakness), now you bet big on a K. BB will call with any pair — 9x, 7x, 2x, Kx hands lower than yours. And you still have the NFD for a monster river if called. This spot prints money.' },
        ],
      },
      {
        street: 'river',
        board: ['9d', '7c', '2h', 'Kc', '5d'],
        context: 'BB calls turn. Pot $28bb. River: 5d — blank. BB checks.',
        prompt: 'River 5d doesn\'t improve the board. BB called your turn bet and checks. Top pair, no flush. River value or give up?',
        options: [
          { id: 'check', label: 'Check back (confused about hand strength)', quality: 'mistake', evLoss: 4.8, coaching: 'Checking back TPTK after a delayed c-bet that got called is a value mistake. BB called the turn with something — 9x, 7x, Kx. On a blank river, lead for thin value. A check gives BB a free showdown with a hand that would call your bet.' },
          { id: 'bet-small', label: 'Bet 12bb (43% pot)', quality: 'perfect', evLoss: 0, coaching: 'Bet for thin value. BB has a one-pair hand or bluff-catcher that called the turn. A small-to-medium river bet extracts value from second pair and weak Kx while keeping them from feeling priced out. This completes the delayed c-bet line perfectly.' },
          { id: 'bet-large', label: 'Bet 25bb (89% pot)', quality: 'good', evLoss: 1.1, coaching: 'Large bet is too thin here. After a delayed c-bet call, BB\'s range is capped but includes some calls for a large sizing. The thin-value bet (40-50%) is better calibrated to extract from their range.' },
        ],
      },
    ],
  },

  // ── srp-n08: BB Ah9h — top pair + NFD check-raise ───────────────────────
  {
    id: 'srp-n08-bb-ah9h-checkraise',
    title: 'BB vs BTN — A9s Top Pair + NFD Check-Raise',
    description: 'Defend BB with Ah9h. Flop top pair and nut flush draw on a monotone board. Execute a check-raise to maximize value and leverage your draw.',
    difficulty: 'advanced',
    category: 'SRP',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Ah', '9h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    summary: '',
    tags: [],
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to BTN who raises to $5. SB folds.',
        prompt: 'BB with Ah9h facing BTN raise. How do you play this suited ace?',
        options: [
          { id: 'fold', label: 'Fold', quality: 'mistake', evLoss: 3.1, coaching: 'A9s is too strong to fold from BB. You have a suited ace with strong flush equity. At 3.5:1 pot odds, this is a clear defend — possibly a 3-bet candidate in some spots.' },
          { id: 'call', label: 'Call $3', quality: 'perfect', evLoss: 0, coaching: 'Standard defend. A9s is near the top of your BB calling range vs BTN. Strong equity, nut flush potential, and good playability on ace-high boards.' },
          { id: '3bet', label: '3-bet to $17', quality: 'good', evLoss: 0.4, coaching: 'A9s is a solid 3-bet bluff OOP — the nut flush draw equity makes it a good semi-bluff candidate. Calling is slightly better in position EV terms, but 3-betting is a strong play.' },
        ],
      },
      {
        street: 'flop',
        board: ['Ah', '6h', '2d'],
        context: 'Pot $10bb. Flop: Ah6h2d — you have top pair + NFD. You act first OOP.',
        prompt: 'You flopped top pair + nut flush draw (9 outs clean). BTN will c-bet wide on ace-high boards. Do you lead, check-call, or check-raise?',
        options: [
          { id: 'check-call', label: 'Check-call', quality: 'good', evLoss: 1.1, coaching: 'Check-calling is fine and keeps BTN\'s bluffs in. But you miss the chance to build a bigger pot when you have a huge equity advantage (top pair + 9 NFD outs). Check-raising extracts far more.' },
          { id: 'check-raise', label: 'Check, then raise to $22', quality: 'perfect', evLoss: 0, coaching: 'Check-raise is optimal. You check to invite a c-bet from BTN\'s wide range, then raise to build the pot. With top pair + NFD you want maximum pot size. BTN will call with 6x, flush draws, and Ax — all of which you dominate or have massive equity against.' },
          { id: 'lead', label: 'Lead $6bb (60% pot)', quality: 'good', evLoss: 0.8, coaching: 'Leading is reasonable and denies BTN the free option to check back. Check-raising is slightly better because you let BTN commit chips with their c-bet range first, then punish the whole range.' },
        ],
      },
      {
        street: 'turn',
        board: ['Ah', '6h', '2d', 'Td'],
        context: 'BTN calls check-raise. Pot $44bb. Turn: Td — adds a diamond draw. You act first OOP.',
        prompt: 'BTN called your check-raise. Td turn adds a backdoor diamond draw to the board. You still have TPTK + NFD. Bet big or control pot?',
        options: [
          { id: 'check', label: 'Check (pot control)', quality: 'mistake', evLoss: 5.5, coaching: 'Checking the turn with top pair + NFD after check-raising the flop is a big mistake. You built this pot precisely to bet multiple streets. A free card here risks BTN hitting a flush with a worse draw and feeling confident on the river.' },
          { id: 'bet-small', label: 'Bet 15bb (34% pot)', quality: 'good', evLoss: 1.8, coaching: 'Small turn bet maintains pressure but undersizes given your huge equity advantage. You want to build the pot for a river jam here.' },
          { id: 'bet-large', label: 'Bet 30bb (68% pot)', quality: 'perfect', evLoss: 0, coaching: 'Bet large — you need to build the stack for a river jam. With ~$26bb behind after this bet, you set up a profitable river shove. BTN\'s range (Ax, 6x, flush draws) will call a large turn bet given how much they\'ve already invested.' },
        ],
      },
      {
        street: 'river',
        board: ['Ah', '6h', '2d', 'Td', '3s'],
        context: 'BTN calls turn. Pot $104bb. River: 3s — blank. BTN checks. Stacks ~$22bb each.',
        prompt: 'River 3s bricks everything. BTN checks into the large pot. You have $22bb left with top pair + missed flush draw. What do you do?',
        options: [
          { id: 'check', label: 'Check (protect missed equity)', quality: 'mistake', evLoss: 6.5, coaching: 'Checking river with top pair in a massive pot after three streets of aggression is a value error. BTN called check-raise flop, large turn bet — they have something. Your Ah beats the vast majority of their range. Jam.' },
          { id: 'bet-small', label: 'Bet $10bb', quality: 'good', evLoss: 2.1, coaching: 'Betting small leaves value behind when BTN will call a jam anyway. With $22bb into a $104bb pot, jamming is clearly better — near-equivalent pot odds for BTN but you extract $12bb more.' },
          { id: 'jam', label: 'Jam $22bb all-in', quality: 'perfect', evLoss: 0, coaching: 'Jam the remaining $22bb. After three streets of aggression, BTN has Ax, 6x, or a stubborn draw. They will call $22 into a $104 pot almost every time. Your top pair is good vs their range. This is a clear value shove — you\'ve been driving the action from the beginning for exactly this payoff.' },
        ],
      },
    ],
  },

]
