import type { Puzzle } from '../puzzle-types'

export const PUZZLES_POSTFLOP: Puzzle[] = [
  // ── Pure Flop Decisions ──────────────────────────────────────────────────

  {
    id: 'p46',
    title: 'Air C-bet on Dry Board',
    description: 'You raised CO, BB called. Flop A85r — should you c-bet your nothing hand?',
    difficulty: 'beginner',
    category: 'C-bet',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BB',
    heroCards: ['7h', '6h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['Ac', '8d', '5s'],
        context: 'You open CO to 2.5BB, BB calls. Pot 5.5BB. BB checks.',
        prompt: 'You have 76h with no equity on A85r. How do you play?',
        options: [
          { id: 'bet33', label: 'Bet 33% pot (1.8BB)', quality: 'perfect', evLoss: 0, coaching: 'Dry ace-high boards heavily favour the PFR. A small c-bet forces folds from all Kx/Qx/pair hands at a great price. You have backdoor equity (straight) as backup.' },
          { id: 'check', label: 'Check back', quality: 'acceptable', evLoss: 0.4, coaching: 'Checking is fine with your backdoor outs, but you give up a very profitable bluff spot. Ace-high dry boards are the best to c-bet with air.' },
          { id: 'bet75', label: 'Bet 75% pot (4.1BB)', quality: 'mistake', evLoss: 1.2, coaching: 'Overbetting with zero equity on a board where villain folds enough to a small bet is inefficient. Use big sizes when you have equity or want to target specific hands.' },
        ],
      },
    ],
    summary: 'On dry ace-high boards, bet small (25–33%) with your entire range. The board strongly favours the c-bettor, so even pure air can c-bet here for a good price.',
    tags: ['c-bet', 'dry board', 'air', 'CO', 'flop'],
  },

  {
    id: 'p47',
    title: 'KK on Wet 3-bet Pot Flop',
    description: 'You 3-bet KK from SB vs BTN. Flop comes 9h8h7s — a nightmare board for overpairs.',
    difficulty: 'intermediate',
    category: '3-bet Pot',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'SB',
    villainPosition: 'BTN',
    heroCards: ['Kd', 'Ks'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'flop',
        board: ['9h', '8h', '7s'],
        context: 'BTN opens 2.5BB, you 3-bet to 10BB from SB, BTN calls. Pot 21BB. You are OOP.',
        prompt: 'KK on 987 two-tone in a 3-bet pot OOP. Bet or check?',
        options: [
          { id: 'check', label: 'Check (protect range)', quality: 'perfect', evLoss: 0, coaching: 'On connected wet boards in 3-bet pots OOP, checking with strong hands protects your checking range and avoids being check-raised off your equity. Check-call with KK here.' },
          { id: 'bet33', label: 'Bet 33% pot (7BB)', quality: 'acceptable', evLoss: 0.8, coaching: 'Small bet is defensible — you have equity and block some straights — but being check-raised puts you in an awful spot OOP. Checking is preferred by most solvers.' },
          { id: 'bet75', label: 'Bet 75% pot (16BB)', quality: 'mistake', evLoss: 2.5, coaching: 'Large bet OOP on a coordinated board invites check-raises you cannot call profitably. You often get stacked by straights and sets while folding out weaker hands.' },
        ],
      },
    ],
    summary: 'On highly connected boards in 3-bet pots OOP, check with strong hands to protect your range and avoid being blown off your equity by a check-raise.',
    tags: ['3-bet pot', 'OOP', 'overpair', 'wet board', 'check-call'],
  },

  {
    id: 'p48',
    title: 'Set on Monotone Board — Protection vs Value',
    description: 'You flop top set but the board is monotone. How do you extract value while managing flush risk?',
    difficulty: 'advanced',
    category: 'Value Bet',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Kc', 'Kd'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'flop',
        board: ['Kh', '5h', '5s'],
        context: 'You open BTN, BB calls. Pot 5.5BB. BB checks. Board is NOT monotone — you have top set on K55 rainbow.',
        prompt: 'Top set K55r. Villain checks. How do you size?',
        options: [
          { id: 'bet75', label: 'Bet 75% pot (4.1BB)', quality: 'perfect', evLoss: 0, coaching: 'Large bet is best here. The board is dry but you need to build a pot with top set. Villain has trips/Kx/pocket pairs that will call. Start building now.' },
          { id: 'bet33', label: 'Bet 33% pot (1.8BB)', quality: 'acceptable', evLoss: 0.9, coaching: 'Small bet is fine but undersizes relative to the stack-to-pot ratio. You want to build a pot over 3 streets with top set.' },
          { id: 'check', label: 'Check back (slowplay)', quality: 'mistake', evLoss: 1.5, coaching: 'Checking K55 is fine on some boards but here you need protection vs runner-runner hands and want to build the pot. Bet for value.' },
        ],
      },
    ],
    summary: 'With top set on dry boards, build the pot with a strong sizing. Slowplaying misses value and gives free cards to runner-runner draws.',
    tags: ['set', 'value bet', 'top set', 'BTN', 'dry board'],
  },

  {
    id: 'p49',
    title: 'Multiway TPTK — Check or Bet?',
    description: 'You have TPTK in a 3-way pot. Betting range is heavily capped in multiway scenarios.',
    difficulty: 'advanced',
    category: 'Multiway',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BTN+BB',
    heroCards: ['As', 'Jc'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['Jd', '7c', '3h'],
        context: 'CO opens, BTN and BB both call. Pot 7.5BB. BB checks, you act.',
        prompt: 'AJ TPTK on J73r in a 3-way pot, OOP. Both players behind. What do you do?',
        options: [
          { id: 'bet50', label: 'Bet 50% pot (3.75BB)', quality: 'perfect', evLoss: 0, coaching: 'TPTK is still strong enough to bet multiway on this dry board. A medium-sized bet charges draws (backdoor), protects against free cards, and gets value from Jx/7x.' },
          { id: 'check', label: 'Check (pot control)', quality: 'acceptable', evLoss: 0.6, coaching: 'Checking is not wrong with two players behind and possible over-pairs in their ranges, but you miss value from Jx hands that would call one street.' },
          { id: 'bet75', label: 'Bet 75% pot (5.6BB)', quality: 'mistake', evLoss: 1.1, coaching: 'Large bets multiway get called only by hands that beat you or have huge equity. Scale down for better risk-reward.' },
        ],
      },
    ],
    summary: 'In multiway pots, scale down your bet sizes. TPTK is strong enough to bet medium-sized for value, but avoid large bets that only get called by stronger hands.',
    tags: ['multiway', 'TPTK', 'flop', 'sizing', 'CO'],
  },

  {
    id: 'p50',
    title: 'TPTK Check-Raise Flop',
    description: 'Villain bets the flop and you have TPTK. When does check-raising top pair make sense?',
    difficulty: 'intermediate',
    category: 'Check-Raise',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Ad', 'Jh'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['Jc', '7d', '2s'],
        context: 'BTN opens to 2.5BB, you defend BB. Pot 5.5BB. You check, BTN bets 2.5BB.',
        prompt: 'AJ on J72r. BTN bets small. You have top two kicker — check-raise or call?',
        options: [
          { id: 'checkraise', label: 'Check-raise to 9BB', quality: 'perfect', evLoss: 0, coaching: 'J72r heavily favours the PFR range. Check-raising here protects your range, gets value from Jx, and denies equity from hands like 87/56. This board needs your check-raise range.' },
          { id: 'call', label: 'Call (float IP on turn)', quality: 'acceptable', evLoss: 0.7, coaching: 'Calling is fine — you have top pair but give villain a free card on turn. Check-raising builds a better pot and prevents villain from realising equity cheaply.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 8.0, coaching: 'Never fold top pair top kicker for this price. You are far ahead of BTN c-betting range on this board.' },
        ],
      },
    ],
    summary: 'On dry boards that heavily favour the pre-flop raiser, check-raise with strong made hands to protect your range and build value.',
    tags: ['check-raise', 'TPTK', 'BB defense', 'flop', 'J72'],
  },

  {
    id: 'p51',
    title: 'NFD Semi-Bluff Check-Raise',
    description: 'You have the nut flush draw and face a c-bet. Check-raising is a powerful semi-bluff line.',
    difficulty: 'intermediate',
    category: 'Semi-Bluff',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'CO',
    heroCards: ['Ah', '4h'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'flop',
        board: ['Kh', '8h', '3c'],
        context: 'CO opens, you defend BB. Pot 5.5BB. You check, CO bets 2.5BB.',
        prompt: 'You have A4h (NFD) on Kh8h3c. CO bets 2.5BB into 5.5BB. Options?',
        options: [
          { id: 'checkraise', label: 'Check-raise to 10BB', quality: 'perfect', evLoss: 0, coaching: 'With the NFD and ace blocker you have a perfect semi-bluff check-raise. You deny equity to pairs, have 9 nut flush outs, and might fold out Qx/Jx immediately.' },
          { id: 'call', label: 'Call', quality: 'acceptable', evLoss: 0.5, coaching: 'Calling is fine — you have 9 outs to the nuts — but check-raising adds fold equity and builds a larger pot when you hit.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 4.0, coaching: 'Folding the nut flush draw with an over-card to a small bet is a massive mistake. Even calling has strong equity here.' },
        ],
      },
    ],
    summary: 'The nut flush draw is a prime semi-bluff check-raise hand. You combine immediate fold equity with 9 clean outs to the nuts.',
    tags: ['semi-bluff', 'NFD', 'check-raise', 'BB', 'flush draw'],
  },

  {
    id: 'p52',
    title: 'Donk Bet Two Pair on Dynamic Board',
    description: 'You flopped two pair OOP. The board is draw-heavy — do you donk or check?',
    difficulty: 'intermediate',
    category: 'Donk Bet',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['9d', '7s'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['9c', '7h', '5d'],
        context: 'BTN opens, you call from BB. Pot 5.5BB. You are OOP.',
        prompt: 'You have 97 (two pair) on 975. Dynamic board. Lead out (donk) or check?',
        options: [
          { id: 'donk50', label: 'Donk bet 50% pot (2.75BB)', quality: 'perfect', evLoss: 0, coaching: 'On a connected board where you have two pair, donking protects your hand, charges flush/straight draws, and denies BTN the ability to c-bet cheaply. Modern solvers donk heavily here.' },
          { id: 'check', label: 'Check (c/r or c/c)', quality: 'acceptable', evLoss: 0.8, coaching: 'Check-calling or check-raising is fine but allows BTN to check back and give you a free card on turn. Donking is more proactive protection.' },
          { id: 'checkraise', label: 'Check, plan to check-raise', quality: 'good', evLoss: 0.3, coaching: 'Check-raising is also strong here but depends on BTN betting. If BTN checks back you lose value. Donking ensures the pot grows.' },
        ],
      },
    ],
    summary: 'On connected boards where you hold two pair OOP, donk betting charges draws and prevents villain from realising cheap equity.',
    tags: ['donk bet', 'two pair', 'BB', 'connected board', 'flop'],
  },

  {
    id: 'p53',
    title: 'Set vs Flush Draw — Bet Sizing',
    description: 'You flopped a set on a two-tone board. How do you charge the flush draw effectively?',
    difficulty: 'intermediate',
    category: 'Value Bet',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['8c', '8s'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['8h', '7h', '6c'],
        context: 'BTN opens, BB calls. Pot 5.5BB. BB checks. You have middle set on 876 two-tone.',
        prompt: '88 on 876hh — you have the set but board is very wet. How do you size?',
        options: [
          { id: 'bet75', label: 'Bet 75% pot (4.1BB)', quality: 'perfect', evLoss: 0, coaching: 'Large bet is correct. The board is extremely wet with straight and flush draws everywhere. You need to charge all of them maximum equity. Your set is vulnerable and you want to build a pot to get it in.' },
          { id: 'bet33', label: 'Bet 33% pot (1.8BB)', quality: 'mistake', evLoss: 1.8, coaching: 'Small bet lets all draws peel cheaply. On highly wet boards with sets, use large bets. You need to extract value and charge draws before bad cards fall.' },
          { id: 'check', label: 'Check (slowplay)', quality: 'mistake', evLoss: 2.5, coaching: 'Checking a set on 876 two-tone is a serious mistake. Too many free cards can complete straights and flushes. Bet and build the pot now.' },
        ],
      },
    ],
    summary: 'On wet boards with sets, bet large to charge draws. Never slowplay on highly connected two-tone boards — the hand is vulnerable.',
    tags: ['set', 'wet board', 'sizing', 'flush draw', 'straight draw'],
  },

  // ── Pure Turn Decisions ──────────────────────────────────────────────────

  {
    id: 'p54',
    title: 'Delayed C-bet on the Turn',
    description: 'You checked back the flop with a strong hand. Now the turn comes — delayed c-bet timing.',
    difficulty: 'intermediate',
    category: 'Delayed C-bet',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Ah', 'Qd'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'turn',
        board: ['Ac', '7d', '3s', '2h'],
        context: 'BTN opens, BB calls. Flop A73r: BB checks, you check back (pot control / deception). Turn 2h. BB checks again.',
        prompt: 'AQ on A7322. You checked flop, BB checks turn. Delayed c-bet now?',
        options: [
          { id: 'bet50', label: 'Bet 50% pot (2.75BB)', quality: 'perfect', evLoss: 0, coaching: 'After checking back the flop, a turn bet represents a wider range (pocket pairs, 2x, floats). BB has capped their range by checking twice. Now is the time to extract value.' },
          { id: 'check', label: 'Check again (go for thin river)', quality: 'acceptable', evLoss: 0.9, coaching: 'Checking again builds a larger river pot but gives free cards to hands with equity (3x, gutshots). Betting turn is more reliable value extraction.' },
          { id: 'bet75', label: 'Bet 75% pot (4.1BB)', quality: 'good', evLoss: 0.2, coaching: 'Large bet is also fine — represents a polarised range. Either sizing works, but medium sizing gets more calls from weak Ax and 7x.' },
        ],
      },
    ],
    summary: 'Delayed c-bets on turns are powerful because villain\'s check twice caps their range. Bet for value with TPTK when the board remains benign.',
    tags: ['delayed c-bet', 'turn', 'TPTK', 'BTN', 'deception'],
  },

  {
    id: 'p55',
    title: 'Turn Probe Bet from BB',
    description: 'PFR checked back the flop. As the pre-flop caller, you can probe the turn to take initiative.',
    difficulty: 'advanced',
    category: 'Turn Probe',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'CO',
    heroCards: ['Td', '9d'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'turn',
        board: ['Qh', '8c', '3d', 'Jd'],
        context: 'CO opens, BB calls. Flop Q83r: you check, CO checks back. Turn Jd — you picked up an OESD + FD (T9d).',
        prompt: 'CO checked back flop. Turn brings J giving you monster draw. Do you probe?',
        options: [
          { id: 'probe50', label: 'Probe bet 50% pot (2.75BB)', quality: 'perfect', evLoss: 0, coaching: 'CO checking back flop greatly caps their range (likely no strong Qx). You have 15 outs (9 diamonds + 7s and Ks for straight). Probing charges CO and takes initiative with massive equity.' },
          { id: 'check', label: 'Check (call or raise if CO bets)', quality: 'acceptable', evLoss: 0.8, coaching: 'Checking is fine but gives CO a free shot at the pot. With 15 outs you have too much equity to be passive. Probe and take the pot or build it.' },
          { id: 'probe75', label: 'Probe bet 75% pot (4.1BB)', quality: 'good', evLoss: 0.3, coaching: 'Larger probe also works. You want to apply maximum pressure on a capped opponent.' },
        ],
      },
    ],
    summary: 'When PFR checks back the flop, their range is capped. Probing the turn with strong draws takes advantage of their weakness and builds pot for your equity.',
    tags: ['turn probe', 'combo draw', 'BB', 'turn', 'aggression'],
  },

  {
    id: 'p56',
    title: 'Double Barrel Decision — Brick Turn',
    description: 'You c-bet the flop and got called. Turn bricks. Do you continue or give up?',
    difficulty: 'intermediate',
    category: 'Double Barrel',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Kd', 'Qh'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'turn',
        board: ['Jc', '7h', '3s', '2d'],
        context: 'BTN opens, BB defends. Flop J73r: you c-bet 2.5BB (into 5.5BB), BB calls. Turn 2d — total brick.',
        prompt: 'KQ (two overcards, gutshot to AT) on J7322. BB calls flop. Do you double barrel?',
        options: [
          { id: 'barrel50', label: 'Double barrel 50% pot (5.25BB)', quality: 'perfect', evLoss: 0, coaching: 'You have two overcards plus gutshot (8 outs to top pair or better). BB\'s calling range on J73 is Jx, 7x, draws. Many check the turn. A turn barrel puts maximum pressure and you have equity to fall back on.' },
          { id: 'check', label: 'Check (give up)', quality: 'mistake', evLoss: 1.5, coaching: 'Giving up with two overcards and a gutshot abandons 8 clean outs and lets BB realise their equity for free. This is a mandatory barrel spot.' },
          { id: 'allin', label: 'Shove (over-barrel)', quality: 'mistake', evLoss: 2.0, coaching: 'Shoving 100BB deep here is too aggressive for a semi-bluff spot. Scale to a normal barrel sizing.' },
        ],
      },
    ],
    summary: 'Double barrel when you have equity (overcards, gutshot) even on brick turns. Give up when you have zero equity and villain\'s range likely hit the board hard.',
    tags: ['double barrel', 'semi-bluff', 'turn', 'overcards', 'gutshot'],
  },

  {
    id: 'p57',
    title: 'Turn Overbet with Nut Advantage',
    description: 'You hold the nuts with a polarised range advantage on the turn. Overbet to maximum value.',
    difficulty: 'advanced',
    category: 'Overbet',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Ah', 'Kh'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'turn',
        board: ['Qh', 'Th', '5d', 'Jh'],
        context: 'BTN 3-bets SB, BB cold calls. Wait — BTN opens, BB defends. You bet flop QT5h, BB calls. Turn Jh — you made the royal flush draw (A-K-Q-J-T flush draw, basically already the nuts).',
        prompt: 'AKh on QhTh5dJh — you have the royal flush draw (already a nut flush). BB checks. Overbet?',
        options: [
          { id: 'overbet150', label: 'Overbet 150% pot (21BB)', quality: 'perfect', evLoss: 0, coaching: 'You have the nut flush plus a made straight plus royal draw. Your range advantage here is extreme. Overbetting forces max decisions from two pairs, sets, and weaker flushes.' },
          { id: 'bet75', label: 'Bet 75% pot (10.5BB)', quality: 'good', evLoss: 0.8, coaching: 'Normal sized bet captures value but misses the premium opportunity to overbet when you have a massive range and equity advantage.' },
          { id: 'check', label: 'Check (trap)', quality: 'mistake', evLoss: 2.5, coaching: 'Slowplaying the nut flush on a very wet board in position is a mistake. Bet large — you want to build a pot you can stack villains in.' },
        ],
      },
    ],
    summary: 'Overbet when you have a massive range and equity advantage. The nut flush on a wet board is a prime candidate for large or over-sized bets.',
    tags: ['overbet', 'nut flush', 'turn', 'polarised', 'value'],
  },

  {
    id: 'p58',
    title: 'Backdoor Equity Float on Turn',
    description: 'You called the flop with backdoor outs. Turn gives you a real draw — time to float or raise?',
    difficulty: 'intermediate',
    category: 'Float',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['5h', '6h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'turn',
        board: ['Kc', '7d', '2h', '4h'],
        context: 'BTN opens, BB calls. Flop K72: BTN c-bets, you call (backdoor flush + gutshot). Turn 4h — you now have flush draw + OESD.',
        prompt: '56h picked up NFD + straight draw on 4h turn. BTN bets again (50% pot). What now?',
        options: [
          { id: 'call', label: 'Call (peel river)', quality: 'good', evLoss: 0.3, coaching: 'Calling is fine — you have 15 outs. The question is whether raising adds more EV through fold equity.' },
          { id: 'raise', label: 'Raise to 3x (semi-bluff)', quality: 'perfect', evLoss: 0, coaching: 'With 15 outs and fold equity, raising is the highest EV play. You can win immediately or hit one of your many outs. BTN has a wide range that will fold the turn.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 5.0, coaching: 'Folding 15 outs to a half-pot bet is a massive error. You have roughly 55% equity to improve to the best hand by the river.' },
        ],
      },
    ],
    summary: 'When you pick up a combo draw on the turn after floating the flop, raising becomes the highest EV option due to combined equity and fold equity.',
    tags: ['combo draw', 'turn', 'float', 'semi-bluff', 'raise'],
  },

  {
    id: 'p59',
    title: 'Turn Check-Raise Semi-Bluff',
    description: 'You check-called the flop and now face a turn bet with a strong draw. Check-raise opportunity.',
    difficulty: 'intermediate',
    category: 'Check-Raise',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Jd', 'Td'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'turn',
        board: ['Qd', '9c', '3h', '8d'],
        context: 'BTN opens, BB defends. Flop Q93: you check, BTN bets, you call (gutshot). Turn 8d — you have OESD + FD (JTd).',
        prompt: 'JTd on Qd9c3h8d — OESD plus nut flush draw. BTN bets 60% pot. Check-raise?',
        options: [
          { id: 'checkraise', label: 'Check-raise to 3x', quality: 'perfect', evLoss: 0, coaching: 'This is a textbook check-raise semi-bluff. You have a massive combo draw (15 outs), range advantage on 8d (many 8x, Tx in your BB defense range), and fold equity against BTN\'s c-bet range.' },
          { id: 'call', label: 'Call (see river)', quality: 'acceptable', evLoss: 1.0, coaching: 'Calling is fine with 15 outs, but you give BTN the chance to check back a river. Check-raising extracts maximum EV from this hand.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 7.0, coaching: 'You have 15 outs and are never folding here for any reasonable price.' },
        ],
      },
    ],
    summary: 'Combo draws (straight + flush) are the premier check-raise semi-bluff hands on the turn. Combine your equity with fold equity for maximum EV.',
    tags: ['check-raise', 'combo draw', 'turn', 'BB', 'semi-bluff'],
  },

  {
    id: 'p60',
    title: 'Turn Bet Sizing with Combo Draw',
    description: 'You are the aggressor with a combo draw on the turn. Which sizing maximises your EV?',
    difficulty: 'intermediate',
    category: 'Sizing',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['9h', '8h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'turn',
        board: ['Tc', '7d', '2s', '6h'],
        context: 'BTN opens, BB defends. Flop T72r: you c-bet small, BB calls. Turn 6h gives you OESD (98, needs 5 or J) plus backdoor heart draw.',
        prompt: '98h on T7266h. You have OESD on turn. BB checks. Sizing?',
        options: [
          { id: 'bet75', label: 'Bet 75% pot (7.5BB)', quality: 'perfect', evLoss: 0, coaching: 'Large sizing forces BB to make big decisions with marginal hands. You have real equity and want to build a pot. This sizing also polarises you well for river.' },
          { id: 'bet33', label: 'Bet 33% pot (3.3BB)', quality: 'acceptable', evLoss: 0.9, coaching: 'Small bet keeps pot small — fine for pot control, but you have too much equity to bet small here. Build a bigger pot.' },
          { id: 'check', label: 'Check (free card)', quality: 'mistake', evLoss: 1.5, coaching: 'Checking gives up initiative and the pot while having 8 clean outs. Don\'t take free cards with strong semi-bluffs in position.' },
        ],
      },
    ],
    summary: 'With strong draws in position, use large turn bets to build pots and polarise your range for river. Small bets under-realise the value of your equity.',
    tags: ['OESD', 'sizing', 'turn', 'semi-bluff', 'BTN'],
  },

  {
    id: 'p61',
    title: 'Turn Pot Control with TPTK',
    description: 'TPTK on a wet turn — should you try for all 3 streets or apply the brakes?',
    difficulty: 'intermediate',
    category: 'Pot Control',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BB',
    heroCards: ['Ah', 'Jd'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'turn',
        board: ['Jc', '8h', '5s', '9h'],
        context: 'CO opens, BB calls. Flop J85: you c-bet 3BB (into 5.5BB), BB calls. Turn 9h — connects with draws and makes many straights.',
        prompt: 'AJ (TPTK) on J8559h. BB checks. Continue value-betting or control pot?',
        options: [
          { id: 'check', label: 'Check back (pot control)', quality: 'perfect', evLoss: 0, coaching: 'The turn 9h completed T7, 76, and added flush draw. TPTK is no longer a clear value bet OOP. Check back, keep the pot manageable, and call a small river bet.' },
          { id: 'bet50', label: 'Bet 50% pot (5.75BB)', quality: 'acceptable', evLoss: 0.7, coaching: 'Betting is fine but you get called only by hands that beat or are close to AJ. The board has gotten dangerous enough that checking is preferred.' },
          { id: 'bet75', label: 'Bet 75% pot (8.5BB)', quality: 'mistake', evLoss: 2.0, coaching: 'Large bet on this wet board invites check-raises from straights and sets. You\'re effectively making the pot too big to fold but too uncertain to continue.' },
        ],
      },
    ],
    summary: 'When the board gets wet on the turn, pot control with marginal one-pair hands prevents building pots where you are often behind.',
    tags: ['pot control', 'TPTK', 'turn', 'wet board', 'check-back'],
  },

  // ── Pure River Decisions ─────────────────────────────────────────────────

  {
    id: 'p62',
    title: 'Thin River Value — Second Pair',
    description: 'You reach the river with second pair. Is there value in betting thin, or should you check?',
    difficulty: 'intermediate',
    category: 'Thin Value',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Kc', '9d'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'river',
        board: ['Ac', '9h', '3s', '2d', '7c'],
        context: 'BTN opens, BB defends. You c-bet flop and turn, BB calls both. River 7c. BB checks. Pot ~40BB.',
        prompt: 'K9 (second pair nines) on A9322 7c. BB checks river. Thin value or check?',
        options: [
          { id: 'betsmall', label: 'Bet 25% pot (10BB)', quality: 'perfect', evLoss: 0, coaching: 'Small river bet for thin value is perfect here. BB has been calling with pairs, weak Ax. You beat all 9x, 7x, 3x, 2x and many under-pairs. A small bet gets called by worse and folds better.' },
          { id: 'check', label: 'Check back', quality: 'acceptable', evLoss: 0.7, coaching: 'Checking is fine as a showdown value play, but you leave chips behind vs weaker calling hands. Small value bets on rivers vs capped ranges capture extra EV.' },
          { id: 'bet75', label: 'Bet 75% pot (30BB)', quality: 'mistake', evLoss: 3.0, coaching: 'Large river bet with second pair gets called only by better hands or strong bluff-catches. Size down drastically for thin value.' },
        ],
      },
    ],
    summary: 'Thin river value bets (20–30% pot) extract EV from weaker calling hands. Scale down dramatically from turn bets when your range is relatively weak.',
    tags: ['thin value', 'river', 'second pair', 'BTN', 'small bet'],
  },

  {
    id: 'p63',
    title: 'River Overbet Bluff with Blockers',
    description: 'You missed your draw but hold key blockers. Overbet bluffing on the river is a high-EV line.',
    difficulty: 'advanced',
    category: 'River Bluff',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Ah', '5h'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'river',
        board: ['Kh', '9h', '4s', '2d', '3c'],
        context: 'BTN opens, BB defends. You c-bet flop (flush draw), turn (draw + gutshot), river bricked. BB checks river. Pot ~45BB.',
        prompt: 'A5h missed everything on K9432. BB checks. Overbet bluff or give up?',
        options: [
          { id: 'overbet150', label: 'Overbet bluff 150% pot (67BB)', quality: 'perfect', evLoss: 0, coaching: 'Perfect overbet bluff spot: (1) You block Ax, reducing BB\'s calling range. (2) A5 is a pure bluff candidate — no showdown value. (3) BB\'s range is capped (no sets called two streets on this board). Overbet or fold — don\'t bet small.' },
          { id: 'bet50', label: 'Bet 50% pot (22BB)', quality: 'mistake', evLoss: 2.0, coaching: 'Small bluff invites calls from middle pairs and weak Kx. If you\'re bluffing, go big to fold those hands, or don\'t bluff at all.' },
          { id: 'check', label: 'Give up (check back)', quality: 'acceptable', evLoss: 0.8, coaching: 'Giving up with zero equity is safe. The overbet bluff is clearly the highest EV play but checking is correct if you don\'t want to risk the stack.' },
        ],
      },
    ],
    summary: 'River overbet bluffs work best when: (1) you hold blockers to villain\'s calling hands, (2) you have zero showdown value, (3) villain\'s range is capped by the line.',
    tags: ['river bluff', 'overbet', 'blocker', 'BTN', 'missed draw'],
  },

  {
    id: 'p64',
    title: 'River Bluff Catch vs 2x Overbet',
    description: 'Villain fires a 2x pot overbet on the river. You have a medium strength hand — call or fold?',
    difficulty: 'expert',
    category: 'Hero Call',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Kd', 'Jh'],
    effectiveStack: 100,
    stakes: '$5/$10',
    steps: [
      {
        street: 'river',
        board: ['Kc', '9h', '4d', '2s', '7h'],
        context: 'BB defends vs BTN. You check-call flop (top pair), check-call turn (same). River 7h. You check. BTN fires 2x pot overbet (all-in essentially).',
        prompt: 'KJ (top pair, third kicker) on K9427. BTN 2x overbets river into you. Call or fold?',
        options: [
          { id: 'call', label: 'Call (hero bluff catch)', quality: 'perfect', evLoss: 0, coaching: 'BTN\'s 2x overbet is polar: either sets/two-pair for value or missed draws as bluffs. KJ beats all bluffs. BTN\'s range on this runout includes Ah5h (missed flush), QhJh, 56 (gutshot). With top pair third kicker, you block very few of their value hands. Call.' },
          { id: 'fold', label: 'Fold (respect the overbet)', quality: 'mistake', evLoss: 4.0, coaching: 'Folding top pair to an overbet is often correct against tight players but this board is a bluffing paradise. You need only ~33% equity to call a 2x overbet.' },
        ],
      },
    ],
    summary: 'Against river overbets, you need ~33% equity. If villain\'s bluffing frequency matches their value hands on this run-out, calling becomes profitable even with one-pair hands.',
    tags: ['hero call', 'river', 'overbet', 'bluff catch', 'expert'],
  },

  {
    id: 'p65',
    title: 'Hero Call with Ace-High',
    description: 'Your hand is ace-high and villain bets the river. Sometimes ace-high is the best hand.',
    difficulty: 'expert',
    category: 'Hero Call',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Ad', 'Qc'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'river',
        board: ['Jh', '9c', '6s', '4d', '2h'],
        context: 'BTN 3-bets, BB calls. You c-bet flop with backdoor equity, BB calls. Turn and river checked through by you. River BB fires 70% pot.',
        prompt: 'AQ (ace-high) on J9642 all rainbow. BB leads river 70% pot. What do you do?',
        options: [
          { id: 'call', label: 'Call (ace-high is good here)', quality: 'perfect', evLoss: 0, coaching: 'In a 3-bet pot where you checked back twice, BB\'s lead represents missed draws looking to bluff you off AQ (no showdown value to them). BB\'s missed draws include KT, T8, Q7, 85. AQ beats all of them.' },
          { id: 'fold', label: 'Fold (ace-high can\'t be good)', quality: 'mistake', evLoss: 3.5, coaching: 'This is the most common mistake — folding ace-high when it\'s actually ahead of villain\'s bluffing range. Count their missed draws and compare to value hands.' },
          { id: 'raise', label: 'Raise (bluff catch + fold equity)', quality: 'mistake', evLoss: 5.0, coaching: 'Raising ace-high with no showdown value advantage turns a bluff catcher into a bluff, which is too expensive here.' },
        ],
      },
    ],
    summary: 'Ace-high can be a profitable bluff catch when your range is capped and villain holds many missed draws. Read the specific board texture and line.',
    tags: ['hero call', 'ace-high', 'river', 'bluff catch', 'expert'],
  },

  {
    id: 'p66',
    title: 'River Trap Check-Raise with Nuts',
    description: 'You hold the nuts on the river OOP. Check-raise or lead for max value?',
    difficulty: 'advanced',
    category: 'Check-Raise',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Ah', '2h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'river',
        board: ['5h', '4h', '3c', 'Kd', '7s'],
        context: 'BB defends vs BTN. Flop and turn went check-call. River 7s. You hold A2h — nut straight (A2345).',
        prompt: 'You rivered the nut straight (A2). BTN has been barreling. Check or lead river?',
        options: [
          { id: 'check', label: 'Check (trap check-raise)', quality: 'perfect', evLoss: 0, coaching: 'Given BTN has been betting every street, they are likely to fire river again. Check-raising the nuts OOP extracts max value — you convert their bet into a 3x pot contribution instead of calling.' },
          { id: 'donk75', label: 'Lead out 75% pot', quality: 'acceptable', evLoss: 0.8, coaching: 'Leading captures value but loses the check-raise upside. If BTN is bluffing frequently, checking captures more total chips.' },
          { id: 'allin', label: 'Shove all-in', quality: 'mistake', evLoss: 2.0, coaching: 'Shoving the river as a donk bet gets called only by better (impossible — you have nuts) or scared. Check-raising extracts more when villain is likely to bet.' },
        ],
      },
    ],
    summary: 'With the nuts OOP vs a player who has been barreling, check-raising extracts more total value than leading out — you convert their bet plus your raise.',
    tags: ['check-raise', 'nuts', 'river', 'BB', 'trap'],
  },

  {
    id: 'p67',
    title: 'River Donk Bet with Second Pair',
    description: 'OOP on the river with second pair. Villain checked back the turn — can you donk for thin value?',
    difficulty: 'intermediate',
    category: 'Thin Value',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'CO',
    heroCards: ['Qh', '9d'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'river',
        board: ['Ac', '9s', '3h', '2c', '7d'],
        context: 'BB defends vs CO. Flop A93: you check-call. Turn 2c: CO checks back. River 7d. Pot ~18BB.',
        prompt: 'Q9 (second pair) OOP. CO checked back turn (capped range). River 7d — lead or check?',
        options: [
          { id: 'lead33', label: 'Lead 33% pot (6BB) for thin value', quality: 'perfect', evLoss: 0, coaching: 'CO checking back the turn greatly caps their range — they likely have medium pairs (77-JJ), busted draws, or weak Ax. Q9 beats most of this range. A small donk extract value before they check back again.' },
          { id: 'check', label: 'Check (showdown)', quality: 'acceptable', evLoss: 0.8, coaching: 'Checking is safe but misses thin value vs CO\'s capped range. Use the turn check-back as information — their range is weak.' },
          { id: 'lead75', label: 'Lead 75% pot (13.5BB)', quality: 'mistake', evLoss: 2.5, coaching: 'Large donk bet with second pair — you only get called by better. Small bets extract thin value while keeping the pot manageable.' },
        ],
      },
    ],
    summary: 'When villain checks back the turn (capping their range), small donk leads on the river extract thin value before they get a free showdown.',
    tags: ['donk bet', 'thin value', 'river', 'capped range', 'BB'],
  },

  {
    id: 'p68',
    title: 'Check Back River — Pot Control',
    description: 'You have top pair weak kicker (TPWK) in position on the river. Bet or check back?',
    difficulty: 'beginner',
    category: 'Pot Control',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Jc', '4d'],
    effectiveStack: 100,
    stakes: '$0.50/$1',
    steps: [
      {
        street: 'river',
        board: ['Jd', '9h', '3s', '2c', '5h'],
        context: 'BTN opens, BB defends. Flop J93: BB checks, you c-bet, BB calls. Turn 2: BB checks, you check back. River 5h. BB checks.',
        prompt: 'J4 (TPWK) on J93225h. BB checks river. Value bet or check back?',
        options: [
          { id: 'check', label: 'Check back (showdown)', quality: 'perfect', evLoss: 0, coaching: 'TPWK with a 4 kicker is a showdown hand. Betting river gets called by better Jx and folds all worse. Your kicker is too weak to extract thin value here — go to showdown.' },
          { id: 'betsmall', label: 'Bet 25% pot (thin value)', quality: 'mistake', evLoss: 0.9, coaching: 'Even small bets with J4 are a mistake. You lose to all Jx with better kickers and fold the exact hands you beat (busted draws). Check back.' },
          { id: 'bet50', label: 'Bet 50% pot', quality: 'mistake', evLoss: 2.0, coaching: 'Betting 50% with J4 results in a "betting for worse to call and better to fold" situation — the definition of a losing bet.' },
        ],
      },
    ],
    summary: 'With top pair weak kicker in position, prefer checking back rivers for showdown. You lose to all better kickers and fold all worse hands.',
    tags: ['pot control', 'TPWK', 'river', 'check-back', 'beginner'],
  },

  {
    id: 'p69',
    title: 'Thin River Raise for Extra Value',
    description: 'Villain bets small on the river. You have two pair. Can you raise thin for value?',
    difficulty: 'advanced',
    category: 'Thin Value',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Jh', '9s'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'river',
        board: ['Jd', '9c', '4h', '2s', '6d'],
        context: 'BB defends vs BTN. You check-called flop and check-called turn. River 6d. BTN bets 25% pot (thin value from their side). Pot ~42BB.',
        prompt: 'J9 (top two pair) on J9426. BTN bets small (thin value range). Raise or call?',
        options: [
          { id: 'raise', label: 'Raise to 3.5x BTN bet', quality: 'perfect', evLoss: 0, coaching: 'BTN sizing thin for value with top pair and sets. You hold top two pair and are ahead of most of their value range. Raising extracts extra chips. BTN will call with Jx and 9x, and you beat all of those.' },
          { id: 'call', label: 'Call (safe)', quality: 'good', evLoss: 0.6, coaching: 'Calling is fine and captures value safely, but raising is higher EV when BTN uses a thin-value sizing that induces calls from worse.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 15.0, coaching: 'Never fold two pair on the river for any bet. This is a clear value hand.' },
        ],
      },
    ],
    summary: 'When villain uses a thin-value small bet on the river, raising with two pair extracts extra chips from their one-pair value hands.',
    tags: ['thin value', 'river raise', 'two pair', 'BB', 'advanced'],
  },

  // ── Flop → Turn Sequences ────────────────────────────────────────────────

  {
    id: 'p70',
    title: 'C-bet Then Double Barrel',
    description: 'You c-bet the flop and got called. The turn changes the dynamic — commit or check?',
    difficulty: 'intermediate',
    category: 'Double Barrel',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BB',
    heroCards: ['Ad', 'Tc'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['Ac', '7h', '3s'],
        context: 'CO opens, BB defends. Pot 5.5BB. BB checks.',
        prompt: 'AT on A73r OOP. BB checks. How do you bet the flop?',
        options: [
          { id: 'bet33', label: 'Bet 33% pot (1.8BB)', quality: 'perfect', evLoss: 0, coaching: 'Small c-bet on dry ace-high boards is the solver line. Gets called by all 7x, 3x, and draws.' },
          { id: 'check', label: 'Check back (deception)', quality: 'acceptable', evLoss: 0.4, coaching: 'Checking is fine for deception with TPTK, but you miss value from medium pairs and draws.' },
          { id: 'bet75', label: 'Bet 75% pot (4.1BB)', quality: 'mistake', evLoss: 1.0, coaching: 'Large bet on dry board folds everything worse and gets called/raised by better. Use small sizing.' },
        ],
      },
      {
        street: 'turn',
        board: ['Ac', '7h', '3s', 'Td'],
        context: 'You bet 33% flop, BB called. Turn Td — you improved to two pair (AT). BB checks.',
        prompt: 'You improved to two pair AT on A7T. BB checks turn. Continue with double barrel?',
        options: [
          { id: 'bet50', label: 'Bet 50% pot (4.75BB)', quality: 'perfect', evLoss: 0, coaching: 'The turn improved your hand to two pair. BB is unlikely to have AT in their BB defense range. Now is the time to build the pot — bet for value vs Ax, 7x, Tx.' },
          { id: 'check', label: 'Check back (trap)', quality: 'acceptable', evLoss: 0.7, coaching: 'Checking is fine as a trap but misses value from medium hands that would call one more bet. Two pair is strong enough to double barrel here.' },
          { id: 'bet100', label: 'Bet 100% pot (pot-size)', quality: 'mistake', evLoss: 1.2, coaching: 'Pot-sized turn bet with two pair is too large and folds all the hands you want calls from.' },
        ],
      },
    ],
    summary: 'On dry ace-high boards, c-bet small to set up double barrels when good turns arrive. Two pair is a premium double barrel hand.',
    tags: ['double barrel', 'two pair', 'CO', 'flop to turn', 'value'],
  },

  {
    id: 'p71',
    title: 'Float Flop, Fire Turn Bluff',
    description: 'You called a c-bet with pure air. The turn is a good card for your range — fire the bluff?',
    difficulty: 'advanced',
    category: 'Bluff',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['6h', '5h'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'flop',
        board: ['Kd', 'Tc', '2h'],
        context: 'BTN opens, BB defends. Pot 5.5BB. You check, BTN c-bets 2.5BB.',
        prompt: '65h on KT2. BTN c-bets. Do you float with gutshot + backdoor flush?',
        options: [
          { id: 'call', label: 'Call (float with backdoors)', quality: 'perfect', evLoss: 0, coaching: 'Floating with a gutshot (needs 4 or 9) plus backdoor flush draw is fine. You have enough equity and position to bet if a good turn arrives.' },
          { id: 'fold', label: 'Fold', quality: 'acceptable', evLoss: 0.6, coaching: 'Folding is safe with minimal equity, but this is a playable float with backdoors in position.' },
          { id: 'raise', label: 'Check-raise (semi-bluff)', quality: 'mistake', evLoss: 1.5, coaching: 'Check-raising with a gutshot and backdoor draws on a K-high board is too thin. Float and take the pot on good turns.' },
        ],
      },
      {
        street: 'turn',
        board: ['Kd', 'Tc', '2h', '7h'],
        context: 'You called flop. Turn 7h — you now have a flush draw to go with your missed gutshot. BTN checks.',
        prompt: 'You picked up NFD on the turn. BTN checks to you. Fire the turn bluff?',
        options: [
          { id: 'bet66', label: 'Bet 66% pot (7BB)', quality: 'perfect', evLoss: 0, coaching: 'BTN checking after c-betting flop caps their range. You now have 9 outs to the nut flush. This is a must-fire spot — semi-bluff with your draw, fold equity + equity makes this +EV.' },
          { id: 'check', label: 'Check (free river card)', quality: 'mistake', evLoss: 1.8, coaching: 'Checking gives up all fold equity and realises only your draw equity. You must apply pressure when BTN checks to you.' },
          { id: 'allin', label: 'Jam (over-pressure)', quality: 'mistake', evLoss: 2.5, coaching: 'Shoving 100BB on the turn with only a flush draw is too aggressive. Use a normal-sized bet.' },
        ],
      },
    ],
    summary: 'Float with backdoor equity. When your draw develops on the turn AND villain checks, fire the semi-bluff immediately — this is one of the highest EV situations in poker.',
    tags: ['float', 'bluff', 'NFD', 'flop to turn', 'BB'],
  },

  {
    id: 'p72',
    title: 'Overpair on Wet Flop Then Turn',
    description: 'TT on a 9h8h3c board — navigate two streets with an overpair on a draw-heavy board.',
    difficulty: 'intermediate',
    category: 'Overpair',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Td', 'Tc'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['9h', '8h', '3c'],
        context: 'BTN opens, BB defends. Pot 5.5BB. BB checks.',
        prompt: 'TT on 9h8h3c. Very wet — straight and flush draws everywhere. How do you play?',
        options: [
          { id: 'bet66', label: 'Bet 66% pot (3.65BB)', quality: 'perfect', evLoss: 0, coaching: 'TT is an overpair but highly vulnerable. Bet large to charge all draws immediately. You want to get stacks in now before bad cards fall.' },
          { id: 'bet33', label: 'Bet 33% pot (1.8BB)', quality: 'acceptable', evLoss: 0.9, coaching: 'Small bet is defensible but lets all draws peel too cheaply on this board.' },
          { id: 'check', label: 'Check back (pot control)', quality: 'mistake', evLoss: 2.5, coaching: 'Checking TT on 98h is a big mistake. Too many bad turns. Bet and protect your equity now.' },
        ],
      },
      {
        street: 'turn',
        board: ['9h', '8h', '3c', '2d'],
        context: 'You bet flop, BB calls. Turn 2d — a brick. BB checks to you. Pot ~12.8BB.',
        prompt: 'TT still an overpair on 9823. BB called flop. Turn brick. Continue?',
        options: [
          { id: 'bet66', label: 'Bet 66% pot (8.5BB)', quality: 'perfect', evLoss: 0, coaching: 'Continue on the brick turn. BB still has all their draws plus pairs. You are ahead and should barrel to charge them maximum.' },
          { id: 'check', label: 'Check back (pot control)', quality: 'acceptable', evLoss: 1.0, coaching: 'Checking is fine to control pot on the river, but you miss value from pairs and give draws cheap equity. Better to continue.' },
          { id: 'allin', label: 'Jam for value', quality: 'good', evLoss: 0.4, coaching: 'Jamming 88BB into 12.8BB is a reasonable SPR play — you often want to get it in with overpair on wet boards.' },
        ],
      },
    ],
    summary: 'With overpairs on wet boards, bet large immediately to charge draws. Continue on brick turns to extract value from pairs and give draws no free equity.',
    tags: ['overpair', 'wet board', 'BTN', 'multi-street', 'value'],
  },

  {
    id: 'p73',
    title: 'QQ OOP in 3-bet Pot — Two Streets',
    description: 'You 3-bet QQ from BB vs BTN. Navigate a J-high flop and a dangerous turn OOP.',
    difficulty: 'intermediate',
    category: '3-bet Pot',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Qd', 'Qh'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'flop',
        board: ['Jc', '6d', '2s'],
        context: 'BTN opens, you 3-bet to 10BB from BB, BTN calls. Pot 21BB. You are OOP.',
        prompt: 'QQ on J62r OOP in 3-bet pot. How do you play this flop?',
        options: [
          { id: 'bet33', label: 'Bet 33% pot (7BB)', quality: 'perfect', evLoss: 0, coaching: 'Small c-bet on a dry J-high board is the solver line. You are ahead of BTN\'s calling range (ATs-AJo, 78s, 99-TT). Extract value while keeping SPR manageable.' },
          { id: 'check', label: 'Check (protect range)', quality: 'good', evLoss: 0.4, coaching: 'Checking is also fine — QQ can be part of your checking range in 3-bet pots OOP to protect it, and you can check-raise if BTN bets.' },
          { id: 'bet75', label: 'Bet 75% pot (15.75BB)', quality: 'mistake', evLoss: 1.8, coaching: 'Large c-bet OOP on a dry board bloats the pot unnecessarily and may run into JJ+ that BTN flats pre.' },
        ],
      },
      {
        street: 'turn',
        board: ['Jc', '6d', '2s', 'Kh'],
        context: 'You bet 7BB, BTN calls. Turn Kh. Pot ~35BB. You are OOP.',
        prompt: 'QQ on J62K. King appeared. BTN called flop. How do you approach the turn OOP?',
        options: [
          { id: 'check', label: 'Check (give up lead)', quality: 'perfect', evLoss: 0, coaching: 'King is a terrible turn for QQ. BTN\'s range now includes AK, KQ, KJs. Checking is correct — QQ is now a bluff catcher. Check-call vs a normal-sized bet but fold to large bets.' },
          { id: 'bet50', label: 'Bet 50% pot (17.5BB)', quality: 'mistake', evLoss: 2.5, coaching: 'Continuing to barrel QQ when the K fell is a mistake. BTN calls flop with KJs, KQs, AK — all of which now beat you. Check and re-evaluate.' },
          { id: 'allin', label: 'Jam (commit)', quality: 'punt', evLoss: 5.0, coaching: 'Jamming QQ on K-high turn in a 3-bet pot is a terrible play. You\'re behind most of BTN\'s continuing range.' },
        ],
      },
    ],
    summary: 'In 3-bet pots OOP, c-bet dry flops small. When a scare card (K) falls, switch to check-call mode — you have been demoted to a bluff catcher.',
    tags: ['3-bet pot', 'OOP', 'QQ', 'overpair', 'scare card'],
  },

  {
    id: 'p74',
    title: 'Check-Raise Flop, Fire Turn',
    description: 'You check-raised the flop with a combo draw. Now the turn falls — continue with the bluff?',
    difficulty: 'intermediate',
    category: 'Semi-Bluff',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'CO',
    heroCards: ['8h', '7h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['9h', '6c', '2h'],
        context: 'CO opens, BB defends. Pot 5.5BB. You check, CO bets 2.5BB.',
        prompt: '87h on 9h6c2h — OESD + flush draw. CO bets. Check-raise as semi-bluff?',
        options: [
          { id: 'checkraise', label: 'Check-raise to 10BB', quality: 'perfect', evLoss: 0, coaching: 'Textbook semi-bluff check-raise with OESD + flush draw. 15 outs, fold equity vs CO, perfect spot to attack.' },
          { id: 'call', label: 'Call', quality: 'good', evLoss: 0.5, coaching: 'Calling is fine — you have a monster draw — but check-raising adds fold equity and builds a larger pot when you hit.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 8.0, coaching: 'You have 15 outs to the best hand. Never fold here.' },
        ],
      },
      {
        street: 'turn',
        board: ['9h', '6c', '2h', '3d'],
        context: 'You check-raised to 10BB, CO calls. Turn 3d — a blank. Pot ~25.5BB. BB checks.',
        prompt: 'Turn 3d is a brick. You picked up nothing. CO checks to you. Fire turn?',
        options: [
          { id: 'bet75', label: 'Bet 75% pot (19BB)', quality: 'perfect', evLoss: 0, coaching: 'You have 15 outs still (flush + OESD). After your check-raise CO\'s range is capped — they checked the turn. Continue the semi-bluff. You\'re getting the money in good.' },
          { id: 'check', label: 'Check (give up)', quality: 'mistake', evLoss: 2.5, coaching: 'Checking after a flop check-raise and missing the turn looks like a missed draw. You lose all fold equity and your draw equity. Keep betting.' },
          { id: 'allin', label: 'Jam all-in', quality: 'good', evLoss: 0.3, coaching: 'Jamming is also reasonable — you want to get it in with 15 outs and fold equity. Standard turn bet is fine but jam is also OK.' },
        ],
      },
    ],
    summary: 'When you check-raise a combo draw on the flop, follow through on the turn. The equity is too good to abandon and fold equity is still high vs a capped range.',
    tags: ['semi-bluff', 'combo draw', 'check-raise', 'multi-street', 'BB'],
  },

  {
    id: 'p75',
    title: 'OOP Check-Call Two Streets',
    description: 'You have top pair OOP and villain bets flop and turn. When do you give up vs continue?',
    difficulty: 'intermediate',
    category: 'Check-Call',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Kd', '8s'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['Kh', '5c', '2d'],
        context: 'BTN opens, BB defends. Pot 5.5BB. You check, BTN bets 2.5BB.',
        prompt: 'K8 (top pair, weak kicker) on K52r OOP. BTN bets. Options?',
        options: [
          { id: 'call', label: 'Call', quality: 'perfect', evLoss: 0, coaching: 'K8 is a clear call on this dry board. You beat all BTN\'s bluffs and value has a hard time being ahead. Check-calling the flop is the standard line OOP with TPWK.' },
          { id: 'checkraise', label: 'Check-raise', quality: 'acceptable', evLoss: 0.5, coaching: 'Check-raising is fine to protect your range but K8 is not a strong enough hand to want to bloat the pot. Call is cleaner.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 5.0, coaching: 'Folding top pair to a small c-bet is a huge mistake.' },
        ],
      },
      {
        street: 'turn',
        board: ['Kh', '5c', '2d', 'Js'],
        context: 'You called flop. Turn Js. Pot ~10.5BB. You check, BTN bets 6BB.',
        prompt: 'Turn Js. BTN continues betting 60% pot. Do you continue with K8?',
        options: [
          { id: 'call', label: 'Call (pot control)', quality: 'perfect', evLoss: 0, coaching: 'K8 is still ahead of BTN\'s bluffing range. J doesn\'t change much — BTN doesn\'t have many KJ or J hands in their BTN opening range vs BB (KJ yes, AJ yes). Call and evaluate the river.' },
          { id: 'fold', label: 'Fold (scared)', quality: 'mistake', evLoss: 2.5, coaching: 'Folding top pair to a turn bet is typically a mistake unless you have specific reads. K8 beats all BTN bluffs still.' },
          { id: 'checkraise', label: 'Check-raise (protect)', quality: 'mistake', evLoss: 1.5, coaching: 'Check-raising K8 on a K5J board with a weak kicker puts you in tough spots. Just call and keep the pot under control.' },
        ],
      },
    ],
    summary: 'With TPWK OOP, check-call two streets on relatively dry boards. You beat all bluffs and should not fold until the pot becomes too large or board becomes very scary.',
    tags: ['check-call', 'TPWK', 'OOP', 'multi-street', 'BB'],
  },

  {
    id: 'p76',
    title: 'IP Pot Control with TPTK Turn',
    description: 'You have TPTK in position. Turn makes the board dangerous — check back for pot control.',
    difficulty: 'intermediate',
    category: 'Pot Control',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['As', 'Qs'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'flop',
        board: ['Ah', '7d', '3c'],
        context: 'BTN opens, BB defends. Pot 5.5BB. BB checks.',
        prompt: 'AQ on A73r in position. BB checks. Standard c-bet?',
        options: [
          { id: 'bet33', label: 'Bet 33% pot', quality: 'perfect', evLoss: 0, coaching: 'Classic small c-bet on dry ace-high board. Works perfectly in position.' },
          { id: 'check', label: 'Check (deception)', quality: 'acceptable', evLoss: 0.5, coaching: 'Checking in position is fine for deception but misses value.' },
          { id: 'bet75', label: 'Bet 75% pot', quality: 'mistake', evLoss: 1.0, coaching: 'Too large on a dry board. Small sizing is more efficient.' },
        ],
      },
      {
        street: 'turn',
        board: ['Ah', '7d', '3c', '8h'],
        context: 'You bet flop, BB calls. Turn 8h adds a backdoor flush draw and a gutshot to the board. BB checks.',
        prompt: 'AQ on A7338h. Board got slightly wetter. BB checked. Bet or check back?',
        options: [
          { id: 'check', label: 'Check back (pot control)', quality: 'perfect', evLoss: 0, coaching: 'AQ on this slightly wet turn is worth checking back. You keep the pot small, BB cannot bluff raise you off top pair, and you can call a small river bet. TPTK is strong but not worth a large pot on this texture.' },
          { id: 'bet50', label: 'Bet 50% pot', quality: 'acceptable', evLoss: 0.6, coaching: 'Betting is fine but gives BB an opportunity to check-raise with two pair or a made hand. Checking is more controlled.' },
          { id: 'bet75', label: 'Bet 75% pot', quality: 'mistake', evLoss: 1.5, coaching: 'Large turn bet with TPTK on a slightly wet board risks being check-raised by two pair, sets, or aggressive draws. Control the pot.' },
        ],
      },
    ],
    summary: 'In position, checking back wet turns with TPTK is often correct. Keep the pot small, avoid check-raises, and maintain control going to the river.',
    tags: ['pot control', 'TPTK', 'BTN', 'turn', 'IP'],
  },

  // ── Full 3-Street Sequences ──────────────────────────────────────────────

  {
    id: 'p77',
    title: '4-bet Pot Postflop Defense',
    description: 'You called a 4-bet in position. Navigate 3 streets with AK on a low-card board.',
    difficulty: 'expert',
    category: '4-bet Pot',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'CO',
    heroCards: ['Ah', 'Kh'],
    effectiveStack: 100,
    stakes: '$5/$10',
    steps: [
      {
        street: 'flop',
        board: ['7c', '5d', '2s'],
        context: 'CO 3-bets, BTN 4-bets to 22BB, CO 5-bets jam to 100BB — wait. CO opens, BTN 3-bets, CO 4-bets, BTN calls. Pot ~45BB effective. CO c-bets 20BB (40% pot).',
        prompt: 'AK on 752r in a 4-bet pot. You have two overcards and backdoor nut flush draw. CO bets 40%. Options?',
        options: [
          { id: 'call', label: 'Call (float with overcards)', quality: 'perfect', evLoss: 0, coaching: 'In 4-bet pots AK has significant equity even on low boards. CO\'s 4-bet range includes QQ/JJ/AQ which you dominate. Float and re-evaluate — your overcards have 6 outs and board is dry.' },
          { id: 'raise', label: 'Raise (float + semi-bluff)', quality: 'good', evLoss: 0.5, coaching: 'Raising is also reasonable — polarised raise in 4-bet pot can fold CO off QQ. But call is safer to see what the turn brings.' },
          { id: 'fold', label: 'Fold', quality: 'mistake', evLoss: 4.0, coaching: 'Folding AK with 6 outs and backdoor draws in a 4-bet pot to a small c-bet is a significant mistake.' },
        ],
      },
      {
        street: 'turn',
        board: ['7c', '5d', '2s', 'Ac'],
        context: 'You called flop. Turn Ac — you made top pair top kicker. CO checks.',
        prompt: 'You hit top pair on the turn in the 4-bet pot. CO checks to you. Size?',
        options: [
          { id: 'bet70', label: 'Bet 70% pot (59BB)', quality: 'perfect', evLoss: 0, coaching: 'You hit top pair in a 4-bet pot and CO checked. Time to build the pot and commit. Bet large — you want to stack CO\'s QQ/JJ/AQ on this A-high turn.' },
          { id: 'bet33', label: 'Bet 33% pot (28BB)', quality: 'acceptable', evLoss: 1.5, coaching: 'Small bet in a 4-bet pot is too cautious. When you hit your card and CO checks, build the pot aggressively.' },
          { id: 'check', label: 'Check back (trap)', quality: 'mistake', evLoss: 3.0, coaching: 'Checking back TPTK in a 4-bet pot when CO checks to you is a serious mistake. You need to build the pot over the remaining streets.' },
        ],
      },
    ],
    summary: '4-bet pots require aggression. Float with AK on low boards and build the pot when you hit — you want to stack QQ/JJ/AQ that called the 4-bet.',
    tags: ['4-bet pot', 'AK', 'BTN', 'expert', 'multi-street'],
  },

  {
    id: 'p78',
    title: 'Triple Barrel Bluff on K-High Board',
    description: 'You have a missed draw and must decide whether to fire a third barrel as a bluff.',
    difficulty: 'expert',
    category: 'Triple Barrel',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Qh', 'Jh'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'flop',
        board: ['Kh', '9h', '3c'],
        context: 'BTN opens, BB defends. Pot 5.5BB. BB checks.',
        prompt: 'QJ hearts (flush draw + gutshot to AKQJ) on Kh9h3c. BB checks. C-bet?',
        options: [
          { id: 'bet50', label: 'Bet 50% pot (2.75BB)', quality: 'perfect', evLoss: 0, coaching: 'Standard c-bet with a flush draw and straight draw. You have 12+ outs and board favours BTN range.' },
          { id: 'check', label: 'Check', quality: 'mistake', evLoss: 1.0, coaching: 'Checking with a combo draw here is a mistake. Bet and apply pressure.' },
          { id: 'bet100', label: 'Bet 100% pot', quality: 'mistake', evLoss: 0.8, coaching: 'Too large for a standard c-bet. Medium sizing is better.' },
        ],
      },
      {
        street: 'turn',
        board: ['Kh', '9h', '3c', '2s'],
        context: 'BB called flop. Turn 2s — blank. BB checks. Pot ~11BB.',
        prompt: 'Turn is a brick. BB called flop. You still have flush draw (9 outs). Double barrel?',
        options: [
          { id: 'bet66', label: 'Bet 66% pot (7.3BB)', quality: 'perfect', evLoss: 0, coaching: 'Continue with your flush draw. 9 outs + fold equity makes this a mandatory barrel. BB called K93 flop — their range includes Kx, 9x, draws. Keep pressure.' },
          { id: 'check', label: 'Check (give up)', quality: 'mistake', evLoss: 2.0, coaching: 'Giving up with 9 flush outs against a capped range is a mistake.' },
          { id: 'allin', label: 'Jam', quality: 'acceptable', evLoss: 0.5, coaching: 'Jamming is reasonable with 9 outs to a flush in position — you might get folds from Kx hands.' },
        ],
      },
      {
        street: 'river',
        board: ['Kh', '9h', '3c', '2s', '4d'],
        context: 'BB called turn. River 4d — missed everything. BB checks. Pot ~25BB.',
        prompt: 'River missed flush draw completely. BB checks to you. Triple barrel bluff or give up?',
        options: [
          { id: 'bluff66', label: 'Triple barrel 66% pot (16.5BB)', quality: 'perfect', evLoss: 0, coaching: 'This is the hardest call for BB. You represent KX or over-pair that bet 3 streets. BB has called two streets and now checks river — they likely have medium strength (9x, Kx-weak). A pot-sized-ish river bluff folds all of them. You need only 40% fold equity.' },
          { id: 'check', label: 'Give up (check back)', quality: 'acceptable', evLoss: 0.8, coaching: 'Giving up on the river is the safe line. You have zero showdown value but a large bluff also risks a lot. Against a frequent caller, giving up is correct.' },
          { id: 'allin', label: 'Jam all-in', quality: 'mistake', evLoss: 3.0, coaching: 'Jamming 100BB into 25BB on the river is too expensive for a pure bluff. If you bluff, use a reasonable sizing.' },
        ],
      },
    ],
    summary: 'Triple barrel bluffs require all three conditions: (1) you have blockers or range advantage, (2) villain\'s range is capped by their line, (3) board tells a consistent story.',
    tags: ['triple barrel', 'bluff', 'missed draw', 'BTN', 'expert'],
  },

  {
    id: 'p79',
    title: 'AK Multiway — All Three Streets',
    description: 'You have top pair in a 3-way pot. Navigate value extraction vs loss mitigation over 3 streets.',
    difficulty: 'intermediate',
    category: 'Multiway',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BB+SB',
    heroCards: ['Ah', 'Kd'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['As', '7c', '3d'],
        context: 'CO opens, SB and BB both call. Pot 7.5BB. SB checks, BB checks.',
        prompt: 'AK on A73r multiway. Both players check. C-bet into 2 players?',
        options: [
          { id: 'bet50', label: 'Bet 50% pot (3.75BB)', quality: 'perfect', evLoss: 0, coaching: 'Standard c-bet multiway with TPTK on a dry board. Charge any 7x, 3x, and pocket pairs. Don\'t give free cards.' },
          { id: 'check', label: 'Check (deception)', quality: 'acceptable', evLoss: 0.6, coaching: 'Checking is fine for deception multiway but with TPTK you should usually bet to protect.' },
          { id: 'bet75', label: 'Bet 75% pot', quality: 'mistake', evLoss: 1.2, coaching: 'Large bets multiway get called only by monsters. Use medium sizing.' },
        ],
      },
      {
        street: 'turn',
        board: ['As', '7c', '3d', '9h'],
        context: 'You bet flop, BB called, SB folded. Turn 9h. BB checks. Now heads-up.',
        prompt: 'Heads-up now, AK on A7399h. BB calls flop, checks turn. Double barrel?',
        options: [
          { id: 'bet50', label: 'Bet 50% pot (7BB)', quality: 'perfect', evLoss: 0, coaching: 'Continue with TPTK heads-up. Turn 9h is mostly neutral. BB likely has Ax or pair hands. Extract value.' },
          { id: 'check', label: 'Check (pot control)', quality: 'acceptable', evLoss: 0.7, coaching: 'Checking for pot control is fine, especially with a weaker second pair range calling. But bet for value.' },
          { id: 'bet75', label: 'Bet 75% pot (10.5BB)', quality: 'good', evLoss: 0.2, coaching: 'Larger sizing is also fine to build value with TPTK.' },
        ],
      },
      {
        street: 'river',
        board: ['As', '7c', '3d', '9h', '2c'],
        context: 'You bet turn, BB calls. River 2c — blank. BB checks. Pot ~28BB.',
        prompt: 'River 2c. No draws completed. AK on A73922. BB checks. River value bet?',
        options: [
          { id: 'betsmall', label: 'Bet 30% pot (8.4BB)', quality: 'perfect', evLoss: 0, coaching: 'Small river value bet captures chips from BB\'s weak Ax and pair hands. You beat all of their range except A7, A3, A9, 79, 97 (unlikely). Thin value with small sizing.' },
          { id: 'bet75', label: 'Bet 75% pot (21BB)', quality: 'mistake', evLoss: 1.5, coaching: 'Large river bet gets called only by hands that beat TPTK or have good equity. Small bet for thin value is correct.' },
          { id: 'check', label: 'Check back', quality: 'acceptable', evLoss: 0.7, coaching: 'Checking is safe but you leave thin value on the table. A small bet captures extra chips.' },
        ],
      },
    ],
    summary: 'In multiway pots, bet medium-sized for value. When you end up heads-up, continue barrelling and finish with small river value bets vs capped ranges.',
    tags: ['multiway', 'AK', 'multi-street', 'thin value', 'CO'],
  },

  {
    id: 'p80',
    title: 'Set on Flush-Completing Board',
    description: 'You flopped a set but a flush completes on the river. Extract max value or exercise caution?',
    difficulty: 'intermediate',
    category: 'Set',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['5c', '5d'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['5h', 'Jh', '3c'],
        context: 'BTN opens, BB defends. Pot 5.5BB. BB checks.',
        prompt: '55 bottom set on 5hJh3c (flush draw present). BB checks. Sizing?',
        options: [
          { id: 'bet75', label: 'Bet 75% pot (4.1BB)', quality: 'perfect', evLoss: 0, coaching: 'Large bet with bottom set on a board with a flush draw. Charge Jhx and flush draws maximum. Build the pot now while ahead.' },
          { id: 'bet33', label: 'Bet 33% pot', quality: 'acceptable', evLoss: 1.0, coaching: 'Small bet lets all flush draws in cheaply. With a set you want to build a pot now.' },
          { id: 'check', label: 'Check (slowplay)', quality: 'mistake', evLoss: 2.5, coaching: 'Slowplaying bottom set on a flush draw board is a big mistake.' },
        ],
      },
      {
        street: 'turn',
        board: ['5h', 'Jh', '3c', '2d'],
        context: 'BB called flop. Turn 2d — no flush, blank. BB checks. Pot ~13.7BB.',
        prompt: 'Turn blank. BB calls flop. Your set is still best. Continue?',
        options: [
          { id: 'bet75', label: 'Bet 75% pot (10.3BB)', quality: 'perfect', evLoss: 0, coaching: 'Continue to build the pot. BB is still on a flush draw or medium pair. Charge them again.' },
          { id: 'bet33', label: 'Bet 33% pot (4.5BB)', quality: 'acceptable', evLoss: 1.0, coaching: 'Smaller bet keeps pot reasonable but underbets your set. Charge draws and pairs properly.' },
          { id: 'check', label: 'Check', quality: 'mistake', evLoss: 2.0, coaching: 'Checking again lets flush draws in free. Protect your hand and build the pot.' },
        ],
      },
      {
        street: 'river',
        board: ['5h', 'Jh', '3c', '2d', 'Kh'],
        context: 'BB calls turn. River Kh completes the flush. BB bets 100% pot (all-in essentially, 50BB jam).',
        prompt: 'River Kh completes the flush. BB jams. Do you call the river with your full house (555JJ)?',
        options: [
          { id: 'call', label: 'Call (set → full house)', quality: 'perfect', evLoss: 0, coaching: 'The river GAVE you a full house (55 + Jh on board = 555JJ). You beat all flushes! BB is jamming a flush — and you crush it. Easy call.' },
          { id: 'fold', label: 'Fold (scared of flush)', quality: 'punt', evLoss: 50.0, coaching: 'This is one of the most common novice mistakes — forgetting that a set with a paired board card makes a full house. You beat the flush. Call.' },
        ],
      },
    ],
    summary: 'Always track how board pairs affect your set. When a board card pairs on the river, your set becomes a full house — you beat all flush hands on that board.',
    tags: ['set', 'full house', 'flush', 'multi-street', 'BTN'],
  },

  {
    id: 'p81',
    title: 'Two Pair vs Dangerous Runout',
    description: 'You flopped two pair, but the board is getting worse each street. When do you give up?',
    difficulty: 'intermediate',
    category: 'Two Pair',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'CO',
    heroCards: ['Jd', '7h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['Jh', '7c', '5s'],
        context: 'CO opens, BB defends. Pot 5.5BB. You check, CO bets 2.5BB.',
        prompt: 'J7 (top two pair) on J75r. CO c-bets. How do you play?',
        options: [
          { id: 'checkraise', label: 'Check-raise to 10BB', quality: 'perfect', evLoss: 0, coaching: 'Top two pair on a connected board is a check-raise. J75 has many draws and two pair needs protection. Check-raise and build the pot while ahead.' },
          { id: 'call', label: 'Call', quality: 'acceptable', evLoss: 0.7, coaching: 'Calling is fine but doesn\'t build pot fast enough with top two pair on a draw-heavy board.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 10.0, coaching: 'Never fold top two pair.' },
        ],
      },
      {
        street: 'turn',
        board: ['Jh', '7c', '5s', '8d'],
        context: 'CO called check-raise. Turn 8d — makes many straights (6 completes straight, 9 makes straight). CO bets 15BB into 25.5BB pot.',
        prompt: 'Turn 8d makes 569 and 67 straights. CO fires 60% pot. Defend or give up?',
        options: [
          { id: 'call', label: 'Call (hope for the board to pair)', quality: 'acceptable', evLoss: 1.2, coaching: 'Calling with two pair when a straight is likely out there is marginal. The pot is large — you might call once and fold river.' },
          { id: 'raise', label: 'Jam all-in (protect)', quality: 'mistake', evLoss: 4.0, coaching: 'Jamming into a likely straight with only two pair and no redraws is a mistake.' },
          { id: 'fold', label: 'Fold (respect the bet)', quality: 'perfect', evLoss: 0, coaching: 'CO bet-called a check-raise on J75, then fires turn when 8 falls. This strongly represents 6x or 9x straight. With two pair and no redraws, folding is defensible here.' },
        ],
      },
    ],
    summary: 'Two pair is a strong hand but when the board runout completes obvious straight draws and villain continues betting, respect the aggression and consider folding.',
    tags: ['two pair', 'danger board', 'multi-street', 'check-raise', 'fold'],
  },

  {
    id: 'p82',
    title: 'JT — Straight Draw Navigation',
    description: 'You flop an OESD with JT. Make the right decisions across 3 streets to realise your equity.',
    difficulty: 'advanced',
    category: 'Semi-Bluff',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Jd', 'Tc'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'flop',
        board: ['Qh', '9s', '3d'],
        context: 'BTN opens, BB defends. Pot 5.5BB. BB checks.',
        prompt: 'JT on Q93 — OESD (8 or K makes straight). BB checks. C-bet strategy?',
        options: [
          { id: 'bet50', label: 'Bet 50% pot (2.75BB)', quality: 'perfect', evLoss: 0, coaching: 'C-bet with your OESD. You have 8 outs, board favours BTN range, and you apply pressure. Medium sizing is right.' },
          { id: 'check', label: 'Check (free card)', quality: 'acceptable', evLoss: 0.6, coaching: 'Checking is fine — you want a free card. But c-betting with equity is generally better.' },
          { id: 'bet100', label: 'Bet pot-size', quality: 'mistake', evLoss: 1.0, coaching: 'Overbetting with a draw is inefficient. Use medium sizing.' },
        ],
      },
      {
        street: 'turn',
        board: ['Qh', '9s', '3d', '7c'],
        context: 'BB calls flop. Turn 7c — blank. BB checks again.',
        prompt: 'Turn 7c — still have OESD. BB checks to you. Double barrel or check?',
        options: [
          { id: 'bet75', label: 'Bet 75% pot (7.5BB)', quality: 'perfect', evLoss: 0, coaching: 'Continue with OESD. You have 8 outs and fold equity. Large turn barrel with draws extracts max fold equity before the river.' },
          { id: 'check', label: 'Check (free river card)', quality: 'acceptable', evLoss: 0.8, coaching: 'Checking is fine to get a free card on a missed turn. But barreling exploits fold equity better.' },
          { id: 'allin', label: 'Jam', quality: 'good', evLoss: 0.3, coaching: 'Jamming is reasonable with good stack-to-pot ratio and a clear draw.' },
        ],
      },
      {
        street: 'river',
        board: ['Qh', '9s', '3d', '7c', 'Ks'],
        context: 'BB calls turn. River Ks — you hit the straight! BB checks.',
        prompt: 'You rivered the straight (J-K). BB checks. Sizing for value?',
        options: [
          { id: 'bet100', label: 'Bet 100% pot (22BB)', quality: 'perfect', evLoss: 0, coaching: 'You rivered the nuts. Villain called two streets of pressure and now you have the best hand. Bet large to extract maximum value from two pair, sets, and weaker straights.' },
          { id: 'bet50', label: 'Bet 50% pot (11BB)', quality: 'acceptable', evLoss: 1.5, coaching: 'Smaller bet is fine but with the nuts and a villain who called two streets, bet large and get paid.' },
          { id: 'check', label: 'Check (trap)', quality: 'mistake', evLoss: 3.0, coaching: 'Slowplaying the nuts on the river after betting two streets is a mistake. Villain is unlikely to bluff — just bet for value.' },
        ],
      },
    ],
    summary: 'With straight draws, apply pressure across flop and turn with semi-bluffs. When you complete the straight on the river, bet large for full value.',
    tags: ['OESD', 'straight', 'semi-bluff', 'BTN', 'multi-street'],
  },

  {
    id: 'p83',
    title: 'Deep Stack Set vs Draw (200BB)',
    description: 'At 200BB deep, you have a set vs an obvious combo draw. How do you play it?',
    difficulty: 'advanced',
    category: 'Deep Stack',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BB',
    heroCards: ['6c', '6d'],
    effectiveStack: 200,
    stakes: '$2/$5',
    steps: [
      {
        street: 'flop',
        board: ['6h', '5h', '4c'],
        context: 'CO opens, BB defends. Pot 5.5BB. You have bottom set on 654 with a flush draw possible. BB checks.',
        prompt: '66 bottom set on 654h (flush draw present). BB checks. 200BB deep — how do you play?',
        options: [
          { id: 'bet75', label: 'Bet 75% pot (4.1BB)', quality: 'perfect', evLoss: 0, coaching: 'Even at 200BB deep, bet large with set on a wet board. You need to build the pot now. If BB has a combo draw (8x flush + 3x or 7x straight), getting stacks in is correct on this board.' },
          { id: 'bet33', label: 'Bet 33% pot (1.8BB)', quality: 'acceptable', evLoss: 1.2, coaching: 'Small bet is too slow for this board. You want to build a large pot now while you have the best hand.' },
          { id: 'check', label: 'Check (induce)', quality: 'mistake', evLoss: 2.5, coaching: 'Checking is dangerous on 654h even with a set. Too many bad cards on turn (3, 7, 8 make straights; any heart makes flush). Build pot now.' },
        ],
      },
      {
        street: 'turn',
        board: ['6h', '5h', '4c', '2d'],
        context: 'BB called. Turn 2d. BB checks-raises (you bet, BB check-raised to 3x).',
        prompt: 'BB check-raises the turn 2d. Your set is now 666+54. Respond?',
        options: [
          { id: 'jam', label: '4-bet jam (commit)', quality: 'perfect', evLoss: 0, coaching: 'At 200BB deep you might normally consider folding to a turn check-raise. But BB\'s range here includes many combo draws (87hh, 78hh, 3hXh). Your set plus straight redraw to 6666 means you have dominant equity even vs a straight. Jam and get it in.' },
          { id: 'call', label: 'Call (control pot)', quality: 'good', evLoss: 0.8, coaching: 'Calling and seeing the river is fine — you have a set and many redraws. But at this SPR, jamming or calling are both reasonable.' },
          { id: 'fold', label: 'Fold (deep stack respect)', quality: 'mistake', evLoss: 8.0, coaching: 'Folding a set to a turn check-raise even at 200BB deep is a mistake. You have a set with redraws on a draw-heavy board.' },
        ],
      },
    ],
    summary: 'Deep stack sets on connected boards should still bet for value immediately — build the pot, then commit when appropriate. Sets with redraws play well even vs straights.',
    tags: ['deep stack', 'set', 'wet board', 'CO', 'advanced'],
  },

  {
    id: 'p84',
    title: 'Semi-Bluff Check-Raise OESD+FD',
    description: 'You have an open-ended straight draw AND a flush draw — the maximum semi-bluff hand.',
    difficulty: 'intermediate',
    category: 'Semi-Bluff',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['8h', '7h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'flop',
        board: ['9h', '6d', '2h'],
        context: 'BTN opens, BB defends. Pot 5.5BB. You check, BTN bets 2.5BB.',
        prompt: '87h on 9h6d2h — OESD (5 or T) plus flush draw (9 hearts). BTN bets. Options?',
        options: [
          { id: 'checkraise', label: 'Check-raise to 10BB', quality: 'perfect', evLoss: 0, coaching: 'With 15 outs to a straight or flush, this is the strongest possible semi-bluff hand. Check-raise to force fold or get max equity in the pot. Even if called, you are likely a coin-flip or better.' },
          { id: 'call', label: 'Call and see turn', quality: 'good', evLoss: 0.5, coaching: 'Calling is fine — 15 outs is a monster draw. But check-raising maximises fold equity and pot size.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 9.0, coaching: 'Folding 15 outs is a catastrophic mistake. You are nearly a coin-flip vs a set!' },
        ],
      },
    ],
    summary: 'OESD plus flush draw (15 outs) is the best semi-bluff hand in poker. Always check-raise or bet aggressively — you are a coin-flip vs most made hands.',
    tags: ['semi-bluff', 'combo draw', 'OESD', 'flush draw', 'check-raise'],
  },

  {
    id: 'p85',
    title: 'River Overbet with the Nuts',
    description: 'You hold the absolute nuts on the river in position. Size up to extract maximum value.',
    difficulty: 'advanced',
    category: 'Overbet',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Td', '9d'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'river',
        board: ['Jd', '8h', '7s', '2c', '6d'],
        context: 'BTN opens, BB defends. Flop/turn checked through. River 6d. BB leads out 50% pot.',
        prompt: 'T9 made the nuts (J-T-9-8-7 straight). BB donks river 50%. How do you respond?',
        options: [
          { id: 'raise150', label: 'Raise to 3x (overbet)', quality: 'perfect', evLoss: 0, coaching: 'You have the absolute nuts. BB is donking — likely a value bet with a straight or two pair. Raise large to extract maximum chips. They cannot fold a strong hand here and you cannot be beaten.' },
          { id: 'call', label: 'Call (safe)', quality: 'mistake', evLoss: 5.0, coaching: 'Calling the nuts on the river is a major mistake. You leave a lot of money on the table. If villain has value, they will call your raise. If they\'re bluffing, you lose nothing by raising.' },
          { id: 'minraise', label: 'Min-raise', quality: 'acceptable', evLoss: 2.0, coaching: 'Min-raise captures some extra value but undersizes significantly. With the absolute nuts on the river, go bigger.' },
        ],
      },
    ],
    summary: 'With the nuts on the river, always raise or overbet. Never slow-call the nuts when you can extract more chips — this is the biggest missed value spot in poker.',
    tags: ['overbet', 'nuts', 'river', 'value', 'BTN'],
  },
]
