import type { Puzzle } from '../puzzle-types'

export const PUZZLES_PREFLOP: Puzzle[] = [

  // ── p11 ──────────────────────────────────────────────────────────────────
  {
    id: 'p11-aqo-vs-3bet',
    title: 'BTN Opens, Faces BB 3-Bet — AQo',
    description: 'You open BTN with AQo and the BB 3-bets. Do you 4-bet, call in position, or fold?',
    difficulty: 'intermediate',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Ah', 'Qd'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to BTN. You open to $5. BB 3-bets to $17.',
        prompt: 'Facing a BB 3-bet with AQo in position. 4-bet, call, or fold?',
        options: [
          { id: 'call',  label: 'Call $12',      quality: 'perfect',    evLoss: 0,   coaching: 'AQo IP is a clear call against a BB 3-bet. You have strong equity, position, and realisation. 4-betting turns it into a marginal bluff — your 4-bet range should be AK, KK, AA for value and A3s-A5s as bluffs. Call and exploit your position postflop.' },
          { id: '4bet',  label: '4-bet to $42',  quality: 'acceptable', evLoss: 2,   coaching: '4-betting AQo is defensible at low frequency, but your 4-bet bluffs are better as A2s-A5s (great blockers, can fold if shoved). AQo is too good to be a pure bluff and not quite strong enough to stack off vs all 3-bet ranges. Calling IP is marginally superior.' },
          { id: 'fold',  label: 'Fold',          quality: 'punt',       evLoss: 8,   coaching: 'Never fold AQo in position facing a BB 3-bet. You have top-5% equity in your hand, position, and a wide calling range. This fold is a significant mistake.' },
        ],
      },
    ],
    summary: 'AQo in position facing a 3-bet is a standard call. It has too much equity to fold and isn\'t quite strong enough to stack off against strong 3-bet ranges. Save 4-bets for AK+ and suited aces with proper blocker value like A2s-A5s.',
    tags: ['preflop', 'BTN', 'vs 3-bet', 'AQo', 'IP', '4-bet'],
  },

  // ── p12 ──────────────────────────────────────────────────────────────────
  {
    id: 'p12-t9s-bb-defend',
    title: 'BB vs CO Open — T9s Defense',
    description: 'The CO opens to 2.5BB. Should you defend T9s from the big blind, 3-bet, or fold?',
    difficulty: 'beginner',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'CO',
    heroCards: ['Tc', '9c'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens to $5. Folds to BB (hero).',
        prompt: 'Facing a CO open with T9s from the BB. Call, 3-bet, or fold?',
        options: [
          { id: 'call',  label: 'Call $3',       quality: 'perfect',    evLoss: 0,   coaching: 'T9s is a standard BB defend vs a CO open. You\'re getting 2.5:1 pot odds with a hand that has excellent playability — two-pair outs, straight draws, flush draws. At 100BB deep, T9s has good implied odds and plays well in multi-street pots.' },
          { id: '3bet',  label: '3-bet to $15',  quality: 'good',       evLoss: 0.5, coaching: '3-betting T9s from the BB is a viable strategy at some frequencies. However, CO\'s range is tighter than BTN/SB, so your bluff faces a stronger calling range. Calling is marginally higher EV but 3-betting is not wrong.' },
          { id: 'fold',  label: 'Fold',          quality: 'mistake',    evLoss: 3,   coaching: 'Folding T9s in the BB vs a CO open is too tight. At 2.5:1 pot odds with good implied odds and connectivity, this is a clear defend. CO opens wider than UTG so your hand plays well here.' },
        ],
      },
    ],
    summary: 'T9s in the BB vs a CO open is a clear call. Suited connectors have excellent implied odds and playability in single-raised pots. When you\'re getting 2.5:1, most hands with good equity and potential should defend.',
    tags: ['preflop', 'BB defense', 'suited connectors', 'T9s', 'CO'],
  },

  // ── p13 ──────────────────────────────────────────────────────────────────
  {
    id: 'p13-kqo-utg-rfi',
    title: 'UTG Opening Range — KQo Decision',
    description: 'Should you open KQo from UTG in a 6-max game? Understand positional opening ranges.',
    difficulty: 'beginner',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'UTG',
    villainPosition: 'BB',
    heroCards: ['Kh', 'Qd'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'You are UTG in a 6-max game with KQo.',
        prompt: 'First to act preflop with KQo UTG 6-max. Open, limp, or fold?',
        options: [
          { id: 'open',  label: 'Open to $3',    quality: 'perfect',    evLoss: 0,   coaching: 'KQo is a standard open from UTG in 6-max. In 6-max you only have 5 opponents (vs 8 in full ring), so the UTG range is wider. KQo dominates much of the BB and SB calling ranges and plays well postflop. Open standard.' },
          { id: 'limp',  label: 'Limp $1',       quality: 'punt',       evLoss: 4,   coaching: 'Never limp from UTG with KQo. Limping gives away information, allows players to over-limp or raise cheaply, and creates poor pot structures. Always open-raise or fold from EP.' },
          { id: 'fold',  label: 'Fold',          quality: 'mistake',    evLoss: 2.5, coaching: 'Folding KQo from UTG in 6-max is too tight. KQo is in the top 8% of hands and is a profitable open in 6-max. It would be a fold from UTG in full ring, but not in 6-max.' },
        ],
      },
    ],
    summary: '6-max UTG ranges are significantly wider than full ring UTG. KQo is a standard open in 6-max — it dominates a large portion of BB calling ranges and plays well in position against single opponents. Never limp from UTG — always open or fold.',
    tags: ['preflop', 'UTG', 'RFI', 'KQo', '6-max', 'opening range'],
  },

  // ── p14 ──────────────────────────────────────────────────────────────────
  {
    id: 'p14-bvb-k7o',
    title: 'Blind vs Blind — K7o from SB',
    description: 'Folds to the SB. Should you raise, complete, or fold K7o in a heads-up blind war?',
    difficulty: 'beginner',
    category: 'BvB',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'SB',
    villainPosition: 'BB',
    heroCards: ['Kh', '7o'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to SB (hero). One opponent remaining: the BB.',
        prompt: 'Heads-up in the blinds with K7o. Raise, complete, or fold?',
        options: [
          { id: 'raise',    label: 'Raise to $3',   quality: 'perfect',    evLoss: 0,   coaching: 'Raising is correct with K7o from the SB in a blind war. Against only the BB, you have position postflop, high fold equity, and K7o has decent equity vs BB\'s wide defend range. Open to 2.5-3BB.' },
          { id: 'complete', label: 'Complete $1',    quality: 'acceptable', evLoss: 1.5, coaching: 'Completing with K7o is defensible but weaker. You give BB the option to check or raise, you play OOP, and you don\'t build the pot with your positional advantage. Raising is higher EV.' },
          { id: 'fold',     label: 'Fold',          quality: 'mistake',    evLoss: 2,   coaching: 'Folding K7o to the BB in a BvB spot is too tight. You\'re only facing one player, you have position, and K7o has reasonable equity. In BvB, you should be raising very wide — K7o comfortably meets that threshold.' },
        ],
      },
    ],
    summary: 'In blind vs blind situations, the SB should raise a wide range (70-80%+ of hands) since you have position over the BB postflop. K7o is comfortably within a raising range. Completing is too passive — you surrender the initiative and play OOP.',
    tags: ['preflop', 'BvB', 'SB', 'K7o', 'blind war'],
  },

  // ── p15 ──────────────────────────────────────────────────────────────────
  {
    id: 'p15-99-sb-squeeze',
    title: 'SB Squeeze with Pocket Nines',
    description: 'CO opens, BTN cold-calls. Should you squeeze from the SB with 99, call, or fold?',
    difficulty: 'intermediate',
    category: 'Squeeze',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'SB',
    villainPosition: 'CO',
    heroCards: ['9c', '9d'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens to $5. BTN cold-calls. Action on SB with 99.',
        prompt: 'CO opens, BTN cold-calls. You are in the SB with 99. Squeeze, call, or fold?',
        options: [
          { id: 'squeeze', label: '3-bet to $22',  quality: 'perfect',    evLoss: 0,   coaching: '99 is an excellent squeeze hand. You isolate vs CO\'s wide range, deny BTN\'s equity for free, and often get heads-up with 99 as an overpair advantage. When you squeeze and they fold, you win a 6.5BB pot without a flop — great EV.' },
          { id: 'call',    label: 'Call $4',        quality: 'acceptable', evLoss: 2,   coaching: 'Calling is valid but suboptimal. You play a multiway pot OOP with 99 — you\'ll often flop an underpair and face multiple opponents. Squeezing is more profitable as it wins the blinds outright frequently.' },
          { id: 'fold',    label: 'Fold',           quality: 'mistake',    evLoss: 4.5, coaching: 'Folding 99 in the SB with a squeeze opportunity is far too tight. You have a strong pair, fold equity, and excellent position to squeeze. This fold is a significant leak.' },
        ],
      },
    ],
    summary: 'Pocket nines from the SB in a squeeze spot (open + cold-call) is a high-frequency squeeze. You have good equity, strong fold equity against both players, and avoid playing OOP in a multiway pot. Squeezing here is clearly superior to calling or folding.',
    tags: ['preflop', 'SB', 'squeeze', '99', '3-bet'],
  },

  // ── p16 ──────────────────────────────────────────────────────────────────
  {
    id: 'p16-a5s-cold-4bet',
    title: 'Cold 4-Bet Bluff — A5s on BTN',
    description: 'UTG opens, CO 3-bets. You are on the BTN with A5s. Should you cold 4-bet as a bluff?',
    difficulty: 'advanced',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'CO',
    heroCards: ['As', '5s'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'UTG opens to $15. CO 3-bets to $45. Folds to BTN (hero) with As5s.',
        prompt: 'UTG opens, CO 3-bets, and action is on BTN with A5s. 4-bet, call, or fold?',
        options: [
          { id: '4bet',  label: '4-bet to $120',  quality: 'perfect',    evLoss: 0,   coaching: 'A5s is the ideal cold 4-bet bluff hand. The Ace blocks AA and AK (the strongest 3-bet value hands), and the suited wheel cards have good equity when called. You also have position. 4-bet to ~2.5x the 3-bet and fold vs a 5-bet.' },
          { id: 'fold',  label: 'Fold',           quality: 'good',       evLoss: 0.5, coaching: 'Folding is fine. Cold 4-betting is an advanced move that requires precise execution. If you\'re unsure about your 4-bet/5-bet dynamics and postflop plan, folding A5s here is a reasonable default.' },
          { id: 'call',  label: 'Call $45',       quality: 'mistake',    evLoss: 3,   coaching: 'Cold-calling a 3-bet OOP on the BTN with A5s creates terrible pot geometry. You\'re forced to play postflop OOP with weak connectivity. Either 4-bet or fold — calling is the worst option here.' },
        ],
      },
    ],
    summary: 'A2s-A5s are the premium 4-bet bluff hands because they block AA and AK while having great equity when called (flush draws, nut flush potential). Always choose 4-bet or fold when cold-calling a 3-bet would leave you OOP — never cold-call a 3-bet on the BTN with a weak hand.',
    tags: ['preflop', '4-bet', 'A5s', 'bluff', 'BTN', 'blocker'],
  },

  // ── p17 ──────────────────────────────────────────────────────────────────
  {
    id: 'p17-qq-sb-3bet',
    title: 'SB vs BTN Open — Pocket Queens',
    description: 'BTN opens and the SB has QQ. Should you 3-bet for value, call, or fold?',
    difficulty: 'intermediate',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'SB',
    villainPosition: 'BTN',
    heroCards: ['Qh', 'Qd'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'BTN opens to $5. SB (hero) is next to act with QhQd.',
        prompt: 'BTN opens, you have QQ in the SB. 3-bet, call, or fold?',
        options: [
          { id: '3bet',  label: '3-bet to $16',  quality: 'perfect',    evLoss: 0,   coaching: 'QQ is a clear value 3-bet from the SB. BTN opens wide and calling would allow BB to squeeze in and play multiway with a pair that wants to be heads-up. 3-betting gets value and denies BB\'s equity, setting up a favorable HU pot even if OOP.' },
          { id: 'call',  label: 'Call $4',        quality: 'mistake',    evLoss: 3.5, coaching: 'Calling QQ from the SB is a significant mistake. You allow BB to over-call for cheap, play a multiway pot OOP, and don\'t extract value with one of the strongest starting hands. 3-bet always.' },
          { id: 'fold',  label: 'Fold',          quality: 'punt',       evLoss: 10,  coaching: 'Never fold QQ preflop. This is one of the strongest starting hands in poker. Folding is a massive punt.' },
        ],
      },
    ],
    summary: 'Strong pairs (QQ+) and AK should almost always be 3-bet from the SB vs a BTN open. Calling allows more players to enter the pot cheaply, and you miss value. QQ plays best in a heads-up pot — 3-bet and isolate.',
    tags: ['preflop', 'SB', '3-bet', 'QQ', 'value', 'BvB'],
  },

  // ── p18 ──────────────────────────────────────────────────────────────────
  {
    id: 'p18-jts-btn-cold-call',
    title: 'BTN Cold Call — JTs vs CO Open',
    description: 'CO opens. Should you cold-call JTs from BTN, 3-bet, or fold?',
    difficulty: 'beginner',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'CO',
    heroCards: ['Jh', 'Th'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens to $5. Folds to BTN (hero) with JhTh.',
        prompt: 'CO opens. You have JTs on the BTN. Call, 3-bet, or fold?',
        options: [
          { id: 'call',  label: 'Call $5',        quality: 'perfect',    evLoss: 0,   coaching: 'JTs is a standard BTN cold call. You have position, excellent implied odds, and a hand that plays well on many board textures (straights, flushes, TPTK). Calling vs a CO open is the standard and correct play.' },
          { id: '3bet',  label: '3-bet to $15',   quality: 'good',       evLoss: 0.5, coaching: '3-betting JTs from the BTN is also a good option at some frequencies — it creates fold equity and position. However, calling preserves the hand\'s implied odds and is the standard play.' },
          { id: 'fold',  label: 'Fold',           quality: 'mistake',    evLoss: 3,   coaching: 'Folding JTs in position vs a CO open is too tight. JTs is in the top 10% of starting hands with great connectivity, flush potential, and strong implied odds. Never fold this in position.' },
        ],
      },
    ],
    summary: 'JTs is one of the best cold-calling hands from the BTN. It has excellent playability on most board textures, great implied odds at 100BB, and connects with straights, flushes, and top-pair combinations. Both calling and light 3-betting are valid strategies.',
    tags: ['preflop', 'BTN', 'cold call', 'JTs', 'suited connectors'],
  },

  // ── p19 ──────────────────────────────────────────────────────────────────
  {
    id: 'p19-64s-bb-defense',
    title: 'BB Defense — 64s vs BTN Open',
    description: 'BTN opens. Do you defend from the BB with 64s or fold the borderline suited connector?',
    difficulty: 'beginner',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['6h', '4h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'BTN opens to $5. SB folds. BB (hero) has 6h4h.',
        prompt: 'BTN opens, SB folds. Do you defend 64s from the BB or fold?',
        options: [
          { id: 'call',  label: 'Call $3',        quality: 'perfect',    evLoss: 0,   coaching: 'Calling 64s in the BB vs a BTN open is correct. You\'re getting 2.5:1 pot odds vs BTN\'s very wide opening range. Suited connectors have good implied odds — if you hit a straight or flush, you can win a big pot. The price is right to defend.' },
          { id: 'fold',  label: 'Fold',           quality: 'acceptable', evLoss: 1.5, coaching: 'Folding 64s is a conservative but not terrible play. This is a borderline hand — slightly below the threshold vs a tighter CO/UTG open, but clearly a defend vs BTN\'s wide range. You\'re giving up some EV but the mistake isn\'t massive.' },
          { id: '3bet',  label: '3-bet to $14',   quality: 'mistake',    evLoss: 2.5, coaching: '3-betting 64s from the BB is too loose. This hand lacks blockers and connectivity needed for a profitable 3-bet bluff. Call or fold, not raise.' },
        ],
      },
    ],
    summary: 'In the BB vs BTN opens, you should defend a wide range because of the pot odds you\'re receiving. 64s is a marginal but profitable defend — suited connectors have implied odds that justify calling at 2.5:1. The BB is the only position where you can call that wide.',
    tags: ['preflop', 'BB defense', '64s', 'BTN', 'pot odds', 'suited connectors'],
  },

  // ── p20 ──────────────────────────────────────────────────────────────────
  {
    id: 'p20-ajs-bb-3bet',
    title: 'BB 3-Bet with AJs vs BTN Open',
    description: 'BTN opens and you have AJs in the BB. Should you 3-bet for value, call, or fold?',
    difficulty: 'intermediate',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Ah', 'Jh'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'BTN opens to $5. SB folds. BB (hero) with AhJh.',
        prompt: 'BTN opens, SB folds. You have AJs in the BB. 3-bet, call, or fold?',
        options: [
          { id: '3bet',  label: '3-bet to $16',  quality: 'perfect',    evLoss: 0,   coaching: 'AJs is a value 3-bet from the BB vs a BTN open. BTN opens very wide (~45-50% of hands), making your AJs dominate a huge portion of their range. You generate fold equity vs weak BTN hands and set up favorable flops with a strong suited hand.' },
          { id: 'call',  label: 'Call $3',        quality: 'good',       evLoss: 0.5, coaching: 'Calling AJs is fine — you preserve implied odds and avoid giving BTN information. Both are valid strategies; 3-betting is marginally higher EV against wide BTN ranges.' },
          { id: 'fold',  label: 'Fold',           quality: 'punt',       evLoss: 7,   coaching: 'Never fold AJs from the BB vs a BTN open. This is a top-15% hand with excellent postflop playability. Folding here is a major error.' },
        ],
      },
    ],
    summary: 'AJs in the BB is a strong 3-bet candidate vs BTN opens. BTN opens wide (~45%), so your AJs dominates much of their range. 3-betting generates fold equity and sets up aggressive postflop play. Both 3-betting and calling are correct — folding is never an option.',
    tags: ['preflop', 'BB', '3-bet', 'AJs', 'vs BTN', 'value'],
  },

  // ── p21 ──────────────────────────────────────────────────────────────────
  {
    id: 'p21-a2s-co-3bet-bluff',
    title: 'Light 3-Bet Bluff — A2s from CO vs UTG',
    description: 'UTG opens. You are in CO with A2s. Should you 3-bet as a bluff, call, or fold?',
    difficulty: 'intermediate',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'UTG',
    heroCards: ['As', '2s'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'UTG opens to $5. Folds to CO (hero) with As2s.',
        prompt: 'UTG opens. You have A2s in CO. 3-bet bluff, call, or fold?',
        options: [
          { id: '3bet',  label: '3-bet to $16',  quality: 'perfect',    evLoss: 0,   coaching: 'A2s is an ideal 3-bet bluff vs UTG. The Ace blocks AA and AK (UTG\'s strongest holdings), the suited nut flush draw has equity when called, and you\'re in position postflop. You balance your 3-bet range by mixing in A2s-A5s as bluffs alongside your value hands.' },
          { id: 'fold',  label: 'Fold',          quality: 'good',       evLoss: 0.5, coaching: 'Folding A2s vs UTG is fine. UTG has a tight range, so 3-betting is slightly riskier — you\'ll face stronger hands when called. Folding is a conservative but acceptable play vs the tightest position.' },
          { id: 'call',  label: 'Call $5',        quality: 'acceptable', evLoss: 1.5, coaching: 'Cold-calling with A2s creates awkward situations postflop. You often have ace-low and disconnect from the board. 3-bet or fold is cleaner than calling in position with a weak hand.' },
        ],
      },
    ],
    summary: 'A2s-A5s are the canonical 3-bet bluff hands because they block the nut end of villain\'s value range (AA, AK) while having equity when called. They also generate fold equity with a strong ace-high hand that blocks villain\'s calling combos.',
    tags: ['preflop', 'CO', '3-bet bluff', 'A2s', 'blocker', 'light 3-bet'],
  },

  // ── p22 ──────────────────────────────────────────────────────────────────
  {
    id: 'p22-87s-sb-complete',
    title: 'SB vs Limpers — Complete or Raise with 87s?',
    description: 'Two players limp. You\'re in the SB with 87s. Should you complete, raise, or fold?',
    difficulty: 'beginner',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'SB',
    villainPosition: 'BB',
    heroCards: ['8h', '7h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'UTG limps, CO limps. Folds to SB (hero) with 8h7h. BB still to act.',
        prompt: 'Two limpers. You\'re in SB with 87s. Raise, complete, or fold?',
        options: [
          { id: 'raise',    label: 'Raise to $8',    quality: 'perfect',    evLoss: 0,   coaching: 'Raising 87s with limpers in the pot is optimal. You build a bigger pot with a hand that plays well multiway (hits straights and flushes), deny equity to limpers by possibly folding some out, and set up a favorable flop as the aggressor.' },
          { id: 'complete', label: 'Complete $0.50',  quality: 'good',       evLoss: 1,   coaching: 'Completing is fine and conservative. You get a cheap flop with good implied odds. However, raising is higher EV — you charge players to play with weak limping ranges and build the pot with a strong speculative hand.' },
          { id: 'fold',     label: 'Fold',            quality: 'mistake',    evLoss: 2,   coaching: 'Folding 87s in the SB vs two limpers is too tight. You\'re getting excellent odds to see a flop with a hand that can make monsters. Complete at minimum, ideally raise.' },
        ],
      },
    ],
    summary: 'Versus limpers, the SB should often raise with playable hands to build the pot and deny equity. 87s has excellent implied odds and plays well multiway — raising builds a pot where your strong hands (straights, flushes) can win big. Completing is fine but raising is higher EV.',
    tags: ['preflop', 'SB', 'vs limpers', '87s', 'iso-raise', 'suited connectors'],
  },

  // ── p23 ──────────────────────────────────────────────────────────────────
  {
    id: 'p23-tt-utg-full-ring',
    title: 'Full Ring UTG — Open TT or Not?',
    description: 'You\'re UTG in a 9-handed full ring game with TT. Open-raise, limp, or fold?',
    difficulty: 'intermediate',
    category: 'Preflop',
    gameType: 'cash',
    format: 'Full Ring',
    heroPosition: 'UTG',
    villainPosition: 'BB',
    heroCards: ['Tc', 'Td'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'You are UTG in a 9-max game with TcTd. 8 players left to act.',
        prompt: 'UTG full ring with TT. Open-raise, limp, or fold?',
        options: [
          { id: 'raise',  label: 'Open to $6',    quality: 'perfect',    evLoss: 0,   coaching: 'TT is a standard open from UTG full ring. Even with 8 players behind, TT has high equity pre-flop and you want to build the pot with a premium hand. Open to 3BB to deny the field cheap entry and define your range as strong.' },
          { id: 'limp',   label: 'Limp $1',       quality: 'mistake',    evLoss: 2.5, coaching: 'Limping TT from UTG full ring is poor. You don\'t build the pot with a strong hand, create a messy multiway pot, and can\'t define any ranges. Open or fold — never limp from EP with pocket tens.' },
          { id: 'fold',   label: 'Fold',          quality: 'punt',       evLoss: 5,   coaching: 'Folding TT from UTG full ring is a massive mistake. TT is a top-5% hand and clearly profitable to open even from UTG in full ring. Never fold pocket pairs from EP in a cash game.' },
        ],
      },
    ],
    summary: 'TT is a clear open from UTG in full ring. In full ring, your UTG opening range narrows compared to 6-max (roughly top 15% vs top 20%), but TT is firmly in that range. Open for value, build the pot, and play postflop as the aggressor.',
    tags: ['preflop', 'UTG', 'full ring', 'TT', 'opening range'],
  },

  // ── p24 ──────────────────────────────────────────────────────────────────
  {
    id: 'p24-kqs-vs-squeeze',
    title: 'Facing a Squeeze — KQs from the BB',
    description: 'CO opens, BTN cold-calls, and SB squeezes. You\'re in the BB with KQs. Call, 4-bet, or fold?',
    difficulty: 'advanced',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'SB',
    heroCards: ['Kh', 'Qh'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens to $15. BTN cold-calls. SB squeezes to $55. Action on BB with KhQh.',
        prompt: 'Facing a SB squeeze with KQs in the BB. Call, 4-bet, or fold?',
        options: [
          { id: 'fold',  label: 'Fold',          quality: 'perfect',    evLoss: 0,   coaching: 'Folding KQs vs a 3-way squeeze is correct. The SB\'s squeeze range is tight — they have JJ+, AKs, and perhaps AQs. KQs is dominated by much of this range and you have no position advantage. Folding preserves your stack.' },
          { id: 'call',  label: 'Call $50',       quality: 'acceptable', evLoss: 2,   coaching: 'Calling is tempting but you\'d be playing OOP vs a strong range in a bloated pot. Your implied odds are poor since KQs rarely gets the money in good vs a tight squeeze range. Folding is cleaner.' },
          { id: '4bet',  label: '4-bet to $140',  quality: 'mistake',    evLoss: 5,   coaching: '4-betting with KQs vs a 3-way squeeze puts you in a terrible spot. The SB will often have JJ+/AKs and your 4-bet is essentially a bluff into a tight range. You risk losing a large pot OOP with a dominated hand.' },
        ],
      },
    ],
    summary: 'KQs looks strong but is regularly dominated by squeeze ranges (KK, QQ, AKs, AK). In multi-way squeeze situations OOP, folding marginal hands is correct despite the apparent strength of KQs. Position and range interaction matter more than raw card strength.',
    tags: ['preflop', 'BB', 'squeeze', 'KQs', 'fold equity', 'range dominance'],
  },

  // ── p25 ──────────────────────────────────────────────────────────────────
  {
    id: 'p25-jj-5bet-jam',
    title: 'JJ Facing a 5-Bet Shove',
    description: 'You 4-bet with JJ and the villain 5-bets all-in. Call off or fold?',
    difficulty: 'advanced',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BTN',
    heroCards: ['Jh', 'Jc'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'BTN opens to $15. You 4-bet to $45 from CO. BTN 5-bet jams for 100BB ($500 total).',
        prompt: 'You 4-bet JJ and face a 5-bet shove from BTN. Call or fold?',
        options: [
          { id: 'fold',  label: 'Fold JJ',       quality: 'perfect',    evLoss: 0,   coaching: 'Folding JJ vs a 5-bet is correct in most spots. 5-bet ranges are extremely tight — typically QQ+, AK. JJ flips against AK and is dominated by QQ+. You\'re getting roughly 1.5:1 pot odds but facing a range where you\'re an equity underdog. Fold and preserve your stack.' },
          { id: 'call',  label: 'Call off',       quality: 'acceptable', evLoss: 2.5, coaching: 'Calling is reasonable in player-pool-specific spots where villain has a wider 5-bet range. Against tight regulars who only 5-bet QQ+/AK, folding JJ is higher EV. Against aggro players who 5-bet bluff frequently, calling becomes correct.' },
        ],
      },
    ],
    summary: 'JJ vs a 5-bet is one of poker\'s most uncomfortable spots. Standard 5-bet ranges are QQ+, AKs, AKo — making JJ a coin-flip or dominated hand. Folding JJ vs a tight player\'s 5-bet is often correct despite having a premium pair. Adjust based on villain\'s tendencies.',
    tags: ['preflop', '5-bet', 'JJ', 'fold', '4-bet pot', 'range analysis'],
  },

  // ── p26 ──────────────────────────────────────────────────────────────────
  {
    id: 'p26-hu-preflop-decision',
    title: 'Heads-Up Preflop — Steal or Check?',
    description: 'Heads-up match. BTN vs BB. What is your opening strategy with J6o from the BTN?',
    difficulty: 'intermediate',
    category: 'BvB',
    gameType: 'cash',
    format: 'Heads-Up',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Jh', '6d'],
    effectiveStack: 100,
    stakes: '$1/$2 HU',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Heads-up cash match. Hero is on the BTN (which is also the SB in HU). Hero has J6o.',
        prompt: 'Heads-up on the BTN with J6o. Open-raise or check?',
        options: [
          { id: 'raise',  label: 'Raise to $4',   quality: 'perfect',    evLoss: 0,   coaching: 'In heads-up poker, the BTN should open-raise almost any two cards — typically 75-80%+ of hands. J6o is well above that threshold. You have position, fold equity, and J6o has reasonable equity vs a single opponent\'s calling range. Raise every time.' },
          { id: 'check',  label: 'Limp / Check',  quality: 'mistake',    evLoss: 2,   coaching: 'Checking back preflop in HU with a hand as strong as J6o is a mistake. You give up fold equity and initiative for no reason. In HU, the BTN should raise a very wide range to exploit their positional advantage.' },
          { id: 'fold',   label: 'Fold',           quality: 'punt',       evLoss: 5,   coaching: 'Folding J6o from the BTN in a HU match is a massive punt. You have position and there is one opponent. J6o wins roughly 50%+ of the time vs a random hand. Raise or at minimum see a flop.' },
        ],
      },
    ],
    summary: 'Heads-up poker requires extremely wide preflop ranges from the BTN. You should be raising ~75-80% of hands or more, depending on the match dynamics. J6o is clearly in that range. Position is dominant in HU — never give it up by checking back a decent hand.',
    tags: ['preflop', 'HU', 'BTN', 'J6o', 'heads-up range', 'aggression'],
  },

  // ── p27 ──────────────────────────────────────────────────────────────────
  {
    id: 'p27-qts-bb-vs-utg',
    title: 'BB Defend vs UTG Open — QTs',
    description: 'UTG opens to 3BB. Should you defend QTs from the BB or fold given the tight EP range?',
    difficulty: 'intermediate',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'UTG',
    heroCards: ['Qs', 'Ts'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'UTG opens to $6 (3BB). Folds around. BB (hero) with QsTs.',
        prompt: 'UTG opens 3BB heads-up to you in the BB with QTs. Call, 3-bet, or fold?',
        options: [
          { id: 'call',  label: 'Call $4',        quality: 'perfect',    evLoss: 0,   coaching: 'QTs is a profitable BB call vs UTG. You\'re getting 2:1 pot odds with a connected suited hand. UTG\'s range is tight but your QTs has good playability on many boards — top pair, straight draws, flush draws. You play OOP but the price is right.' },
          { id: '3bet',  label: '3-bet to $18',   quality: 'acceptable', evLoss: 1.5, coaching: '3-betting QTs vs UTG is thin. UTG opens a tight range (top 15% 6-max), and your QTs is often dominated or facing strong hands. Calling is cleaner here — save 3-bets for better blocker hands (AK, QQ+).' },
          { id: 'fold',  label: 'Fold',           quality: 'mistake',    evLoss: 2.5, coaching: 'Folding QTs vs a UTG open getting 2:1 is a leak. QTs has enough equity vs UTG\'s range and playability on wet boards to be a clear defend. You would fold K3o or 72o here, not QTs.' },
        ],
      },
    ],
    summary: 'Even vs tight UTG ranges, QTs in the BB is a standard call at 2:1 pot odds. Suited connectors and suited broadways have enough equity and implied odds to defend. 3-betting is marginal because UTG\'s calling range will dominate QTs too often.',
    tags: ['preflop', 'BB defense', 'QTs', 'UTG', 'pot odds'],
  },

  // ── p28 ──────────────────────────────────────────────────────────────────
  {
    id: 'p28-ato-iso-raise',
    title: 'Isolate the Fish — ATo vs Limper',
    description: 'A recreational player limps from UTG. Should you iso-raise from CO with ATo?',
    difficulty: 'beginner',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'UTG',
    heroCards: ['Ah', 'To'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'UTG (known recreational player) limps $2. Folds to CO (hero) with AhTo.',
        prompt: 'A recreational limper is UTG. You have ATo in CO. Iso-raise, call, or fold?',
        options: [
          { id: 'raise',  label: 'Raise to $8',    quality: 'perfect',    evLoss: 0,   coaching: 'Iso-raising ATo is the correct play. You have a strong hand that dominates the limper\'s wide range, you get position on them postflop, and you can potentially isolate them heads-up. Make it 3-4BB to try to get HU with the rec player.' },
          { id: 'limp',   label: 'Over-limp',       quality: 'mistake',    evLoss: 2.5, coaching: 'Over-limping allows more players to enter the pot cheaply. You lose your positional leverage and face a multiway pot with a hand that plays best heads-up. Always raise with strong hands vs limpers.' },
          { id: 'fold',   label: 'Fold',            quality: 'punt',       evLoss: 5,   coaching: 'Folding ATo vs a recreational limper is a massive punt. You have a hand that\'s ahead of their entire limping range (often 72o through Ax). Never fold premium hands vs weak players.' },
        ],
      },
    ],
    summary: 'Isolating recreational players (fish) is one of the highest-EV spots in poker. Raise 3-4x vs limpers with hands that dominate their range. ATo crushes the typical recreational limping range. Over-limping or folding squanders the opportunity to get chips from the weakest player.',
    tags: ['preflop', 'CO', 'iso-raise', 'ATo', 'recreational player', 'limper'],
  },

  // ── p29 ──────────────────────────────────────────────────────────────────
  {
    id: 'p29-98s-sb-3bet',
    title: 'SB vs BTN Open — 3-bet or Call with 98s?',
    description: 'BTN opens. You have 98s in the SB. Should you 3-bet as a semi-bluff, call, or fold?',
    difficulty: 'intermediate',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'SB',
    villainPosition: 'BTN',
    heroCards: ['9h', '8h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'BTN opens to $5. Folds to SB (hero) with 9h8h.',
        prompt: 'BTN opens. You have 98s in the SB. 3-bet, call, or fold?',
        options: [
          { id: '3bet',  label: '3-bet to $15',   quality: 'perfect',    evLoss: 0,   coaching: '3-betting 98s from the SB is a great play. You have fold equity vs BTN\'s wide open, and 98s has excellent playability when called (straight and flush draws). It also balances your 3-bet range by mixing in suited connectors alongside premium hands.' },
          { id: 'call',  label: 'Call $4',         quality: 'good',       evLoss: 0.5, coaching: 'Calling 98s from the SB is fine — you see a cheap flop with good implied odds. However, playing OOP with a speculative hand in a SRP is slightly weaker than 3-betting with fold equity.' },
          { id: 'fold',  label: 'Fold',            quality: 'mistake',    evLoss: 2,   coaching: 'Folding 98s from the SB vs a BTN open is slightly tight. This hand is borderline — calling or 3-betting is superior. If you\'re going to play a hand like 98s OOP, 3-betting is actually the best option as it gives you fold equity.' },
        ],
      },
    ],
    summary: 'Suited connectors like 98s are effective 3-bet hands from the SB. They provide fold equity when villain folds, great drawing potential when called, and balance your value-heavy 3-bet range. The SB is a good position to attack BTN\'s wide opening range with aggressive 3-bets.',
    tags: ['preflop', 'SB', '3-bet', '98s', 'suited connectors', 'bluff'],
  },

  // ── p30 ──────────────────────────────────────────────────────────────────
  {
    id: 'p30-4bet-sizing-ako',
    title: '4-Bet Sizing — AKo OOP vs BTN 3-Bet',
    description: 'You open CO, BTN 3-bets. You have AKo. What is the optimal 4-bet size when out of position?',
    difficulty: 'advanced',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BTN',
    heroCards: ['Ah', 'Kd'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens to $15. BTN 3-bets to $45. Action on CO with AhKd.',
        prompt: 'CO opens, BTN 3-bets to $45. You have AKo OOP. What is the optimal 4-bet?',
        options: [
          { id: '4bet_25x', label: '4-bet to $110',  quality: 'perfect',    evLoss: 0,   coaching: '4-betting to ~2.5x (around $110-120) is optimal OOP with AKo. This size puts maximum pressure on BTN\'s range while leaving room to fold vs a 5-bet with a marginal hand like AKo that doesn\'t want to go broke vs QQ+. It also extracts max value if BTN calls with hands like AQ, TT-KK.' },
          { id: 'jam',      label: 'Jam all-in',      quality: 'good',       evLoss: 1,   coaching: 'Jamming is fine with AKo — you\'re flipping against QQ and ahead of AQ/KK is losing to AA. However, AKo prefers not to get all-in against tight 3-bet ranges (which often skew toward QQ+). A smaller 4-bet is slightly better.' },
          { id: 'call',     label: 'Call $30',         quality: 'mistake',    evLoss: 3,   coaching: 'Calling a 3-bet OOP with AKo creates a poor pot structure. AKo is too strong to just call a 3-bet — you should be raising for value. Calling leaves money on the table and plays postflop OOP in a large pot.' },
        ],
      },
    ],
    summary: 'When 4-betting OOP with AKo, size to 2.5x the 3-bet (not jam). This gives you room to fold vs a 5-bet (AKo is not a clear call-off vs tight ranges), applies maximum pressure, and extracts value from AQ, AJ, TT-QQ that might call and fold flops.',
    tags: ['preflop', '4-bet', 'AKo', 'OOP', 'sizing', 'CO'],
  },

  // ── p31 ──────────────────────────────────────────────────────────────────
  {
    id: 'p31-77-co-3bet-or-flat',
    title: 'CO Decision — 77 vs UTG Open: 3-Bet or Flat?',
    description: 'UTG opens. You have 77 in CO. Should you 3-bet, cold-call, or fold?',
    difficulty: 'intermediate',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'UTG',
    heroCards: ['7c', '7d'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'UTG opens to $5. Folds to CO (hero) with 7c7d.',
        prompt: 'UTG opens. You have 77 in CO. 3-bet, cold-call, or fold?',
        options: [
          { id: 'call',  label: 'Call $5',        quality: 'perfect',    evLoss: 0,   coaching: 'Cold-calling 77 in CO vs a UTG open is the standard play. You have good set-mining odds (implied odds at 100BB), position vs UTG, and 77 plays well HU postflop when you flop a set or overpair on low boards. Calling keeps the pot small if you miss.' },
          { id: '3bet',  label: '3-bet to $16',   quality: 'good',       evLoss: 0.5, coaching: '3-betting 77 vs UTG is a light 3-bet that can work — but UTG\'s calling range dominates you (they call with 88+, AK, AQs). When called, you play OOP with 77, often as an underdog. Calling is marginally better unless you plan to fold to 4-bets often.' },
          { id: 'fold',  label: 'Fold',           quality: 'mistake',    evLoss: 2,   coaching: 'Folding 77 in CO vs UTG is slightly tight. You have position and good set-mining potential at 100BB. While UTG\'s range is tight, calling with pocket sevens for implied odds is clearly profitable.' },
        ],
      },
    ],
    summary: 'Small and medium pairs from the CO vs UTG opens play best as set-mine calls. You have position, implied odds, and pairs play well when they hit. 3-betting is thin vs UTG\'s tight range. Set mine vs premiums — a flopped set can win a big pot.',
    tags: ['preflop', 'CO', '77', 'set mine', 'UTG', 'implied odds'],
  },

  // ── p32 ──────────────────────────────────────────────────────────────────
  {
    id: 'p32-kqs-bb-squeeze',
    title: 'BB Squeeze — KQs vs CO Open + BTN Call',
    description: 'CO opens, BTN cold-calls. Do you squeeze KQs from the BB or flat?',
    difficulty: 'intermediate',
    category: 'Squeeze',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'CO',
    heroCards: ['Kd', 'Qd'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens to $5. BTN cold-calls. SB folds. Action on BB with KdQd.',
        prompt: 'CO opens, BTN cold-calls. You have KQs in the BB. Squeeze, call, or fold?',
        options: [
          { id: 'squeeze', label: '3-bet to $22',  quality: 'perfect',    evLoss: 0,   coaching: 'Squeezing KQs is optimal here. You have a strong hand that dominates both CO\'s and BTN\'s ranges, fold equity vs both players, and KQs plays well when called (top pair top kicker, flush draws). The BTN cold-call is wide and often weak — squeezing punishes them.' },
          { id: 'call',    label: 'Call $3',        quality: 'acceptable', evLoss: 1.5, coaching: 'Calling is fine — you see a cheap flop with a strong hand. However, KQs is too good not to squeeze in a multi-way pot. You create fold equity, thin the field, and play a bigger pot with an advantaged hand. Squeeze is superior.' },
          { id: 'fold',    label: 'Fold',           quality: 'punt',       evLoss: 7,   coaching: 'Folding KQs from the BB in a squeeze spot is a massive error. KQs is a top-15 hand and the perfect squeeze candidate. Never fold this.' },
        ],
      },
    ],
    summary: 'BB squeezes are powerful because you have maximum pot odds already invested and face two players with defined ranges. KQs is an ideal squeeze hand — it has value vs both players\' ranges, strong playability, and creates significant fold equity vs cold-callers.',
    tags: ['preflop', 'BB', 'squeeze', 'KQs', '3-bet', 'CO+BTN'],
  },

  // ── p33 ──────────────────────────────────────────────────────────────────
  {
    id: 'p33-a3s-utg1-rfi',
    title: 'UTG+1 RFI — Should You Open A3s?',
    description: 'You are UTG+1 in a 6-max game with A3s. Open or fold?',
    difficulty: 'beginner',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'UTG+1',
    villainPosition: 'BB',
    heroCards: ['Ac', '3c'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'You are UTG+1 (second to act) in a 6-max game with Ac3c.',
        prompt: 'UTG+1 in 6-max with A3s. Open or fold?',
        options: [
          { id: 'open',  label: 'Open to $3',    quality: 'perfect',    evLoss: 0,   coaching: 'A3s is a standard open from UTG+1 in 6-max. Suited aces have excellent value — they block the nut flush, make nut flushes, and have strong backdoor equity. In 6-max, UTG+1 is the equivalent of LJ (LoJack) — you can open A3s+ comfortably.' },
          { id: 'fold',  label: 'Fold',          quality: 'mistake',    evLoss: 2,   coaching: 'Folding A3s from UTG+1 6-max is slightly tight. While it\'s a borderline hand vs full ring UTG, in 6-max it\'s clearly in the opening range. Suited aces with wheel cards have great value and should be opened from all positions in 6-max.' },
        ],
      },
    ],
    summary: 'Suited aces are valuable hands in 6-max — they play well postflop with nut flush potential and have good blockers. A3s+ is a standard open from UTG+1 in 6-max (vs full ring UTG where you might fold A3s). Understand how position affects your opening ranges.',
    tags: ['preflop', 'UTG+1', 'A3s', 'suited ace', 'RFI', '6-max range'],
  },

  // ── p34 ──────────────────────────────────────────────────────────────────
  {
    id: 'p34-87s-deep-cold-call',
    title: 'Deep Stack Cold Call — 87s vs CO 3-Bet at 200BB',
    description: 'You open BTN with 87s, CO 3-bets. At 200BB deep, should you call, 4-bet, or fold?',
    difficulty: 'advanced',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'CO',
    heroCards: ['8c', '7c'],
    effectiveStack: 200,
    stakes: '$2/$5',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'You open BTN to $15. CO 3-bets to $45. Effective stacks: 200BB ($1,000). BTN has 87s.',
        prompt: 'CO 3-bets. You have 87s on BTN at 200BB deep. Call, 4-bet, or fold?',
        options: [
          { id: 'call',  label: 'Call $30',       quality: 'perfect',    evLoss: 0,   coaching: 'Calling 87s IP at 200BB is excellent. Stack depth dramatically increases implied odds for speculative hands. If you flop a two-pair, set, or strong draw, you can win a massive pot. At 200BB you are getting the price to call with 87s and postflop equity.' },
          { id: 'fold',  label: 'Fold',           quality: 'mistake',    evLoss: 2.5, coaching: 'Folding 87s in position at 200BB deep is too tight. Deep stacks dramatically increase the value of speculative hands — straights and flushes win enormous pots. At 100BB you might fold; at 200BB you clearly call.' },
          { id: '4bet',  label: '4-bet to $120',  quality: 'mistake',    evLoss: 3,   coaching: '4-betting 87s is a 4-bet bluff that faces a tough spot vs CO\'s 5-bet or call. Your hand doesn\'t benefit from 4-betting — it benefits from seeing a flop with implied odds. Call and try to make a monster.' },
        ],
      },
    ],
    summary: 'Stack depth changes implied odds dramatically. At 200BB, suited connectors like 87s become profitable calls even vs tight 3-bet ranges because straights and flushes can win massive pots. Deep stack play rewards speculative hands that can make monster holdings on favorable boards.',
    tags: ['preflop', 'BTN', 'deep stack', '87s', 'implied odds', '200BB'],
  },

  // ── p35 ──────────────────────────────────────────────────────────────────
  {
    id: 'p35-bvb-q8s',
    title: 'BvB Escalation — Q8s from SB vs BB 3-Bet',
    description: 'You open SB with Q8s and BB 3-bets. Call, 4-bet, or fold?',
    difficulty: 'intermediate',
    category: 'BvB',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'SB',
    villainPosition: 'BB',
    heroCards: ['Qh', '8h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'You open SB to $5. BB 3-bets to $15.',
        prompt: 'You opened Q8s from SB and BB 3-bets to $15. Call, 4-bet, or fold?',
        options: [
          { id: 'call',  label: 'Call $10',       quality: 'perfect',    evLoss: 0,   coaching: 'Calling Q8s OOP vs a BB 3-bet is correct. BvB 3-bets are often wider and bluffier than CO/BTN 3-bets. Q8s has good equity and playability. You\'re getting ~2.3:1 and the BB\'s 3-bet range in BvB includes many weaker hands you can outplay postflop.' },
          { id: 'fold',  label: 'Fold',           quality: 'acceptable', evLoss: 1.5, coaching: 'Folding is a reasonable default vs a BB 3-bet, especially if villain 3-bets tight. However, BvB 3-bet ranges tend to be wider, making Q8s a marginal call. Folding is the more conservative play.' },
          { id: '4bet',  label: '4-bet to $40',   quality: 'mistake',    evLoss: 2.5, coaching: '4-betting Q8s as a light bluff OOP is too aggressive. You don\'t have the blocker value of a suited ace, and Q8s can\'t fold to a 5-bet profitably. Call or fold.' },
        ],
      },
    ],
    summary: 'BvB 3-bets are frequently wider and bluffier than 3-bets from other positions. Q8s is a marginal but profitable call in BvB spots — you have decent equity and playability against a wide 3-bet range. Be aware that 4-betting without proper blockers is risky OOP.',
    tags: ['preflop', 'BvB', 'SB', 'Q8s', '3-bet', 'blind war'],
  },

  // ── p36 ── MULTI-STREET: preflop + flop ──────────────────────────────────
  {
    id: 'p36-aa-sb-limp-reraise',
    title: 'Slow-Play AA — Limp-Reraise from SB',
    description: 'You have AA in the SB. Consider the limp-reraise trap, then navigate the flop.',
    difficulty: 'advanced',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'SB',
    villainPosition: 'BTN',
    heroCards: ['As', 'Ad'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'BTN opens to $5. SB (hero) has AsAd.',
        prompt: 'BTN opens. You have AA in the SB. 3-bet, limp-reraise, or call?',
        options: [
          { id: '3bet',         label: '3-bet to $16',    quality: 'perfect',    evLoss: 0,   coaching: '3-betting AA standard is the highest EV play. You build a pot immediately, get called by hands that are dominated, and avoid multiway situations where AA loses more of its edge. Always 3-bet AA from the SB vs a BTN open.' },
          { id: 'limp_reraise', label: 'Limp then reraise', quality: 'good',     evLoss: 0.5, coaching: 'Limp-reraising with AA can be effective if BTN raises a lot vs SB completes. You trap them for extra money. However, standard 3-betting is slightly higher EV as you always build the pot vs BTN\'s wide range.' },
          { id: 'call',         label: 'Call $3',          quality: 'mistake',   evLoss: 3,   coaching: 'Flatting AA from the SB is too passive. You allow BB to see a cheap flop, play multiway with a hand that dominates all opponents, and miss significant value. Always raise with AA.' },
        ],
      },
      {
        street: 'flop',
        board: ['Kh', '7d', '3c'],
        context: '3-bet pot. BTN calls. Pot $33. Flop: Kh 7d 3c. You are OOP.',
        prompt: 'Kh 7d 3c rainbow. You have AA (overpair) OOP in a 3-bet pot. Check or bet?',
        options: [
          { id: 'bet_33',  label: 'Bet $11 (33%)',  quality: 'perfect',    evLoss: 0,   coaching: 'Small bet with AA on this board. The Kh is a scare card for villain who called a 3-bet — many of their hands have Kx. Betting small induces calls from Kx and weaker pairs. It also keeps your range balanced with your Kx combos.' },
          { id: 'check',   label: 'Check',           quality: 'good',       evLoss: 0.5, coaching: 'Checking with AA to induce BTN to bet with their Kx, draws, or weaker overpairs is also fine. Both strategies work — checking can induce more bluffs and generates information.' },
          { id: 'bet_75',  label: 'Bet $25 (75%)',   quality: 'acceptable', evLoss: 2,   coaching: 'Large bet with AA on a K-high board folds out most of BTN\'s hands except Kx. You want to keep their range wide. Small bets or checking is better to extract more value across three streets.' },
        ],
      },
    ],
    summary: 'AA should almost always be 3-bet from the SB vs a BTN open. On K-high boards in 3-bet pots, small bets or checks keep villain\'s range wide and extract value across multiple streets. Don\'t overbet with AA on boards that connect well with villain\'s range.',
    tags: ['preflop', 'SB', 'AA', '3-bet', 'limp-reraise', 'flop'],
  },

  // ── p37 ── MULTI-STREET: preflop + flop ──────────────────────────────────
  {
    id: 'p37-kk-btn-vs-3bet-ah-flop',
    title: 'KK on the BTN — 3-Bet Pot, Ace on the Flop',
    description: 'You 3-bet with KK from BTN and face the worst flop: an ace. How do you proceed?',
    difficulty: 'intermediate',
    category: '3-bet Pot',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'CO',
    heroCards: ['Kh', 'Ks'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens to $5. BTN (hero) 3-bets to $16. CO calls.',
        prompt: 'CO opens, you 3-bet with KK from BTN. CO calls. Pot $33.',
        options: [
          { id: '3bet',  label: '3-bet to $16',  quality: 'perfect',    evLoss: 0,   coaching: 'KK is a clear value 3-bet from the BTN. You want to build a pot with the second-best starting hand, isolate CO, and set up a favorable HU pot in position.' },
          { id: 'call',  label: 'Call $5',        quality: 'mistake',    evLoss: 3,   coaching: 'Flatting KK from the BTN is a significant mistake. You miss value vs CO\'s wide range, don\'t charge hands like AQ and AK, and lose the positional leverage a 3-bet creates.' },
        ],
      },
      {
        street: 'flop',
        board: ['Ac', '8d', '3h'],
        context: 'Pot $33. Flop: Ac 8d 3h. CO checks.',
        prompt: 'CO checks the Ac 8d 3h flop. You have KK (underpair to Ace). Bet or check?',
        options: [
          { id: 'check',   label: 'Check',          quality: 'perfect',    evLoss: 0,   coaching: 'Checking is correct. CO called a 3-bet and checks an ace-high flop — many of their hands have Ax. Your KK is now a bluff-catcher. Check and re-evaluate — if CO bets, consider your pot odds to call. Betting gets called or raised by hands that beat you.' },
          { id: 'bet_33',  label: 'Bet $11 (33%)',  quality: 'acceptable', evLoss: 2,   coaching: 'Betting small is defensible as a way to get info and charge weaker pairs. However, you rarely have better hands calling and often face Ax that beats you. Checking with KK on an ace board is the standard play.' },
          { id: 'bet_75',  label: 'Bet $25 (75%)',  quality: 'mistake',    evLoss: 4,   coaching: 'Large bet on an ace-high board with KK is poor. You primarily fold out worse hands and get called or raised by Ax. This is effectively bluffing with a strong hand — never do this.' },
        ],
      },
    ],
    summary: 'KK is a clear 3-bet from any position, but on ace-high flops in 3-bet pots, KK becomes a bluff-catcher. Check to induce and use pot odds to call villain\'s bets. Never bet KK large on ace boards — you fold out worse and get action from better.',
    tags: ['preflop', '3-bet pot', 'KK', 'BTN', 'ace flop', 'bluff-catch'],
  },

  // ── p38 ── MULTI-STREET: preflop + flop ──────────────────────────────────
  {
    id: 'p38-ako-co-vs-squeeze-flop',
    title: 'AKo CO — Facing a BTN Squeeze, Then the Flop',
    description: 'You open CO with AKo and BTN squeezes. How do you respond preflop and postflop?',
    difficulty: 'intermediate',
    category: '4-bet Pot',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BTN',
    heroCards: ['Ah', 'Kc'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens to $5. BTN 3-bets to $17. SB/BB fold.',
        prompt: 'BTN 3-bets your CO open. You have AKo. 4-bet, call, or fold?',
        options: [
          { id: '4bet',  label: '4-bet to $42',  quality: 'perfect',    evLoss: 0,   coaching: '4-betting AKo is clearly correct. You have a premium hand and a 3-bet steal opportunity to punish. Your 4-bet range here is primarily AK, QQ, KK, AA — so 4-betting with AKo is standard. If BTN shoves, you call — AKo has roughly 44% equity vs QQ+/AKs.' },
          { id: 'call',  label: 'Call $12',       quality: 'good',       evLoss: 0.5, coaching: 'Calling with AKo to see the flop is a valid flatting strategy. You have great implied odds if you hit an A or K. However, 4-betting is slightly higher EV as it generates fold equity and builds a larger pot with a premium hand.' },
          { id: 'fold',  label: 'Fold',           quality: 'punt',       evLoss: 8,   coaching: 'Never fold AKo to a 3-bet. This is one of the strongest starting hands in poker. Folding is a massive mistake.' },
        ],
      },
      {
        street: 'flop',
        board: ['Kd', '7h', '2s'],
        context: 'BTN calls the 4-bet. Pot $85. Flop: Kd 7h 2s. BTN checks.',
        prompt: 'Kd 7h 2s — you flopped top pair top kicker in a 4-bet pot. BTN checks.',
        options: [
          { id: 'bet_25',  label: 'Bet $28 (33%)',  quality: 'perfect',    evLoss: 0,   coaching: 'Small bet on this dry board is optimal. In a 4-bet pot, BTN called your 4-bet and now faces a king — their range has many medium pairs (JJ, TT) and weaker kings (KQ). A small bet induces these hands to call and builds the pot efficiently.' },
          { id: 'check',   label: 'Check',           quality: 'good',       evLoss: 0.5, coaching: 'Checking with TPTK to trap is also good here. BTN may stab with air or bet their pair. However, betting small is marginally higher EV as you build the pot with a likely best hand.' },
          { id: 'bet_66',  label: 'Bet $56 (66%)',   quality: 'acceptable', evLoss: 1.5, coaching: 'Medium bet works but may fold out hands you want to call. On a dry board with TPTK, small bets keep more of villain\'s range in. Save the larger sizes for when draws appear.' },
        ],
      },
    ],
    summary: '4-betting AKo vs a 3-bet is standard. On dry boards in 4-bet pots, small cbets are optimal — they keep villain\'s range wide and build the pot across multiple streets with TPTK. In bloated pots, think about which sizing extracts the most value from villain\'s specific range.',
    tags: ['preflop', '4-bet', 'AKo', 'CO', '3-bet pot', 'flop sizing'],
  },

  // ── p39 ── MULTI-STREET: preflop + flop ──────────────────────────────────
  {
    id: 'p39-qq-utg-multiway',
    title: 'QQ UTG — Multiway Pot on a J-High Flop',
    description: 'You open QQ from UTG, two players call. Navigate a tricky J-high flop multiway.',
    difficulty: 'intermediate',
    category: '3-bet Pot',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'UTG',
    villainPosition: 'CO',
    heroCards: ['Qc', 'Qd'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'UTG opens to $5. CO calls. BTN calls. Pot $17.',
        prompt: 'You opened QQ from UTG and two players called. Pot $17 three-ways. How do you feel about the preflop play?',
        options: [
          { id: 'happy',    label: 'Good spot — open and take it',  quality: 'perfect',    evLoss: 0,   coaching: 'Opening QQ from UTG is correct. In an ideal world you\'d 3-bet pre-flop, but since you\'re UTG, you open-raise and face callers. QQ is a strong hand even multiway — you play postflop with the range advantage.' },
          { id: 'squeeze',  label: 'Should have re-raised CO\'s call', quality: 'acceptable', evLoss: 0.5, coaching: 'You can\'t reraise a call preflop in poker — once you open and they call, you proceed to the flop. The only decision was the initial open-raise, which with QQ is always correct. Moving to postflop.' },
        ],
      },
      {
        street: 'flop',
        board: ['Jc', '8h', '4d'],
        context: 'Pot $17. Flop: Jc 8h 4d (rainbow). You are UTG (first to act).',
        prompt: 'Multiway pot. Jc 8h 4d rainbow. You have QQ (overpair). First to act. Check, small bet, or large bet?',
        options: [
          { id: 'bet_33',  label: 'Bet $7 (40%)',   quality: 'perfect',    evLoss: 0,   coaching: 'Small bet is optimal multiway. QQ needs protection against overcards on this connected board. A small bet charges draws (Tx, 97, 65), keeps medium pairs in, and builds the pot with your likely best hand. Don\'t over-commit until you know where you stand.' },
          { id: 'check',   label: 'Check',           quality: 'good',       evLoss: 1,   coaching: 'Checking multiway to avoid a messy spot is fine, but you give free cards to draws. On a semi-connected board with QQ, betting small to protect and build is slightly better.' },
          { id: 'bet_75',  label: 'Bet $13 (75%)',   quality: 'acceptable', evLoss: 2,   coaching: 'Large bet multiway risks folding out all but the strongest hands. With QQ as an overpair (not the nuts), you prefer to keep medium-strength hands in and avoid building a pot you might be losing.' },
        ],
      },
    ],
    summary: 'Opening QQ from UTG is standard. Multiway postflop, bet small for value and protection on connected boards — you need to charge draws while keeping weaker pairs in the pot. Checking can give free cards to dangerous draws that can crack your overpair.',
    tags: ['preflop', 'QQ', 'UTG', 'multiway', 'overpair', 'flop bet sizing'],
  },

  // ── p40 ── MULTI-STREET: preflop + flop ──────────────────────────────────
  {
    id: 'p40-short-deck-kq-preflop',
    title: 'Short Deck Hold\'em — KQ Preflop Decision',
    description: 'In Short Deck (6+ Poker), hand values change. How does KQ play preflop and on a 9-high board?',
    difficulty: 'intermediate',
    category: 'Preflop',
    gameType: 'cash',
    format: 'Short Deck',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Kd', 'Qd'],
    effectiveStack: 100,
    stakes: '$5/$5 ante Short Deck',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Short Deck game (cards 2-5 removed). All players post $5 ante. BTN straddle. Action folds to BTN (hero) with KdQd.',
        prompt: 'Short Deck: You have KQs on the BTN with everyone posting antes. Open or fold?',
        options: [
          { id: 'raise',  label: 'Raise to $20',  quality: 'perfect',    evLoss: 0,   coaching: 'KQs is a strong hand in Short Deck. With only 36 cards, hand values shift — flushes are harder to make (fewer cards) but the deck is shorter so ranks are more clustered. KQs retains excellent value: top pair potential, flush draw power, and blocker value to strong hands.' },
          { id: 'fold',   label: 'Fold',          quality: 'mistake',    evLoss: 3,   coaching: 'Folding KQs in Short Deck from the BTN is far too tight. In Short Deck, ranges are often tighter because hand values concentrate, but KQs is clearly a playable hand in any Short Deck format from late position.' },
        ],
      },
      {
        street: 'flop',
        board: ['9d', '7d', '3s'],
        context: 'Pot $40. Flop: 9d 7d 3s. BB checks.',
        prompt: '9d 7d 3s — you have KQ with the nut flush draw (K♦Q♦). What do you do in Short Deck?',
        options: [
          { id: 'bet_66',  label: 'Bet $30 (75%)',  quality: 'perfect',    evLoss: 0,   coaching: 'In Short Deck, straights are more common (more cards between 6-A) and board connectivity is higher. With the nut flush draw + two overcards, you have massive equity. Bet to charge opponents\' equity and build the pot for when you hit.' },
          { id: 'check',   label: 'Check',           quality: 'mistake',    evLoss: 2.5, coaching: 'Checking with a nut flush draw on a connected board in Short Deck is too passive. Short Deck play tends toward higher variance and more aggressive postflop action — semi-bluff your strong draws.' },
        ],
      },
    ],
    summary: 'Short Deck changes hand values and board dynamics. Flushes are rarer but straights are more common due to the compressed deck. KQs retains strong value — it plays similarly to a suited broadway in standard hold\'em. Adapt bet sizing to the more aggressive Short Deck environment.',
    tags: ['preflop', 'short deck', 'KQs', 'BTN', 'flush draw', 'format variant'],
  },

  // ── p41 ── MULTI-STREET: preflop + flop ──────────────────────────────────
  {
    id: 'p41-76s-btn-steal-flop',
    title: 'BTN Steal with 76s — Hit or Miss on the Flop',
    description: 'You steal with 76s from BTN, BB defends. Cbet the flop or give up depending on the board.',
    difficulty: 'beginner',
    category: 'SRP',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['7h', '6h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to BTN (hero). BB is the only remaining player.',
        prompt: 'You have 76s on the BTN with only the BB remaining. Open or fold?',
        options: [
          { id: 'raise',  label: 'Open to $5',    quality: 'perfect',    evLoss: 0,   coaching: 'Opening 76s from the BTN is clearly correct. You have position, the best suited connector for implied odds, and you\'re only facing one player. 76s is in the BTN opening range vs any single opponent.' },
          { id: 'fold',   label: 'Fold',          quality: 'mistake',    evLoss: 2,   coaching: 'Folding 76s from the BTN with only the BB remaining is too tight. Suited connectors are high-value hands in position — open and play postflop where you have the advantage.' },
        ],
      },
      {
        street: 'flop',
        board: ['9h', '7d', '3s'],
        context: 'BB defends. Pot $11. Flop: 9h 7d 3s. BB checks.',
        prompt: 'You hit middle pair (7) on 9h 7d 3s. BB checks to you. Bet or check?',
        options: [
          { id: 'bet_50',  label: 'Bet $7 (63%)',  quality: 'perfect',    evLoss: 0,   coaching: 'Bet middle pair for value and protection. You have a made hand (7s) and likely best hand vs BB\'s defending range on this board. Betting denies free equity to draws (8x, 65, JT) and extracts value from weaker pairs. Standard cbet with a made hand.' },
          { id: 'check',   label: 'Check',          quality: 'good',       evLoss: 1,   coaching: 'Checking middle pair to pot control is fine. However, on a board where you likely have the best hand, betting small is higher EV. You want to build the pot and charge draws.' },
          { id: 'bet_100', label: 'Overbet $12',    quality: 'acceptable', evLoss: 1.5, coaching: 'Overbetting with middle pair on a non-nutted board is too risky. You fold out worse and get called by better. Normal sizing is preferred.' },
        ],
      },
    ],
    summary: 'BTN opens should include wide suited connector ranges. On boards where you flop made hands (middle pair), bet for value and protection. Don\'t slow-play non-nutted hands on boards with draws — charge opponents to improve against you.',
    tags: ['preflop', 'BTN', '76s', 'steal', 'flop', 'middle pair'],
  },

  // ── p42 ── MULTI-STREET: preflop + flop ──────────────────────────────────
  {
    id: 'p42-aks-3bet-oop-flop',
    title: 'AKs 3-Bet OOP — Navigating a Strong Flop',
    description: 'You 3-bet AKs from BB. You flop top pair on Ah 8c 3d. Navigate the 3-bet pot.',
    difficulty: 'intermediate',
    category: '3-bet Pot',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Ac', 'Kc'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'BTN opens to $5. BB (hero) 3-bets to $16. BTN calls.',
        prompt: 'BB 3-bets BTN with AKs. BTN calls. Pot $33. Flop coming.',
        options: [
          { id: '3bet',  label: '3-bet to $16',  quality: 'perfect',    evLoss: 0,   coaching: 'AKs is a clear value 3-bet from the BB vs a BTN open. You have a premium hand that dominates much of BTN\'s wide opening range. 3-betting for value is the standard play.' },
          { id: 'call',  label: 'Call $3',        quality: 'acceptable', evLoss: 1.5, coaching: 'Calling AKs is too passive. AKs is one of the best starting hands and warrants a 3-bet for value, especially vs a wide BTN range.' },
        ],
      },
      {
        street: 'flop',
        board: ['Ah', '8c', '3d'],
        context: 'Pot $33. Flop: Ah 8c 3d (rainbow). Hero checks OOP.',
        prompt: 'Ah 8c 3d rainbow — top pair top kicker in a 3-bet pot OOP. Check or bet?',
        options: [
          { id: 'check',   label: 'Check (slowplay)',  quality: 'perfect',    evLoss: 0,   coaching: 'Checking is excellent here. You have top pair on a dry board in a 3-bet pot. BTN will often stab with their air and medium pairs if you check. You can check-call or check-raise depending on the bet size.' },
          { id: 'bet_33',  label: 'Bet $11 (33%)',     quality: 'good',       evLoss: 0.5, coaching: 'Small cbet is also fine — you build the pot and keep BTN\'s range wide. Both check and small bet work; checking is slightly higher EV as it gives BTN more rope to bluff.' },
          { id: 'bet_75',  label: 'Bet $25 (75%)',     quality: 'acceptable', evLoss: 2,   coaching: 'Large bet folds out too much of BTN\'s range on a dry board. With the nuts (TPTK), you want to maximize action over three streets — large bets accelerate the action but reduce your ability to extract value incrementally.' },
        ],
      },
    ],
    summary: 'AKs is a clear value 3-bet preflop. On dry A-high boards in 3-bet pots OOP, checking is often optimal — it gives villain rope to bluff with their air. Mix in small cbets to keep villain\'s range wide when you choose to bet.',
    tags: ['preflop', 'BB', 'AKs', '3-bet', 'flop', 'OOP', 'TPTK'],
  },

  // ── p43 ── MULTI-STREET: preflop + flop ──────────────────────────────────
  {
    id: 'p43-rush-cash-ako-spot',
    title: 'Rush & Cash — AKo in a Fast-Fold Environment',
    description: 'In Rush & Cash (fast-fold poker), should your strategy change with AKo?',
    difficulty: 'intermediate',
    category: 'Preflop',
    gameType: 'cash',
    format: 'Rush & Cash',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Ah', 'Kd'],
    effectiveStack: 100,
    stakes: '$0.50/$1 Rush',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Rush & Cash game. Action folds to BTN (hero) with AhKd. BB is a random player.',
        prompt: 'Rush & Cash: You have AKo on BTN. Open or fold?',
        options: [
          { id: 'raise',  label: 'Open to $3',    quality: 'perfect',    evLoss: 0,   coaching: 'Rush & Cash (fast-fold) is structurally similar to regular poker, just with faster rotation. AKo on the BTN is a clear open — no strategy change needed. Key Rush & Cash adaptation: players can fold and get new hands instantly, so they tend to fold more vs opens. Your AKo has even more fold equity here.' },
          { id: 'fold',   label: 'Fold',          quality: 'punt',       evLoss: 8,   coaching: 'Never fold AKo on the BTN in any format. This is a top-5 starting hand.' },
        ],
      },
      {
        street: 'flop',
        board: ['Ah', '7c', '2s'],
        context: 'BB defends. Pot $7. Flop: Ah 7c 2s. BB checks.',
        prompt: 'Flopped top pair top kicker on Ah 7c 2s in Rush & Cash. BB checks.',
        options: [
          { id: 'bet_50',  label: 'Bet $5 (71%)',  quality: 'perfect',    evLoss: 0,   coaching: 'In Rush & Cash, players tend to have tighter ranges (they can fold and get a new hand easily, so they play stronger hands). On a dry A-high board, bet for value — BB who defended will often have pairs and draws that call. Medium bet is appropriate.' },
          { id: 'check',   label: 'Check',          quality: 'good',       evLoss: 0.5, coaching: 'Checking is fine. In Rush & Cash BB tendencies are often to check-fold on dry boards, so betting may be more profitable. But checking is a reasonable range balance play.' },
          { id: 'overbet', label: 'Overbet $9',     quality: 'acceptable', evLoss: 1.5, coaching: 'Overbetting on this specific board may fold out too much. Rush & Cash players often fold more, so you want to find a size that keeps weaker hands in.' },
        ],
      },
    ],
    summary: 'Rush & Cash strategy doesn\'t fundamentally change — you still play premium hands normally. The key adaptation: in fast-fold games, players fold more preflop (they get new hands instantly), giving you more fold equity with your opens. AKo plays the same as in regular poker.',
    tags: ['preflop', 'Rush & Cash', 'AKo', 'fast-fold', 'BTN', 'format variant'],
  },

  // ── p44 ── MULTI-STREET: preflop + flop ──────────────────────────────────
  {
    id: 'p44-q9s-bb-defend-flop-cr',
    title: 'BB Defends Q9s — Check-Raise Opportunity on the Flop',
    description: 'You defend Q9s from BB vs CO open. You flop top pair and face a cbet. Flat or check-raise?',
    difficulty: 'intermediate',
    category: 'Check-Raise',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'BB',
    villainPosition: 'CO',
    heroCards: ['Qh', '9h'],
    effectiveStack: 100,
    stakes: '$1/$2',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens to $5. SB folds. BB (hero) with QhQh.',
        prompt: 'CO opens $5. You have Q9s in the BB. Call or fold?',
        options: [
          { id: 'call',  label: 'Call $3',        quality: 'perfect',    evLoss: 0,   coaching: 'Q9s is a standard BB defend vs CO. You\'re getting 2.5:1 pot odds with a hand that can flop well — top pair, flush draws, straight draws. Q9s is clearly in your BB defending range.' },
          { id: 'fold',  label: 'Fold',           quality: 'mistake',    evLoss: 2,   coaching: 'Folding Q9s in the BB vs CO is too tight. At 2.5:1 pot odds with a playable hand, you should always be defending here.' },
        ],
      },
      {
        street: 'flop',
        board: ['Qd', '7c', '3h'],
        context: 'Pot $11. Flop: Qd 7c 3h (rainbow). CO bets $7.',
        prompt: 'You flopped top pair (Q9) on Qd 7c 3h. CO bets $7. Call or check-raise?',
        options: [
          { id: 'raise',  label: 'Check-raise to $22',  quality: 'perfect',    evLoss: 0,   coaching: 'Check-raising top pair on this dry board is the optimal line. You have position to build the pot, and CO\'s cbet range is wide and bluff-heavy on Q73r. Raising protects your hand, gets value from Qx, and folds out hands that might catch free cards.' },
          { id: 'call',   label: 'Call $7',              quality: 'good',       evLoss: 0.5, coaching: 'Calling is fine — you keep CO\'s range wide and float in position. However, check-raising is slightly better as it builds the pot when you\'re ahead and gives you initiative on future streets.' },
          { id: 'fold',   label: 'Fold',                 quality: 'punt',       evLoss: 12,  coaching: 'Folding top pair to a small cbet is a major punt. You have top pair with a good kicker. Never fold this.' },
        ],
      },
    ],
    summary: 'Q9s is a standard BB defend. On boards where you flop top pair OOP, check-raising is often better than calling — it builds the pot when you\'re ahead, denies equity to draws, and forces villain to play for stacks on favorable runouts.',
    tags: ['preflop', 'BB defense', 'Q9s', 'check-raise', 'flop', 'top pair'],
  },

  // ── p45 ── MULTI-STREET: preflop + flop ──────────────────────────────────
  {
    id: 'p45-ato-co-vs-btn-4bet',
    title: 'ATo CO vs BTN 4-Bet — Preflop Decision Tree',
    description: 'You 3-bet ATo from CO vs BTN open and face a 4-bet. Call, 5-bet jam, or fold?',
    difficulty: 'advanced',
    category: 'Preflop',
    gameType: 'cash',
    format: '6-max',
    heroPosition: 'CO',
    villainPosition: 'BTN',
    heroCards: ['Ac', 'To'],
    effectiveStack: 100,
    stakes: '$2/$5',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'BTN opens to $15. CO 3-bets to $45. BTN 4-bets to $100.',
        prompt: 'You 3-bet ATo from CO and BTN 4-bets to $100. Call, jam, or fold?',
        options: [
          { id: 'fold',  label: 'Fold',           quality: 'perfect',    evLoss: 0,   coaching: 'Folding ATo vs a 4-bet is correct. ATo is a 3-bet bluff — when you use it to 3-bet (for fold equity), you fold vs a 4-bet. BTN\'s 4-bet range is strong (QQ+, AK, sometimes JJ/AQs). ATo is dominated by much of this range. Take the loss on the 3-bet and fold.' },
          { id: 'call',  label: 'Call $55',        quality: 'mistake',    evLoss: 3,   coaching: 'Calling a 4-bet OOP with ATo puts 100BB in with a hand that\'s dominated vs most 4-bet ranges. You\'re playing a huge pot OOP with low equity. Fold and move on.' },
          { id: 'jam',   label: '5-bet jam',       quality: 'mistake',    evLoss: 4,   coaching: '5-bet jamming ATo as a bluff vs a 4-bet faces an extremely tight range. You\'re putting in 100BB as a near-dead bluff — BTN rarely folds to 5-bets. This play loses significant EV.' },
        ],
      },
      {
        street: 'flop',
        board: ['Ad', '6h', '2c'],
        context: 'Alternative line: You called the 4-bet with ATo (OOP). Pot ~$205. Flop: Ad 6h 2c. Hero checks.',
        prompt: 'If you called the 4-bet, you flopped top pair on Ad 6h 2c. What is your line?',
        options: [
          { id: 'check_call', label: 'Check-call a bet',    quality: 'perfect',    evLoss: 0,   coaching: 'In the 4-bet pot (if you called), check-call top pair. BTN\'s 4-bet range has many AK, AA, KK hands — your ATo has good equity vs AK but is crushed by AA and KK. Check-call to keep pot manageable and see the turn.' },
          { id: 'check_fold', label: 'Check-fold to a bet', quality: 'mistake',    evLoss: 3,   coaching: 'Check-folding top pair in a 4-bet pot is too weak. You have TPTK — at least call one bet. Note: the correct preflop play is folding ATo to the 4-bet; this scenario shows why calling was problematic.' },
        ],
      },
    ],
    summary: 'When you 3-bet as a bluff and face a 4-bet, your plan is simple: fold. 3-bet bluffs like ATo build range balance and generate fold equity, but you abandon the investment when 4-bet. Calling or jamming with ATo vs a 4-bet loses significant EV — stick to the plan.',
    tags: ['preflop', 'CO', 'ATo', '3-bet bluff', '4-bet', 'fold to 4bet'],
  },
]
