import type { Puzzle } from '../puzzle-types'

export const PUZZLES_TOURNAMENT: Puzzle[] = [
  // ── MTT Push/Fold & ICM ──────────────────────────────────────────────────

  {
    id: 'p86',
    title: 'MTT Bubble Push/Fold — Short Stack',
    description: 'You have 10BB on the money bubble in an MTT. Should you push or fold?',
    difficulty: 'beginner',
    category: 'Push/Fold',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Ah', '7d'],
    effectiveStack: 10,
    stakes: 'MTT $100 buy-in',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: '10BB stack on the money bubble. Folds to you on BTN. SB folds. BB has 50BB (covers you).',
        prompt: 'A7o on BTN with 10BB on bubble. Shove or fold?',
        options: [
          { id: 'shove', label: 'Shove all-in (10BB)', quality: 'perfect', evLoss: 0, coaching: 'A7o is a clear shove from BTN with 10BB even on the bubble. Your hand has 45%+ equity vs any call. Folding gives up too much equity — at 10BB you must play for chips.' },
          { id: 'fold', label: 'Fold (bubble pressure)', quality: 'mistake', evLoss: 2.5, coaching: 'Folding A7o with 10BB is too tight even on the bubble. Your equity is too high and your stack is too short to wait for better spots.' },
          { id: 'limp', label: 'Limp (see cheap flop)', quality: 'punt', evLoss: 3.0, coaching: 'Limping with 10BB is almost never correct in MTTs. You give up fold equity and the option to apply pressure.' },
        ],
      },
    ],
    summary: 'At 10BB in MTTs, use a push/fold strategy. A7o on BTN is a clear shove — fold equity plus hand equity makes this strongly profitable.',
    tags: ['push/fold', 'MTT', 'bubble', 'short stack', '10BB'],
  },

  {
    id: 'p87',
    title: 'ICM Bubble Spot — Top 3 Gets Paid',
    description: 'You hold a medium stack near the bubble. ICM heavily penalises busting vs a big stack.',
    difficulty: 'advanced',
    category: 'ICM',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Qh', 'Jd'],
    effectiveStack: 25,
    stakes: 'MTT $200 buy-in — 4 left, top 3 paid',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: '4 players left, top 3 paid. You have 25BB in BB. Chip leader (100BB) shoves BTN.',
        prompt: 'QJo vs chip leader shove. ICM considerations change this drastically.',
        options: [
          { id: 'fold', label: 'Fold (ICM fold)', quality: 'perfect', evLoss: 0, coaching: 'With only 1 player from the money, folding QJo vs a chip leader shove is correct by ICM. You lose massive $EV busting to the chip leader — your equity is worth more than the risk here.' },
          { id: 'call', label: 'Call (chip EV positive)', quality: 'mistake', evLoss: 3.5, coaching: 'While QJo has decent chip EV, ICM severely punishes losing here. You drop from 3rd in chips to out with nothing. The $EV of folding and waiting is much higher.' },
        ],
      },
    ],
    summary: 'ICM forces tighter decisions near the bubble. Folding medium-strength hands vs big stack shoves preserves your $EV — chip EV and $EV diverge significantly here.',
    tags: ['ICM', 'MTT', 'bubble', 'QJo', 'fold'],
  },

  {
    id: 'p88',
    title: 'MTT Final Table — Short Stack Steal',
    description: 'Final table, 6 left. Short stack with 8BB — identify steal opportunities.',
    difficulty: 'intermediate',
    category: 'Push/Fold',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'CO',
    villainPosition: 'BTN+BB',
    heroCards: ['Kc', '5d'],
    effectiveStack: 8,
    stakes: 'MTT $500 buy-in — Final table 6 left',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: '6 players, final table. You have 8BB in CO. UTG folds, MP folds, action on you.',
        prompt: 'K5o in CO with 8BB at the final table. Shove or fold?',
        options: [
          { id: 'shove', label: 'Shove 8BB', quality: 'perfect', evLoss: 0, coaching: 'K5o is a profitable shove from CO with 8BB. The fold equity from 3 players still to act plus your hand equity makes this a clear push. Waiting is too costly at 8BB.' },
          { id: 'fold', label: 'Fold (wait for better)', quality: 'mistake', evLoss: 1.8, coaching: 'Folding K5o with 8BB is too passive. You need to apply pressure while you have any fold equity. At 6-7BB it gets worse.' },
          { id: 'raise3', label: 'Open to 2BB (non-commit)', quality: 'punt', evLoss: 3.0, coaching: 'Non-all-in raises with <15BB in MTTs are almost always mistakes. You commit chips without forcing an all-in decision from opponents.' },
        ],
      },
    ],
    summary: 'At 8BB in MTTs, use push/fold. K5o is a profitable shove from CO. Waiting makes your stack worse and gives opponents free hands to accumulate chips.',
    tags: ['push/fold', 'MTT', 'final table', 'short stack', 'CO'],
  },

  {
    id: 'p89',
    title: 'ICM Final Table — Big Stack Restraint',
    description: 'You are the chip leader at the final table. ICM pressures you to avoid risky spots.',
    difficulty: 'advanced',
    category: 'ICM',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Ad', 'Jc'],
    effectiveStack: 80,
    stakes: 'MTT $1000 — Final table 5 left',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Final table 5 players. You are chip leader (80BB). 2nd stack (60BB) 3-bets your BTN open to 18BB from BB. You opened AJo to 2.5BB.',
        prompt: 'AJo facing a 3-bet from a large stack. ICM says you should be careful. 4-bet or fold?',
        options: [
          { id: 'fold', label: 'Fold (ICM restraint)', quality: 'perfect', evLoss: 0, coaching: 'Against a large stack 3-bet at the final table, AJo is a fold by ICM. The 3-bet range from a large stack is strong (QQ+, AK, AQ). Your chip lead is valuable — preserve it by folding marginal hands.' },
          { id: 'call', label: 'Call (see flop)', quality: 'acceptable', evLoss: 0.8, coaching: 'Calling is better than 4-betting but still commits chips vs a polarised 3-bet range. ICM favours folding the toughest spots even with good hands.' },
          { id: '4bet', label: '4-bet (chip EV play)', quality: 'mistake', evLoss: 2.5, coaching: 'AJo is dominated by the 3-bet range here (AK, AQ beat you). Committing your chip lead on AJo is an ICM mistake at the final table.' },
        ],
      },
    ],
    summary: 'As a chip leader at the final table, avoid coin-flip situations. ICM amplifies the cost of losing chips — fold marginal spots and let short stacks bust each other.',
    tags: ['ICM', 'final table', 'chip leader', 'AJo', 'fold'],
  },

  {
    id: 'p90',
    title: 'MTT Early Stage Multiway Squeeze',
    description: 'Early in an MTT with 60BB. CO limps, BTN limps. You have a squeezing hand from SB.',
    difficulty: 'intermediate',
    category: 'Squeeze',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'SB',
    villainPosition: 'CO+BTN+BB',
    heroCards: ['As', 'Qs'],
    effectiveStack: 60,
    stakes: 'MTT $100 — Early stage',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO limps, BTN limps. You are SB with 60BB. BB behind you.',
        prompt: 'AQs in SB with 2 limpers. Squeeze, complete, or raise to isolate?',
        options: [
          { id: 'raise4x', label: 'Raise to 5BB (squeeze/isolate)', quality: 'perfect', evLoss: 0, coaching: 'AQs is too strong to limp behind. Raise to 5BB to isolate and build a pot in position (relative to limpers). You dominate all limping ranges and set up a strong c-bet board.' },
          { id: 'complete', label: 'Complete (small investment)', quality: 'mistake', evLoss: 1.5, coaching: 'Completing with AQs is a big mistake. You play a 4-way pot OOP with a premium hand. Raise and take control.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 4.0, coaching: 'Folding AQs in a limped pot as SB is very wrong. You have a premium hand — raise or complete, never fold.' },
        ],
      },
    ],
    summary: 'In MTTs early stages, isolate limpers with premium hands by raising 3-5x. Don\'t complete or fold — build the pot and set up a strong post-flop line.',
    tags: ['MTT', 'squeeze', 'AQs', 'SB', 'isolate'],
  },

  {
    id: 'p91',
    title: 'MTT Mid-Stage 3-bet Defense',
    description: 'You open CO, BTN 3-bets. 30BB effective — call, 4-bet shove, or fold?',
    difficulty: 'intermediate',
    category: '3-bet Pot',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'CO',
    villainPosition: 'BTN',
    heroCards: ['Jd', 'Jc'],
    effectiveStack: 30,
    stakes: 'MTT $200 — Mid-stage',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens to 2.2BB, BTN 3-bets to 6.5BB. 30BB effective. Folds back to you.',
        prompt: 'JJ facing 3-bet with 30BB effective. Call, 4-bet shove, or fold?',
        options: [
          { id: '4betshove', label: '4-bet shove all-in (30BB)', quality: 'perfect', evLoss: 0, coaching: 'JJ is a mandatory 4-bet shove with 30BB effective. You have enough equity vs any 3-bet range (AA/KK/QQ/AK+). SPR is too low to play post-flop — get it in now.' },
          { id: 'call', label: 'Call (see flop)', quality: 'acceptable', evLoss: 0.8, coaching: 'Calling is fine but you face terrible SPR spots with JJ OOP. 4-bet shoving is simpler and higher EV.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 8.0, coaching: 'Folding JJ for 30BB is a massive error. You are ahead of all but 2 hands in villain\'s 3-bet range.' },
        ],
      },
    ],
    summary: 'With 20-35BB effective and JJ+, always 4-bet shove vs 3-bets. The SPR is too low for post-flop play and your equity is too good to fold.',
    tags: ['MTT', 'JJ', '4-bet shove', 'mid-stage', 'CO'],
  },

  {
    id: 'p92',
    title: 'MTT Resteal Opportunity',
    description: 'Tight player opens from CO, you have 15BB in BB. When is a resteal profitable?',
    difficulty: 'intermediate',
    category: 'Resteal',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'BB',
    villainPosition: 'CO',
    heroCards: ['Kh', '8s'],
    effectiveStack: 15,
    stakes: 'MTT $100 — Late stage',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'UTG folds, MP folds, CO (tight player, 45BB) opens to 2.5BB. BTN folds, SB folds. You are in BB with K8o, 15BB.',
        prompt: 'K8o in BB vs tight CO open with 15BB. 3-bet shove or fold?',
        options: [
          { id: 'shove', label: '3-bet shove 15BB', quality: 'perfect', evLoss: 0, coaching: 'K8o is a good resteal vs a tight CO opener with 15BB. A tight CO opens ~15% range. Your K8o has 40%+ equity vs their folding range, and they fold wide enough to show an immediate profit even without the equity.' },
          { id: 'fold', label: 'Fold', quality: 'acceptable', evLoss: 0.9, coaching: 'Folding is safe vs a tight player but K8o has enough equity for a profitable resteal here. The fold equity combined with your hand equity makes shoving +EV.' },
          { id: 'call', label: 'Call (see cheap flop)', quality: 'mistake', evLoss: 1.5, coaching: 'Calling with 15BB OOP is the worst option — you play OOP with a committed stack but no fold equity. Either shove or fold.' },
        ],
      },
    ],
    summary: 'Resteals are profitable when you have fold equity (15-25BB range) and a hand with decent equity vs calling ranges. K8o qualifies as a resteal vs tight openers.',
    tags: ['resteal', 'MTT', 'late stage', 'K8o', 'BB'],
  },

  {
    id: 'p93',
    title: 'MTT Steal vs Antes — Wider Range',
    description: 'With antes in play, the pot is larger. This expands your stealing range considerably.',
    difficulty: 'beginner',
    category: 'Steal',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'BTN',
    villainPosition: 'SB+BB',
    heroCards: ['Qc', '7h'],
    effectiveStack: 20,
    stakes: 'MTT $100 — Antes in play',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Antes in play. Pot already 2.2BB before action. Folds to you on BTN with 20BB.',
        prompt: 'Q7o on BTN with 20BB. Antes make stealing more profitable. Open steal?',
        options: [
          { id: 'raise25', label: 'Open to 2.2BB (steal)', quality: 'perfect', evLoss: 0, coaching: 'With antes, the pot is 2.2BB before action — stealing gives you better RFE (required fold equity). Q7o on BTN with 20BB is a profitable steal. The antes significantly expand your BTN stealing range.' },
          { id: 'fold', label: 'Fold (weak hand)', quality: 'mistake', evLoss: 1.2, coaching: 'Folding Q7o on BTN with antes is too tight. The pot odds and fold equity justify a steal attempt here. Q7o has decent blockers and reasonable equity.' },
          { id: 'shove', label: 'Shove all-in (20BB)', quality: 'acceptable', evLoss: 0.4, coaching: 'Shoving is also fine with 20BB — sometimes simpler. But a min-raise steal risks fewer chips and can still fold out SB/BB.' },
        ],
      },
    ],
    summary: 'With antes, the increased pot makes stealing more profitable. Expand your BTN stealing range significantly — antes change the mathematics of steal plays.',
    tags: ['steal', 'MTT', 'antes', 'BTN', 'beginner'],
  },

  // ── Spin & Go ────────────────────────────────────────────────────────────

  {
    id: 'p94',
    title: 'Spin & Go — 3-Handed Push/Fold',
    description: 'In a Spin & Go with 15BB effective, correct push/fold ranges differ from MTTs.',
    difficulty: 'intermediate',
    category: 'Push/Fold',
    gameType: 'tournament',
    format: 'Spin & Go',
    heroPosition: 'BTN',
    villainPosition: 'SB+BB',
    heroCards: ['7h', '7c'],
    effectiveStack: 15,
    stakes: 'Spin & Go $10',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: '3-handed Spin & Go. 15BB effective. Folds to you on BTN/CO.',
        prompt: '77 with 15BB 3-handed in Spin & Go. Push or raise smaller?',
        options: [
          { id: 'shove', label: 'Shove all-in (15BB)', quality: 'perfect', evLoss: 0, coaching: '77 is a mandatory shove in 3-handed play with 15BB. Your hand equity is strong vs any 2 cards, and fold equity is significant. 3-handed ranges are wider — your 77 is a dominating hand.' },
          { id: 'raise25', label: 'Raise to 2.5BB', quality: 'acceptable', evLoss: 0.6, coaching: 'Min-raising is playable but you play post-flop without fold equity. With 15BB effective, shoving is simpler and higher EV.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 5.0, coaching: 'Folding 77 in 3-handed play is a serious mistake. You have a premium hand for push/fold ranges.' },
        ],
      },
    ],
    summary: 'In 3-handed Spin & Go play, push/fold ranges are much wider. Any pair is a shove from the BTN with 12-18BB stacks.',
    tags: ['Spin & Go', 'push/fold', '3-handed', '77', 'BTN'],
  },

  {
    id: 'p95',
    title: 'Spin & Go Heads-Up — 20BB',
    description: 'Heads-up in a Spin & Go. The game is almost entirely push/fold at 20BB.',
    difficulty: 'intermediate',
    category: 'Push/Fold',
    gameType: 'tournament',
    format: 'Spin & Go',
    heroPosition: 'SB',
    villainPosition: 'BB',
    heroCards: ['Th', '4s'],
    effectiveStack: 20,
    stakes: 'Spin & Go $25 — Heads-Up',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Heads-up Spin & Go. 20BB effective. You are SB (BTN). T4o in hand.',
        prompt: 'T4o heads-up with 20BB as SB. Shove or fold?',
        options: [
          { id: 'shove', label: 'Shove 20BB', quality: 'perfect', evLoss: 0, coaching: 'Heads-up with 20BB, T4o is a shove. Heads-up push/fold ranges with 20BB include all Tx+, and T4o passes that threshold. The SB/BTN shoving range at 20BB HU is roughly 70%+ of hands.' },
          { id: 'fold', label: 'Fold', quality: 'mistake', evLoss: 1.5, coaching: 'Folding T4o heads-up with 20BB is too tight. HU ranges are much wider — you should be shoving all Tx and many lower hands.' },
          { id: 'limp', label: 'Limp (see flop)', quality: 'acceptable', evLoss: 0.5, coaching: 'Limping HU is a valid strategy at some stack depths, but with 20BB you should use a push/fold strategy for simplicity and fold equity.' },
        ],
      },
    ],
    summary: 'Heads-up with 20BB in a Spin & Go, use aggressive push/fold. T4o easily qualifies — HU shoving ranges at this depth are 60-70%+ of hands.',
    tags: ['Spin & Go', 'heads-up', 'push/fold', 'T4o', '20BB'],
  },

  // ── PKO ──────────────────────────────────────────────────────────────────

  {
    id: 'p96',
    title: 'PKO — Calling for a Bounty',
    description: 'Progressive Knockout: villain has a big bounty. How much wider should you call?',
    difficulty: 'intermediate',
    category: 'PKO',
    gameType: 'tournament',
    format: 'PKO MTT',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Kd', '7s',],
    effectiveStack: 20,
    stakes: 'PKO MTT $100 — Villain\'s bounty is worth 40% of buy-in',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'BTN shoves 20BB. Villain has a $40 bounty (buy-in is $100). You have K7o in BB.',
        prompt: 'K7o facing a 20BB shove with a $40 bounty at stake. Normal ICM says fold. PKO says?',
        options: [
          { id: 'call', label: 'Call (bounty equity)', quality: 'perfect', evLoss: 0, coaching: 'The $40 bounty (40% of buy-in) dramatically changes the math. K7o has ~40% equity heads-up. Adding bounty equity makes this a clear call that would be a fold in a normal MTT.' },
          { id: 'fold', label: 'Fold (standard ICM)', quality: 'mistake', evLoss: 2.5, coaching: 'Applying standard MTT ICM to PKO is a mistake. The bounty is real money — you must widen your calling range significantly when large bounties are at stake.' },
        ],
      },
    ],
    summary: 'In PKO tournaments, bounties are real money EV. Widen your calling ranges significantly when large bounties are at stake — K7o vs a 20BB shove is a call.',
    tags: ['PKO', 'bounty', 'call', 'ICM', 'K7o'],
  },

  {
    id: 'p97',
    title: 'PKO — Shoving for Your Own Bounty',
    description: 'As a big stack in PKO, your own bounty makes opponents call wider. Adjust accordingly.',
    difficulty: 'advanced',
    category: 'PKO',
    gameType: 'tournament',
    format: 'PKO MTT',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Qc', 'Jd'],
    effectiveStack: 15,
    stakes: 'PKO MTT $200 — You have a $60 bounty on your head',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'You have a $60 bounty (your stack has grown from prior eliminations). 15BB stack, BTN, folds to you. BB has 35BB.',
        prompt: 'QJo shove with 15BB when you have a big bounty on your head. Adjust range?',
        options: [
          { id: 'shove', label: 'Shove (still correct)', quality: 'perfect', evLoss: 0, coaching: 'QJo is still a shove with 15BB despite your bounty. Your hand equity is strong enough. Remember: opponent calling wider due to your bounty means your fold equity decreases, but QJo has enough raw equity to still be a shove.' },
          { id: 'fold', label: 'Fold (opponents call wider)', quality: 'mistake', evLoss: 1.8, coaching: 'Folding QJo with 15BB because opponents call wider is incorrect. QJo is too strong to fold — it has enough equity even vs wider calling ranges.' },
          { id: 'raise25', label: 'Raise smaller (2.5BB)', quality: 'mistake', evLoss: 2.0, coaching: 'Raising small with 15BB is non-committing and gives opponents a chance to 3-bet shove you off the hand. Either fold or shove at this depth.' },
        ],
      },
    ],
    summary: 'In PKO, having a large bounty on your head means opponents call wider, so tighten your shoving range slightly. But QJo with 15BB is still a profitable shove.',
    tags: ['PKO', 'bounty', 'shove', 'QJo', 'BTN'],
  },

  // ── Satellite ────────────────────────────────────────────────────────────

  {
    id: 'p98',
    title: 'Satellite — Survival vs Chip Accumulation',
    description: 'In a satellite tournament (winner-takes-all seats), survival is the only goal.',
    difficulty: 'intermediate',
    category: 'ICM',
    gameType: 'tournament',
    format: 'Satellite',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['Ah', 'Ks'],
    effectiveStack: 30,
    stakes: 'Satellite to $10k Main Event — 8 seats paid',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: '10 players left, 8 seats paid. You have 30BB. Short stack (15BB) shoves from CO. BTN (40BB) calls. Action on you in BB.',
        prompt: 'AKs in BB, short stack shoved, BTN called. Do you call to win chips or fold to secure a seat?',
        options: [
          { id: 'fold', label: 'Fold (satellite strategy)', quality: 'perfect', evLoss: 0, coaching: 'In a satellite, 1st and 8th place are worth the same. With 10 players and 8 seats, you already have a very high probability of winning a seat. Putting your stack at risk with AKs against TWO opponents (even with +EV chip play) risks elimination for no additional reward.' },
          { id: 'call', label: 'Call (AKs is huge)', quality: 'mistake', evLoss: 5.0, coaching: 'In normal poker AKs is a mandatory call. In satellites near the money, chip EV and prize EV completely diverge. You already almost certainly have a seat — risking it for chips you don\'t need is wrong.' },
        ],
      },
    ],
    summary: 'In satellites, survival is everything — all seats have equal value. Fold +chip EV situations when you\'re near the money, even with premium hands.',
    tags: ['satellite', 'ICM', 'fold', 'AKs', 'survival'],
  },

  // ── MTT Postflop ─────────────────────────────────────────────────────────

  {
    id: 'p99',
    title: 'MTT — Steal Then C-bet',
    description: 'You steal from CO, BB calls. Navigate the flop with your steal hand.',
    difficulty: 'intermediate',
    category: 'C-bet',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'CO',
    villainPosition: 'BB',
    heroCards: ['Ks', '9c'],
    effectiveStack: 30,
    stakes: 'MTT $100 — 30BB effective',
    steps: [
      {
        street: 'flop',
        board: ['Kd', '7h', '3c'],
        context: 'CO opens 2.2BB (with antes, pot = 3.7BB), BB defends. Flop K73r. BB checks.',
        prompt: 'K9 on K73r after stealing from CO. BB checked. C-bet?',
        options: [
          { id: 'bet33', label: 'Bet 33% pot (1.2BB)', quality: 'perfect', evLoss: 0, coaching: 'Small c-bet on K73r with top pair is perfect. In MTTs with 30BB, the pot is already large relative to stacks. A small c-bet extracts value without over-committing.' },
          { id: 'check', label: 'Check (pot control)', quality: 'acceptable', evLoss: 0.5, coaching: 'Checking TPTK in MTTs is fine for pot control given shorter stacks. But a small c-bet extracts value from draws and underpairs.' },
          { id: 'bet75', label: 'Bet 75% pot (2.75BB)', quality: 'mistake', evLoss: 1.0, coaching: 'Large c-bet on a dry board over-commits. Use small sizing in MTTs — every chip matters.' },
        ],
      },
    ],
    summary: 'In MTTs, small c-bets on dry boards are efficient. Chips are valuable — extract value with small risks rather than large commitments.',
    tags: ['MTT', 'c-bet', 'steal', 'CO', 'TPTK'],
  },

  {
    id: 'p100',
    title: 'MTT Final Table Hero Call',
    description: 'Final table, villain represents a missed draw. Do you make the hero call for a chip lead?',
    difficulty: 'expert',
    category: 'Hero Call',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Qd', 'Qh',],
    effectiveStack: 50,
    stakes: 'MTT $1000 — Final table 3 left',
    steps: [
      {
        street: 'river',
        board: ['Jc', '9d', '4h', '2s', '6s'],
        context: 'BTN opens, BB 3-bets QQ to 9BB. BTN calls. Flop J94: you c-bet, BTN calls. Turn 2: you check, BTN checks. River 6s. You check, BTN jams all-in (50BB into 40BB pot).',
        prompt: 'QQ as an overpair on J9426. BTN jams river. Hero call to take the chip lead, or fold?',
        options: [
          { id: 'call', label: 'Call (read the line)', quality: 'perfect', evLoss: 0, coaching: 'Analyse BTN\'s line: called a 3-bet pre, called a c-bet on J-high board, checked back the turn (weak signal), then jammed the river. This represents a missed draw (T8, KT, QT, or 87) or a medium pair bluffing. QQ beats all missed draws. Call.' },
          { id: 'fold', label: 'Fold (ICM caution)', quality: 'mistake', evLoss: 8.0, coaching: 'While ICM caution is real, folding QQ on J9426 to a river jam after this specific line is too tight. The line screams missed draw. QQ is good far too often here.' },
        ],
      },
    ],
    summary: 'At final tables, read the line carefully before applying ICM. When the line strongly indicates a missed draw, hero calls with overpairs are correct even with ICM pressure.',
    tags: ['MTT', 'hero call', 'QQ', 'final table', 'expert'],
  },

  // ── Rush & Cash ──────────────────────────────────────────────────────────

  {
    id: 'p101',
    title: 'Rush & Cash — Postflop with Loose Ranges',
    description: 'In Rush & Cash, players jump tables constantly — expect wider ranges and more bluffs.',
    difficulty: 'intermediate',
    category: 'Bluff Catch',
    gameType: 'cash',
    format: 'Rush & Cash',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['Ac', 'Jh'],
    effectiveStack: 100,
    stakes: '$1/$2 Rush & Cash',
    steps: [
      {
        street: 'river',
        board: ['Ah', '9d', '4c', '3s', '8h'],
        context: 'BTN opens, BB defends. You check-called flop and turn. River 8h. BTN fires large (80% pot).',
        prompt: 'AJ (TPTK) on A9438 vs large river bet. Rush & Cash dynamics — call or fold?',
        options: [
          { id: 'call', label: 'Call (Rush & Cash: more bluffs)', quality: 'perfect', evLoss: 0, coaching: 'In Rush & Cash, players fold pre-flop quickly to get new hands — but when they do play, ranges can be wider and bluff frequencies higher. TPTK on this non-threatening board is a clear call.' },
          { id: 'fold', label: 'Fold (respect large bet)', quality: 'mistake', evLoss: 3.5, coaching: 'Folding TPTK for 80% pot on A9438 is too tight even vs large bets. Villain\'s range includes many missed draws on this run-out.' },
          { id: 'raise', label: 'Raise (turn it into a bluff)', quality: 'mistake', evLoss: 5.0, coaching: 'Raising TPTK on the river is a thin line. Just call for value.' },
        ],
      },
    ],
    summary: 'In Rush & Cash, maintain fundamental poker strategy. TPTK is a clear call on non-threatening runouts regardless of fast-fold format.',
    tags: ['Rush & Cash', 'bluff catch', 'AJ', 'river', 'BB'],
  },

  {
    id: 'p102',
    title: 'Rush & Cash — Quick Steal Attempt',
    description: 'In Rush & Cash, players tend to fold more often pre-flop. Steal ranges can expand.',
    difficulty: 'beginner',
    category: 'Steal',
    gameType: 'cash',
    format: 'Rush & Cash',
    heroPosition: 'BTN',
    villainPosition: 'SB+BB',
    heroCards: ['9c', '6d',],
    effectiveStack: 100,
    stakes: '$0.50/$1 Rush & Cash',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Rush & Cash, folds to BTN. SB and BB are both players who just joined the table.',
        prompt: '96o on BTN in Rush & Cash. Open or fold?',
        options: [
          { id: 'raise25', label: 'Open to 2.5BB (exploit wider folds)', quality: 'perfect', evLoss: 0, coaching: 'In Rush & Cash, players fold pre-flop quickly to move to new tables. This increases fold equity for BTN steals. 96o is marginal but profitable in this format with the ante structure and wider folding tendencies.' },
          { id: 'fold', label: 'Fold (weak hand)', quality: 'acceptable', evLoss: 0.4, coaching: 'Folding is fine — 96o is genuinely weak. But in Rush & Cash the steal is slightly more profitable than normal due to the fast-fold dynamics.' },
        ],
      },
    ],
    summary: 'Rush & Cash players fold slightly more to steals due to the fast-fold mechanic. Marginally expand BTN ranges to exploit this, though not excessively.',
    tags: ['Rush & Cash', 'steal', 'BTN', '96o', 'beginner'],
  },

  // ── Short Deck ───────────────────────────────────────────────────────────

  {
    id: 'p103',
    title: 'Short Deck — Hand Rankings Change',
    description: 'In Short Deck (6+), flushes beat full houses. A set is no longer safe on a flush board.',
    difficulty: 'advanced',
    category: 'Short Deck',
    gameType: 'cash',
    format: 'Short Deck',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['9c', '9d'],
    effectiveStack: 50,
    stakes: 'Short Deck €/$5/$5',
    steps: [
      {
        street: 'river',
        board: ['9h', '7h', '6h', 'Ah', '5h'],
        context: 'BTN opens, BB calls. Pot ~12 units. Board runs out all hearts — 9h7h6hAh5h. BB jams river.',
        prompt: 'In Short Deck, flush beats full house. You have a set of 9s. BB jams. Is this a call?',
        options: [
          { id: 'fold', label: 'Fold (flush beats full house in Short Deck)', quality: 'perfect', evLoss: 0, coaching: 'Critical Short Deck rule: flushes beat full houses. On a 5-heart board (9h7h6hAh5h), your 99 gives you a full house (999-AA) but any heart in BB\'s hand makes a flush — and the flush WINS. Fold to a jam.' },
          { id: 'call', label: 'Call (full house is strong)', quality: 'punt', evLoss: 20.0, coaching: 'This is the classic Short Deck trap. Full houses feel strong from regular poker, but in Short Deck the hand rankings are flipped — flushes beat full houses. The jam represents a flush. Fold!' },
        ],
      },
    ],
    summary: 'Short Deck key rule: flush beats full house. Always verify hand rankings before calling large bets on monotone or near-monotone boards in Short Deck.',
    tags: ['Short Deck', 'hand rankings', 'flush', 'full house', 'fold'],
  },

  {
    id: 'p104',
    title: 'Short Deck — Preflop Ranges Shift',
    description: 'In Short Deck, pairs and connected hands gain value. How do preflop ranges change?',
    difficulty: 'intermediate',
    category: 'Short Deck',
    gameType: 'cash',
    format: 'Short Deck',
    heroPosition: 'BTN',
    villainPosition: 'BB',
    heroCards: ['9d', '8d'],
    effectiveStack: 50,
    stakes: 'Short Deck $5/$5',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Short Deck (6+ deck). BTN open or straddle position. 98d — connected suited hand.',
        prompt: 'In Short Deck, 98s is much stronger than in regular poker. Open or limp?',
        options: [
          { id: 'raise', label: 'Raise/open (strong in Short Deck)', quality: 'perfect', evLoss: 0, coaching: 'In Short Deck, connected hands like 98s are significantly stronger because the deck has fewer cards and straight/flush draws complete more often. 98s often opens/raises confidently in Short Deck.' },
          { id: 'fold', label: 'Fold (regular poker thinking)', quality: 'mistake', evLoss: 2.0, coaching: 'Applying regular poker thinking to Short Deck is a mistake. 98s is a premium hand in Short Deck — fold equity and draw equity are both higher due to the reduced deck.' },
          { id: 'limp', label: 'Limp (see cheap flop)', quality: 'acceptable', evLoss: 0.8, coaching: 'Limping is fine in Short Deck but not optimal. The hand is strong enough to raise for value.' },
        ],
      },
    ],
    summary: 'In Short Deck, connected suited hands like 98s are premium hands. The reduced deck means draws complete more frequently — adjust your hand valuations significantly.',
    tags: ['Short Deck', 'preflop', '98s', 'connected', 'suited'],
  },

  {
    id: 'p105',
    title: 'Short Deck — Set Equity vs Flush Draw',
    description: 'In Short Deck, flush draws have more outs (only 9 cards per suit in deck but fewer in play). Navigate a set vs flush draw spot.',
    difficulty: 'advanced',
    category: 'Short Deck',
    gameType: 'cash',
    format: 'Short Deck',
    heroPosition: 'CO',
    villainPosition: 'BB',
    heroCards: ['Jc', 'Jd'],
    effectiveStack: 50,
    stakes: 'Short Deck $5/$5',
    steps: [
      {
        street: 'flop',
        board: ['Jh', '9h', '6c'],
        context: 'CO opens, BB calls. Pot ~12 units. Flop Jh9h6c — you have top set. BB check-raises.',
        prompt: 'Top set JJ on Jh9h6c in Short Deck. BB check-raises. In Short Deck, flush draws hit more often. How do you respond?',
        options: [
          { id: '4betjam', label: '4-bet jam (set is dominant)', quality: 'perfect', evLoss: 0, coaching: 'In Short Deck, top set is still dominant vs flush draws even though flushes beat full houses. You currently have the best hand. Jam and get maximum equity in — if a flush comes you lose (it beats your boat), but you start with ~65% equity vs a combo draw.' },
          { id: 'call', label: 'Call (cautious on wet board)', quality: 'good', evLoss: 0.5, coaching: 'Calling is fine — you keep the pot controlled and can fold river if the board flushes. But getting it in as a 65% favourite is generally correct.' },
          { id: 'fold', label: 'Fold (scared of flush beats boat)', quality: 'punt', evLoss: 15.0, coaching: 'Folding top set to a check-raise is a catastrophic mistake. You are a 65% favourite even vs the flush draw, and the board hasn\'t completed yet.' },
        ],
      },
    ],
    summary: 'Even in Short Deck where flushes beat full houses, top set on the flop is a 65% favourite vs flush draws. Get the money in — you have the best hand now.',
    tags: ['Short Deck', 'set', 'flush draw', 'equity', 'flop'],
  },

  // ── Additional MTT & Format Spots ───────────────────────────────────────

  {
    id: 'p106',
    title: 'MTT Deep-Stack — 3-bet Pot Navigation',
    description: 'Deep-stacked MTT (100BB). 3-bet pot with AK — navigate the flop on a low card board.',
    difficulty: 'intermediate',
    category: '3-bet Pot',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'SB',
    villainPosition: 'BTN',
    heroCards: ['As', 'Kd'],
    effectiveStack: 100,
    stakes: 'MTT $200 — Deep stacks early stage',
    steps: [
      {
        street: 'flop',
        board: ['8c', '5s', '2h'],
        context: 'BTN opens, SB 3-bets to 9BB, BTN calls. Pot 19BB. You are OOP on 852r.',
        prompt: 'AK on 852r OOP in 3-bet pot, MTT. C-bet strategy?',
        options: [
          { id: 'bet33', label: 'Bet 33% pot (6.3BB)', quality: 'perfect', evLoss: 0, coaching: 'Small c-bet on 852r is the standard line in 3-bet pots. The board hits neither range hard. A small c-bet with AK (two overcards) pressures BTN\'s pairs and draws efficiently.' },
          { id: 'check', label: 'Check (pot control MTT)', quality: 'acceptable', evLoss: 0.7, coaching: 'Checking is fine — in MTTs you might prefer pot control. But AK is strong enough to c-bet small on this board.' },
          { id: 'bet75', label: 'Bet 75% pot (14.25BB)', quality: 'mistake', evLoss: 1.8, coaching: 'Large bet on 852r in an MTT over-commits chips. Small bets achieve the same fold equity at much lower risk.' },
        ],
      },
    ],
    summary: 'In MTT 3-bet pots, use small c-bets on dry boards. Every chip has tournament equity — avoid over-committing in marginal spots.',
    tags: ['MTT', '3-bet pot', 'AK', 'SB', 'deep stack'],
  },

  {
    id: 'p107',
    title: 'Spin & Go — All-in Pre with Pair',
    description: 'In a Spin & Go with 20BB, pairs are often all-in pre-flop situations.',
    difficulty: 'beginner',
    category: 'Push/Fold',
    gameType: 'tournament',
    format: 'Spin & Go',
    heroPosition: 'SB',
    villainPosition: 'BB',
    heroCards: ['5h', '5c'],
    effectiveStack: 20,
    stakes: 'Spin & Go $5 — Heads-Up',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Heads-up Spin & Go. 20BB. You are SB. 55 in hand.',
        prompt: 'Heads-up, 20BB, SB. 55. Shove or raise-call?',
        options: [
          { id: 'shove', label: 'Shove 20BB', quality: 'perfect', evLoss: 0, coaching: 'Any pair is a shove heads-up with 20BB. 55 has strong equity vs any Ax (65-70%) and pairs below 5-5 obviously. Get it in now.' },
          { id: 'raise25', label: 'Raise small and call shove', quality: 'good', evLoss: 0.3, coaching: 'Raising small and calling a shove is also fine — same result, slightly different line. Shoving directly is simpler.' },
          { id: 'fold', label: 'Fold', quality: 'punt', evLoss: 5.0, coaching: 'Folding a pair heads-up is almost always a mistake. Especially at 20BB.' },
        ],
      },
    ],
    summary: 'Heads-up with 20BB, any pair is a shove. The equity advantage of 55 vs random hands is too significant to pass up at these stack depths.',
    tags: ['Spin & Go', 'heads-up', 'pair', 'push/fold', 'SB'],
  },

  {
    id: 'p108',
    title: 'PKO — Middle Stage Stack Decision',
    description: 'Mid-stage PKO with a medium stack. You face a shove from a small stack with a medium bounty.',
    difficulty: 'intermediate',
    category: 'PKO',
    gameType: 'tournament',
    format: 'PKO MTT',
    heroPosition: 'BB',
    villainPosition: 'UTG',
    heroCards: ['Ah', '9c'],
    effectiveStack: 40,
    stakes: 'PKO MTT $200 — Villain bounty $30, your stack 40BB',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'UTG (12BB) shoves. Villain has a $30 bounty (15% of buy-in). You have A9o in BB with 40BB.',
        prompt: 'A9o vs 12BB shove with a $30 bounty. Standard play vs PKO consideration?',
        options: [
          { id: 'call', label: 'Call (A9 + bounty equity)', quality: 'perfect', evLoss: 0, coaching: 'A9o is a standard call vs a 12BB shove (you have 50%+ equity vs any range). Adding the $30 bounty makes this even more clear. The bounty provides additional EV on top of already positive chip equity.' },
          { id: 'fold', label: 'Fold (UTG range is strong)', quality: 'mistake', evLoss: 2.0, coaching: 'UTG 12BB shove range is wide (any A, any K, any pair, Qx+). You dominate most of this range with A9o. Add the bounty and this is a clear call.' },
        ],
      },
    ],
    summary: 'In PKO, combine chip equity with bounty equity for calling decisions. A9o vs a 12BB shove is +EV on chips alone; the bounty makes it even more clear.',
    tags: ['PKO', 'bounty', 'call', 'A9o', 'shove'],
  },

  {
    id: 'p109',
    title: 'MTT — River Check-Raise Bluff',
    description: 'You hold a bluff-catcher hand in an MTT final table. Set up a river check-raise bluff.',
    difficulty: 'expert',
    category: 'Bluff',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'BB',
    villainPosition: 'CO',
    heroCards: ['5d', '5h'],
    effectiveStack: 60,
    stakes: 'MTT $500 — Final table 7 left',
    steps: [
      {
        street: 'river',
        board: ['Kd', '9c', '4s', '3h', '2c'],
        context: 'CO opens, BB defends. Flop K94: you check-call. Turn 3h: you check-call. River 2c. CO bets 40% pot.',
        prompt: '55 on K9432 river. CO bets 40%. Check-raise bluff or call?',
        options: [
          { id: 'checkraise', label: 'Check-raise bluff (river CR)', quality: 'good', evLoss: 0.5, coaching: 'A river check-raise here represents a wheel (A5 for A-2-3-4-5 straight) or strong two pair. CO\'s 40% bet might be a thin value or bluff. The board is scary for CO\'s value range — a raise might fold KQ, KJ, 99.' },
          { id: 'call', label: 'Call (bluff catch)', quality: 'perfect', evLoss: 0, coaching: 'Calling is probably higher EV. 55 beats a lot of CO bluffs on this board (missed QJ, JT). Check-raising turns a bluff-catcher into a bluff at ICM risk. Call and show it down.' },
          { id: 'fold', label: 'Fold', quality: 'mistake', evLoss: 3.0, coaching: 'Folding 55 to a small river bet on K9432 is too tight. You beat all bluffs.' },
        ],
      },
    ],
    summary: 'At MTT final tables, calling with bluff-catchers is often safer than turning them into bluffs via check-raise. ICM amplifies the risk of being caught.',
    tags: ['MTT', 'bluff', 'river', 'ICM', 'final table'],
  },

  {
    id: 'p110',
    title: 'MTT — Deep Run AK vs 4-bet',
    description: 'Deep in a major MTT, you open AK and face a 4-bet. ICM changes the math.',
    difficulty: 'expert',
    category: 'ICM',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'CO',
    villainPosition: 'BB',
    heroCards: ['Ac', 'Kh'],
    effectiveStack: 40,
    stakes: 'MTT $1000 — 12 left, top 9 paid',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens AK to 2.2BB. BB 4-bets to 8.5BB. 40BB effective. 3 spots from the money.',
        prompt: 'AKo vs BB 4-bet. 3 from the money. 40BB effective. Call, 5-bet shove, or fold?',
        options: [
          { id: '5betshove', label: '5-bet shove (40BB)', quality: 'perfect', evLoss: 0, coaching: 'AKo vs a 4-bet with 40BB is a mandatory 5-bet shove. The 4-bet range is QQ+/AK. You are a coin-flip vs QQ/KK and a 70% favourite vs AK. ICM is tight but AK is too good to fold near the bubble at this effective stack.' },
          { id: 'call', label: 'Call (see flop, control pot)', quality: 'acceptable', evLoss: 1.0, coaching: 'Calling is fine for pot control — you play post-flop for 32BB effective. But given the stack depth, shoving is cleaner and captures more value.' },
          { id: 'fold', label: 'Fold (ICM pressure, 3 from money)', quality: 'mistake', evLoss: 4.0, coaching: 'Folding AKo for 40BB is wrong even 3 from the money. Your equity is too high vs the 4-bet range. ICM slightly tightens your range but not enough to fold AK here.' },
        ],
      },
    ],
    summary: 'AKo vs 4-bets with 40BB effective is a 5-bet shove even in ICM-heavy spots. The hand equity (coin-flip or better) outweighs ICM penalties except in extreme bubbles.',
    tags: ['MTT', 'AK', '4-bet', 'ICM', 'expert'],
  },
]
