import type { Puzzle } from '../puzzle-types'

export const PUZZLES_TOURNAMENT: Puzzle[] = [

  // ── tr1: MTT Early Stage — 3-bet OOP, miss flop, hit turn ───────────────
  {
    id: 'tr1-mtt-3bet-oop-navigation',
    title: 'MTT 3-bet OOP — Miss, Then Hit',
    description: 'Early MTT, SB 3-bets BTN. Miss the K-high flop, pick up top pair on the turn.',
    difficulty: 'intermediate',
    category: '3-bet Pot',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'SB',
    villainPosition: 'BTN',
    heroCards: ['Ah', 'Qs'],
    effectiveStack: 80,
    stakes: 'MTT $200 — Early stage, 80BB',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to BTN who opens 2.5BB. SB with AhQs, 80BB. BB behind you.',
        prompt: 'AQo in SB vs BTN open. Fold, call, or 3-bet?',
        options: [
          { id: 'fold',  label: 'Fold',             quality: 'mistake',    evLoss: 2.5, coaching: 'Folding AQo in SB vs a BTN open is too tight. AQ is a premium hand with position on the BB — 3-betting is correct.' },
          { id: 'call',  label: 'Call (flat SB)',    quality: 'acceptable', evLoss: 0.6, coaching: 'Calling keeps the pot small but you play OOP vs the pre-flop aggressor. 3-betting is a stronger line with AQ from the SB.' },
          { id: '3bet',  label: '3-bet to 8BB',      quality: 'perfect',    evLoss: 0,   coaching: 'AQo is a strong 3-bet from SB vs BTN. You build the pot with a hand that dominates BTN\'s opening range and set up a c-bet on most boards.' },
        ],
      },
      {
        street: 'flop',
        board: ['Kh', '7s', '2d'],
        context: 'BTN calls your 3-bet. Pot 17BB. Flop Kh7s2d rainbow. You are OOP and act first.',
        prompt: 'AQo on K72 rainbow OOP in a 3-bet pot. Check or c-bet?',
        options: [
          { id: 'check',   label: 'Check (protect range)',  quality: 'perfect',    evLoss: 0,   coaching: 'K72 rainbow heavily favours BTN\'s calling range (Kx, sets). AQ has zero equity here. Checking OOP protects your checking range and avoids bloating the pot with air. Let BTN bet into you.' },
          { id: 'bet33',   label: 'Bet 33% pot (5.6BB)',    quality: 'mistake',    evLoss: 1.5, coaching: 'C-betting K72 with AQ as the 3-bettor OOP is a common leak. You have no equity vs Kx and bloat the pot. Check and re-evaluate on the turn.' },
          { id: 'bet75',   label: 'Bet 75% pot (12.75BB)',  quality: 'punt',       evLoss: 3.5, coaching: 'Large c-bet on a K-high board with AQ OOP is a recipe for losing a big pot. The board hits BTN\'s range hard — check.' },
        ],
      },
      {
        street: 'turn',
        board: ['Kh', '7s', '2d', 'As'],
        context: 'You checked the flop. BTN checked behind. Turn is As — you just made top pair! You act first.',
        prompt: 'AQ turns top pair on K72A. BTN showed weakness. How do you play the turn?',
        options: [
          { id: 'check',   label: 'Check (slow-play the ace)',  quality: 'acceptable', evLoss: 0.8, coaching: 'Slow-playing is possible, but BTN checked back the flop which usually means medium-strength or a marginal hand. Betting extracts more value than checking.' },
          { id: 'bet40',   label: 'Bet 40% pot (6.8BB)',        quality: 'perfect',    evLoss: 0,   coaching: 'Turn bet after a flop check-check is a delayed c-bet. BTN\'s range includes Kx, pocket pairs (TT–99) and floats — all of which call a medium turn bet. Bet for value.' },
          { id: 'bet80',   label: 'Bet 80% pot (13.6BB)',       quality: 'mistake',    evLoss: 1.2, coaching: 'Over-betting turns away the hands you want to extract value from (Kx, medium pairs). A medium bet keeps more of BTN\'s range in.' },
        ],
      },
    ],
    summary: 'In 3-bet pots OOP, check missed boards (even with AQ) and re-evaluate. When you turn top pair after both players checked the flop, value-bet — BTN\'s range can\'t help but call.',
    tags: ['MTT', '3-bet pot', 'SB', 'AQo', 'early stage', 'OOP'],
  },

  // ── tr2: MTT Mid-Stage — CO Open, Two-Pair Protection ───────────────────
  {
    id: 'tr2-mtt-co-two-pair-protection',
    title: 'MTT CO — Two Pair on Connected Board',
    description: 'You open J9s from CO and flop top two pair on a connected board. How much protection do you need?',
    difficulty: 'intermediate',
    category: 'Value & Protection',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'CO',
    villainPosition: 'BB',
    heroCards: ['Js', '9h'],
    effectiveStack: 40,
    stakes: 'MTT $100 — Mid-stage, 40BB',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'UTG folds, MP folds, hero in CO with Js9h (40BB). BTN, SB, BB behind.',
        prompt: 'J9s in CO. Open, fold, or over-raise?',
        options: [
          { id: 'fold',     label: 'Fold (too weak)',          quality: 'mistake',    evLoss: 1.8, coaching: 'J9s is a clear open from CO in MTTs. It has strong playability (straight draws, flush draws) and positional advantage vs blinds. Folding is too tight here.' },
          { id: 'open22',   label: 'Open to 2.2BB (standard)', quality: 'perfect',    evLoss: 0,   coaching: 'J9s is a standard CO open. The suited connector plays well post-flop with position. Open and apply pressure to the blinds.' },
          { id: 'open35',   label: 'Open to 3.5BB (big)',      quality: 'acceptable', evLoss: 0.5, coaching: 'Over-raising with J9s wastes chips — you want the suited connector to see flops cheaply with good implied odds, not build big pots pre-flop.' },
        ],
      },
      {
        street: 'flop',
        board: ['Jh', 'Td', '5c'],
        context: 'BB defends. Pot 5.4BB. Flop Jh Td 5c. BB checks to you in position.',
        prompt: 'Js9h on JT5 — top pair plus gut-shot. BB checked. How do you build the pot?',
        options: [
          { id: 'check',   label: 'Check (pot control)',       quality: 'mistake',    evLoss: 2.0, coaching: 'Checking top pair on a connected board gives free cards to draws (78, 89, QK, flush draws). J9 on JT5 is a bet — protect and extract value.' },
          { id: 'bet33',   label: 'Bet 33% pot (1.8BB)',       quality: 'acceptable', evLoss: 0.5, coaching: 'Small bet is fine but undersizes vs the draw-heavy texture. BB\'s defending range includes a lot of draws. Size up slightly to charge them.' },
          { id: 'bet75',   label: 'Bet 75% pot (4BB)',         quality: 'perfect',    evLoss: 0,   coaching: 'On JT5 with top pair + gut-shot, bet big. The board has many straight draw combinations (89, QK, Q8). A large bet charges draws correctly and extracts from Jx and Tx pairs.' },
        ],
      },
      {
        street: 'turn',
        board: ['Jh', 'Td', '5c', '2s'],
        context: 'BB calls your 75% flop bet. Turn 2s — a blank. BB checks to you. Pot ~13.4BB, ~31BB behind.',
        prompt: 'Blank turn. BB called large bet on flop. Do you continue betting or pot-control?',
        options: [
          { id: 'check',   label: 'Check (pot control)',  quality: 'perfect',    evLoss: 0,   coaching: 'After a large flop bet was called, the pot is large relative to your stack (SPR ~2.3). BB calling a 75% bet on JT5 represents strong hands: KQ, Q8, 89, Jx. Checking controls the pot — you can still call a river bet and reach showdown safely.' },
          { id: 'bet40',   label: 'Bet 40% pot (5.4BB)',  quality: 'acceptable', evLoss: 0.6, coaching: 'A follow-up bet is possible but with low SPR, you risk getting check-raised into a committed spot. The blank turn doesn\'t change ranges much — checking is cleaner.' },
          { id: 'jam',     label: 'Jam all-in (~31BB)',   quality: 'mistake',    evLoss: 2.5, coaching: 'Jamming the turn risks your entire stack on top pair with a low gut-shot. MTT chips are precious — pot control after the large flop bet is the standard line.' },
        ],
      },
    ],
    summary: 'On connected flops with strong pairs, bet large to protect and charge draws. But once you\'ve built the pot, check back blank turns to control pot size and avoid bloating stacks into marginal SPR territory.',
    tags: ['MTT', 'CO', 'J9s', 'two pair', 'protection', 'mid-stage'],
  },

  // ── tr3: MTT Bubble — BB Defense, Flop Check, Turn Value ────────────────
  {
    id: 'tr3-mtt-bubble-bb-turn-value',
    title: 'MTT Bubble — BB Defense Then Turn Extraction',
    description: 'Near the bubble you defend BB with KTo. Miss the flop, hit the turn king. Exploit CO weakness.',
    difficulty: 'intermediate',
    category: 'Bubble Defense',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'BB',
    villainPosition: 'CO',
    heroCards: ['Kh', 'Td'],
    effectiveStack: 35,
    stakes: 'MTT $200 — Near bubble (top 20 paid, 22 left)',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Folds to CO who opens 2.5BB. BTN folds, SB folds. Hero in BB with KhTd, 35BB.',
        prompt: 'KTo in BB vs CO open near the bubble. Fold, defend, or 3-bet-jam?',
        options: [
          { id: 'fold',      label: 'Fold (bubble caution)',        quality: 'acceptable', evLoss: 0.5, coaching: 'Folding KTo is justifiable on the bubble — ICM penalises busting. But KTo dominates much of CO\'s range and has good post-flop playability with position on SB. Defending is better.' },
          { id: 'defend',    label: 'Defend call (2.5BB)',          quality: 'perfect',    evLoss: 0,   coaching: 'KTo is a good BB defend vs a CO open — you block Kx combos in CO\'s range and have a decent kicker. In position relative to SB and getting the right price, defend and play post-flop.' },
          { id: '3betjam',   label: '3-bet jam 35BB',               quality: 'mistake',    evLoss: 3.0, coaching: 'Jamming KTo near the bubble vs a CO open risks your tournament life on a marginal hand. ICM heavily penalises elimination — defend and play post-flop.' },
        ],
      },
      {
        street: 'flop',
        board: ['Ah', '9s', '6d'],
        context: 'Pot 5.5BB. Flop Ah 9s 6d. You are OOP (BB) and act first.',
        prompt: 'KTd on A96 — complete air. Do you lead, check, or bluff?',
        options: [
          { id: 'check',    label: 'Check (standard OOP)',          quality: 'perfect',    evLoss: 0,   coaching: 'With total air (no pair, no draw on A96), check OOP and let CO c-bet. If CO bets, you can fold without investing more. If CO checks back, you get a free turn to improve.' },
          { id: 'donk33',   label: 'Donk-lead 33% (1.8BB)',        quality: 'mistake',    evLoss: 1.5, coaching: 'Donk-betting with air on an ace-high board is risky — CO called a 3-bet range and will continue with all Ax hands. Check and see what CO does.' },
          { id: 'donkjam',  label: 'Jam all-in (35BB)',             quality: 'punt',       evLoss: 6.0, coaching: 'Jamming with king-high air near the bubble is a tournament-ending mistake. Check and take a free card.' },
        ],
      },
      {
        street: 'turn',
        board: ['Ah', '9s', '6d', 'Kd'],
        context: 'You checked. CO also checked the flop (showing weakness). Turn is Kd — you just hit top pair! You act first again.',
        prompt: 'Hero turned top pair after CO showed flop weakness. Extract value or trap?',
        options: [
          { id: 'check',    label: 'Check (trap for river)',       quality: 'acceptable', evLoss: 0.7, coaching: 'Trapping is possible, but CO checked the flop which means they likely have a weak Ax or a pair below the ace. A turn bet extracts much more value than giving a free river.' },
          { id: 'bet40',    label: 'Bet 40% pot (2.2BB)',          quality: 'acceptable', evLoss: 0.3, coaching: 'A standard bet works and is fine. But CO checked back a flop on A96 — their range is weak. A bigger bet extracts more from the hands that still call.' },
          { id: 'bet75',    label: 'Bet 75% pot (4.1BB)',          quality: 'perfect',    evLoss: 0,   coaching: 'When CO checks back A96, their range consists of weak pairs and missed hands. You just turned the top pair. Bet large: it looks like a delayed c-bet and extracts from all of CO\'s weak Ax, 9x, and medium pocket pairs that still continue.' },
        ],
      },
    ],
    summary: 'Near the bubble, defend strong hands but play disciplined post-flop. When you miss the flop OOP, check and take free cards. When villain shows weakness, extract hard once you improve.',
    tags: ['MTT', 'bubble', 'BB', 'KTo', 'delayed c-bet', 'turn value'],
  },

  // ── tr4: MTT Mid-Stage — BTN 3-bet IP, TPTK Navigation ─────────────────
  {
    id: 'tr4-mtt-3bet-ip-tptk',
    title: 'MTT BTN 3-bet IP — TPTK Over 4 Streets',
    description: 'You 3-bet BTN vs CO and flop top pair top kicker. Navigate a 4-street spot IP in an MTT.',
    difficulty: 'advanced',
    category: '3-bet Pot',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'BTN',
    villainPosition: 'CO',
    heroCards: ['Ac', 'Jh'],
    effectiveStack: 45,
    stakes: 'MTT $300 — Mid-stage, 45BB',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'CO opens 2.5BB. BTN (hero) with AcJh, 45BB. SB and BB fold.',
        prompt: 'AJo on BTN vs CO open. Fold, call, or 3-bet?',
        options: [
          { id: 'fold',   label: 'Fold',                quality: 'mistake',    evLoss: 2.0, coaching: 'Folding AJo on BTN vs a CO open is far too tight. AJ dominates most of CO\'s opening range and you have a positional advantage.' },
          { id: 'call',   label: 'Call (flat BTN)',      quality: 'acceptable', evLoss: 0.5, coaching: 'Calling is fine — you keep SPR high and play post-flop IP. But 3-betting builds the pot with a premium hand and creates c-bet opportunities.' },
          { id: '3bet',   label: '3-bet to 8BB',         quality: 'perfect',    evLoss: 0,   coaching: 'AJo on BTN is a standard 3-bet vs CO. You have position, a premium hand, and strong fold equity. 3-bet, build the pot, and apply pressure post-flop.' },
        ],
      },
      {
        street: 'flop',
        board: ['Jd', '8c', '2h'],
        context: 'CO calls the 3-bet. Pot 17.5BB. Flop Jd 8c 2h rainbow. CO checks to you.',
        prompt: 'TPTK on J82 rainbow. CO checked. How do you size the c-bet?',
        options: [
          { id: 'check',   label: 'Check back (trap)',       quality: 'acceptable', evLoss: 0.6, coaching: 'Checking TPTK is a valid deception play but in a 3-bet pot, checking back often just gives free cards to hands that need to fold. Bet for value.' },
          { id: 'bet33',   label: 'Bet 33% pot (5.8BB)',     quality: 'perfect',    evLoss: 0,   coaching: 'Small c-bet with TPTK on a dry J82 board. CO\'s range includes JT, J9, pocket pairs (TT–33) and missed AK/AQ. A small bet extracts value from all of these while keeping CO in with weaker hands.' },
          { id: 'bet75',   label: 'Bet 75% pot (13.1BB)',    quality: 'mistake',    evLoss: 1.5, coaching: 'Over-betting J82 in an MTT 3-bet pot overcommits chips. A small bet achieves the same result — fold out air, get calls from second-best hands.' },
        ],
      },
      {
        street: 'turn',
        board: ['Jd', '8c', '2h', '9c'],
        context: 'CO calls the small c-bet. Turn 9c. Pot ~29BB. CO checks again.',
        prompt: 'J829c — straight draws, club draws appeared. CO called the flop and checked turn. Bet or pot control?',
        options: [
          { id: 'check',   label: 'Check (pot control)',     quality: 'perfect',    evLoss: 0,   coaching: 'After a small flop bet was called, SPR is now ~1.5. The 9c adds flush draw and straight draw combinations (T7, JT, QT). CO has shown strength by calling twice — TPTK is good but vulnerable. Checking controls the pot and lets CO bluff river or check behind.' },
          { id: 'bet50',   label: 'Bet 50% pot (14.5BB)',    quality: 'acceptable', evLoss: 0.8, coaching: 'Betting is fine but with low SPR and a wetter board, you risk inflating the pot vs a hand that beats you. Checking is safer at this tournament stack depth.' },
          { id: 'jam',     label: 'Jam all-in (~37BB)',      quality: 'mistake',    evLoss: 2.5, coaching: 'Jamming TPTK on a two-draw board in an MTT is too aggressive. With low SPR after two streets, checking is cleaner and avoids over-committing vs a turned two pair or set.' },
        ],
      },
      {
        street: 'river',
        board: ['Jd', '8c', '2h', '9c', '5d'],
        context: 'You checked the turn. CO also checked. River 5d — a blank. Pot ~29BB. CO checks to you.',
        prompt: 'Blank river, CO checked twice after calling the flop. TPTK — extract thin value or check down?',
        options: [
          { id: 'check',   label: 'Check (showdown value)',     quality: 'acceptable', evLoss: 0.5, coaching: 'Checking is okay — you get to showdown cheaply. But CO checked the turn and river; their range is capped. A thin value bet extracts from Jx and pocket pairs that won\'t bet themselves.' },
          { id: 'bet40',   label: 'Bet 40% pot (11.6BB)',       quality: 'perfect',    evLoss: 0,   coaching: 'Thin value bet on a bricked river after CO showed passivity on the turn. CO\'s range: Jx (weaker kicker), 9x, 8x, pocket pairs — all call a 40% bet. Extract value from the second-best hands that called your c-bet looking for showdown.' },
          { id: 'jam',     label: 'Jam all-in (37BB)',          quality: 'mistake',    evLoss: 2.0, coaching: 'Jamming the river with TPTK as a bluff or value bet is too much. Thin value at 40% captures all value with no risk of folding out worse hands.' },
        ],
      },
    ],
    summary: 'In MTT 3-bet pots IP, use small c-bets on dry boards. When the turn gets wet and SPR is low, check for pot control. Extract thin value on blank rivers — CO\'s passive line caps their range.',
    tags: ['MTT', 'BTN', 'AJo', '3-bet pot', 'TPTK', 'mid-stage', 'IP'],
  },

  // ── tr5: MTT Bubble — BB 98s, Flop Miss, Turn Pair, River Value ─────────
  {
    id: 'tr5-mtt-bb-draw-turned-pair',
    title: 'MTT BB — Defend Draw, Turn Pair, Extract',
    description: 'You defend BB with 98s. Miss the flop, turn middle pair. Apply pressure and extract value over 4 streets.',
    difficulty: 'intermediate',
    category: 'Draw Play',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'BB',
    villainPosition: 'BTN',
    heroCards: ['9h', '8h'],
    effectiveStack: 40,
    stakes: 'MTT $100 — Near bubble, 40BB',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'BTN opens 2.2BB. SB folds. Hero in BB with 9h8h, 40BB.',
        prompt: '98s in BB vs BTN open. Fold, defend, or 3-bet-squeeze?',
        options: [
          { id: 'fold',     label: 'Fold (bubble caution)',         quality: 'mistake',    evLoss: 1.5, coaching: '98s is a strong BB defend vs BTN — it has excellent implied odds with flush draws and two-way straight draws. Folding is too tight even near the bubble.' },
          { id: 'defend',   label: 'Defend call (get pot odds)',    quality: 'perfect',    evLoss: 0,   coaching: '98s in BB has strong implied odds: flush draws, two-way straight draws, and post-flop playability. Defend and play post-flop with position advantage on most boards.' },
          { id: '3betsqz',  label: '3-bet squeeze to 8BB',         quality: 'acceptable', evLoss: 0.7, coaching: '3-betting 98s heads-up vs BTN is possible but not optimal near the bubble. Hands like 98s play better as calls with implied odds intact — 3-betting turns it into a bluff semi-hand.' },
        ],
      },
      {
        street: 'flop',
        board: ['Ah', '7d', '2s'],
        context: 'Pot 4.6BB. Flop Ah 7d 2s rainbow. You act first OOP.',
        prompt: '98hh on A72r — no pair, backdoor straight (7-8-9 needs runner-runner) and backdoor flush (3 hearts). No direct draw. You act first OOP.',
        options: [
          { id: 'check',    label: 'Check (standard OOP, no direct draw)', quality: 'perfect',    evLoss: 0,   coaching: 'Checking is correct. 9h8h on Ah7d2s has no direct draw — only backdoor straight (7-8-9 needs two more specific cards) and backdoor flush (3 hearts: Ah,9h,8h). You have no pair and near-zero immediate equity. Check and let BTN c-bet; fold to pressure or continue cheaply.' },
          { id: 'donk33',   label: 'Donk-lead 33% (1.5BB)',               quality: 'mistake',    evLoss: 1.5, coaching: 'Donk-betting with no pair and only backdoor draws on an ace-high board is a mistake. BTN\'s range smashes A72 — you have minimal equity and no direct draw to justify investing chips.' },
          { id: 'donkbig',  label: 'Donk-lead 75% (3.45BB)',              quality: 'punt',       evLoss: 3.5, coaching: 'Large donk-bet with backdoor draws only on A72 is a punt. You have no pair, no flush draw, no straight draw — only runner-runner potential. Check and preserve your chips.' },
        ],
      },
      {
        street: 'turn',
        board: ['Ah', '7d', '2s', '8c'],
        context: 'You checked the flop. BTN c-bet, you called with implied odds (backdoor draws + two overcards). Turn 8c — you turned middle pair! You act first OOP.',
        prompt: 'You turned middle pair on A728. BTN showed aggression but you now have equity. Lead or check?',
        options: [
          { id: 'check',   label: 'Check (let BTN bet again)',    quality: 'acceptable', evLoss: 0.7, coaching: 'Checking is fine — BTN was aggressive on the flop and may bet again. But leading the turn after calling a flop bet represents a strong hand and puts BTN in a tough spot vs your range of 8x, 7x, and draws that improved.' },
          { id: 'bet50',   label: 'Bet 50% pot (5.7BB)',          quality: 'acceptable', evLoss: 0.4, coaching: 'A 50% turn lead is solid but under-prices vs BTN\'s pair and draw hands. Betting larger extracts more from worse hands and charges draws.' },
          { id: 'bet75',   label: 'Bet 75% pot (8.6BB)',          quality: 'perfect',    evLoss: 0,   coaching: 'Lead large on the turn after calling the flop c-bet. BTN\'s flop c-bet was on A72 — they likely have an ace or a pair. Your 8x turned a real hand, and leading for 75% charges draws, protects against Ax pairs, and extracts value from BTN\'s under-pairs.' },
        ],
      },
      {
        street: 'river',
        board: ['Ah', '7d', '2s', '8c', '3d'],
        context: 'BTN called your turn bet. River 3d — a blank. Pot ~22.8BB. BTN leads into you for 40% pot (9.1BB).',
        prompt: 'You turned middle pair and bet the turn. River BTN leads for 40%. Call, fold, or raise?',
        options: [
          { id: 'fold',    label: 'Fold (respect river lead)',     quality: 'mistake',    evLoss: 2.5, coaching: 'Folding middle pair to a small river lead is too tight. BTN\'s 40% river lead on A7283 can be a blocking bet with Ax or Tx. You beat all bluffs and thin-value bets.' },
          { id: 'call',    label: 'Call (showdown value)',         quality: 'perfect',    evLoss: 0,   coaching: 'Call the 40% river lead. BTN\'s line — c-bet flop, call turn bet, lead small river — is consistent with blocking value (Ax with weak kicker, Tx, or missed draws on A-high). 8x is a solid bluff-catcher here.' },
          { id: 'raise',   label: 'Raise (thin value/bluff)',      quality: 'mistake',    evLoss: 2.0, coaching: 'Raising middle pair on the river as a bluff or thin-value is too risky. BTN can have Ax that calls your raise all day. Just call and see the showdown.' },
        ],
      },
    ],
    summary: 'With suited connectors in BB: on A72r, 98hh has NO direct draw — only backdoor straight (7-8-9 runner-runner) and backdoor flush (3 hearts). Check the flop with near-zero equity. Call when BTN c-bets and you have implied odds for the turn. Lead large when you turn a pair — you\'ve improved to a real hand. Thin-call small river leads that look like blocking bets.',
    tags: ['MTT', 'BB', '98s', 'backdoor draw', 'bubble', 'turn pair', 'bluff catch'],
  },

  // ── tr6: MTT Final Table — 3-bet with Underpair, Fold River ─────────────
  {
    id: 'tr6-mtt-ft-underpair-fold',
    title: 'MTT Final Table — 3-bet TT, Underpair to K, River Fold',
    description: 'You 3-bet TT at the final table. Flop comes K-high. Navigate the hand and find the river fold.',
    difficulty: 'advanced',
    category: 'ICM',
    gameType: 'tournament',
    format: 'MTT',
    heroPosition: 'BTN',
    villainPosition: 'SB',
    heroCards: ['Tc', 'Th'],
    effectiveStack: 50,
    stakes: 'MTT $1000 — Final table, 4 players left',
    steps: [
      {
        street: 'preflop',
        board: [],
        context: 'Final table, 4 players left. SB opens 2.5BB. Hero BTN with TcTh, 50BB.',
        prompt: 'TT on BTN vs SB open at the final table. Fold, call, or 3-bet?',
        options: [
          { id: 'fold',    label: 'Fold (ICM caution)',            quality: 'mistake',    evLoss: 3.0, coaching: 'Folding TT at a 4-handed final table vs a SB open is far too passive. TT is a strong hand — you must fight back.' },
          { id: 'call',    label: 'Call (avoid confrontation)',    quality: 'acceptable', evLoss: 0.8, coaching: 'Calling is fine — you see a flop in position. But 3-betting applies more pressure, builds the pot, and could win immediately vs SB\'s steal range.' },
          { id: '3bet',    label: '3-bet to 9BB',                  quality: 'perfect',    evLoss: 0,   coaching: 'TT is a standard 3-bet vs a SB open at the final table. You are IP, your hand crushes SB\'s stealing range, and a 3-bet may win immediately or set up a profitable c-bet.' },
        ],
      },
      {
        street: 'flop',
        board: ['Kc', '6d', '2h'],
        context: 'SB calls the 3-bet. Pot 19.5BB. Flop Kc 6d 2h rainbow. SB checks to you.',
        prompt: 'TT on K62 rainbow — underpair to the K. SB checked. Bet or protect your hand?',
        options: [
          { id: 'check',   label: 'Check back (protect TT range)', quality: 'perfect',    evLoss: 0,   coaching: 'K62 rainbow is a board that heavily favours SB\'s calling range (Kx hands). Checking back TT on the BTN in a 3-bet pot is the correct play — you avoid bloating the pot with an underpair and keep the SPR workable for later streets. If SB has Kx, betting the flop just loses more.' },
          { id: 'bet33',   label: 'Bet 33% pot (6.4BB)',           quality: 'acceptable', evLoss: 0.8, coaching: 'Small c-bet is possible but risks escalating vs Kx. At the final table, checking TT on K-high boards is generally cleaner — preserve your stack.' },
          { id: 'bet75',   label: 'Bet 75% pot (14.6BB)',          quality: 'mistake',    evLoss: 2.5, coaching: 'Large c-bet with TT as an underpair on K62 is a significant ICM mistake. You\'re putting chips in the pot as a large underdog when SB holds any king.' },
        ],
      },
      {
        street: 'turn',
        board: ['Kc', '6d', '2h', '7h'],
        context: 'You checked the flop. SB checked back. Turn 7h — a relatively blank card. SB checks again.',
        prompt: 'SB checked both streets after calling a 3-bet. TT on K627. Time to take a stab?',
        options: [
          { id: 'check',   label: 'Check (complete giveup)',       quality: 'mistake',    evLoss: 1.5, coaching: 'SB checked the flop AND the turn — their range is capped and weak. This is the perfect spot to fire a bet and take down the pot uncontested. Checking wastes your fold equity.' },
          { id: 'bet40',   label: 'Bet 40% pot (7.8BB)',           quality: 'perfect',    evLoss: 0,   coaching: 'After two checks from SB, their range is capped: medium pairs (JJ–88), weak Kx, 6x. Bet 40% on the turn to pick up the pot. SB showed two streets of weakness — take advantage. This is a standard delayed c-bet at the final table.' },
          { id: 'jam',     label: 'Jam all-in (43BB)',             quality: 'mistake',    evLoss: 2.5, coaching: 'Jamming 43BB as a turn bluff at a final table with TT is reckless. A 40% bet achieves the same fold rate at a fraction of the risk.' },
        ],
      },
      {
        street: 'river',
        board: ['Kc', '6d', '2h', '7h', 'Qd'],
        context: 'SB called your 40% turn bet. River Qd. SB leads into you for 55% pot (20BB).',
        prompt: 'SB called your delayed c-bet and now leads the river on KQ762. TT — call, fold, or raise?',
        options: [
          { id: 'fold',    label: 'Fold (respect the lead)',       quality: 'perfect',    evLoss: 0,   coaching: 'SB called a 3-bet pre, checked two streets, called a turn bet, and then leads the river on a K-Q board. This exact line — passive then aggressive — strongly represents two pair or a monster (KQ, K7, 67, Q2). With TT as a pure underpair to both the K and Q, fold and preserve your final-table chips.' },
          { id: 'call',    label: 'Call (bluff catch)',            quality: 'mistake',    evLoss: 3.5, coaching: 'The ICM cost of being wrong here is massive. SB\'s line (check-check-call-lead) at a final table is rarely a bluff — it\'s value all the way. TT loses to KX, Q7, K7 and any two-pair. Fold.' },
          { id: 'raise',   label: 'Raise (bluff shove)',           quality: 'punt',       evLoss: 8.0, coaching: 'Raising TT on KQ762 river vs a river donk at the final table is a massive ICM mistake. You\'re turning a bluff-catcher into a bluff against a hand that almost never folds. Fold.' },
        ],
      },
    ],
    summary: 'At MTT final tables, 3-bet strong hands but check back on K-high boards with underpairs. Exploit two-street passivity with a delayed c-bet. Fold to river aggression when your underpair can\'t beat two pair — ICM makes the fold clear.',
    tags: ['MTT', 'final table', 'ICM', 'TT', 'underpair', '3-bet pot', 'fold river'],
  },
]
