/**
 * Generates lib/learn/curriculumPublic.generated.ts — the lesson METADATA
 * (title, subtitle, estimated_min, xp_reward, sort_order, ...) with `steps`
 * and `chapters` stripped, plus a computed `step_count`.
 *
 * WHY THIS EXISTS: curriculum.ts's `LESSONS` array embeds full interactive
 * step content (including correct answers) inside every lesson object. Any
 * client component that imports curriculum.ts — even one that only reads
 * `.title` — causes the bundler to include that full content in its client
 * JS chunk, because ES module tree-shaking removes unused EXPORTS, not
 * unused object PROPERTIES within an export that IS used. Before this file
 * existed, that meant every visitor's browser already had the full content
 * (and answers) of every locked lesson, regardless of subscription tier or
 * login state, defeating any server-side access check on the lesson page
 * itself. Every consumer that only needs metadata (module overview, journey
 * map, dashboard's "continue learning" card, the landing page) should import
 * from the generated file below instead of curriculum.ts — only
 * app/learn/lesson/[slug]/page.tsx (a Server Component, never bundled to the
 * client) and its matching backend checks may import the real curriculum.ts.
 *
 * curriculum.ts remains the ONE authoritative source. This file (and the
 * generated .ts it produces) is a generated artifact, never hand-edited —
 * mirrors generate-reward-manifest.ts's exact pattern, including a
 * freshness test (see lib/learn/__tests__/curriculumPublicFreshness.test.ts)
 * that fails the suite if the checked-in file and curriculum.ts disagree.
 *
 * Run via: npm run generate:curriculum-public  (from frontend/)
 */
import { writeFileSync } from 'fs'
import path from 'path'
import { LESSONS, LEARNING_MODULES, LEARNING_PATHS } from '../lib/learn/curriculum'
import type { PublicLesson } from '../lib/learn/types'

export interface CurriculumPublicData {
  lessons: PublicLesson[]
  modules: typeof LEARNING_MODULES
  paths: typeof LEARNING_PATHS
}

export function buildCurriculumPublic(): CurriculumPublicData {
  const lessons: PublicLesson[] = LESSONS.map(({ steps, chapters, ...meta }) => ({
    ...meta,
    step_count: steps.length,
  }))
  return { lessons, modules: LEARNING_MODULES, paths: LEARNING_PATHS }
}

const HEADER = `// AUTO-GENERATED by scripts/generateCurriculumPublic.ts — DO NOT EDIT BY HAND.
// Run \`npm run generate:curriculum-public\` after changing curriculum.ts.
//
// Lesson METADATA only — \`steps\`/\`chapters\` (the actual interactive content
// and answer keys) are deliberately stripped. Import from here, never from
// '../curriculum', unless you are app/learn/lesson/[slug]/page.tsx itself or
// a backend equivalent. See generateCurriculumPublic.ts's module docstring.

import type { LearningModule, LearningPath, PublicLesson } from './types'
`

export function main() {
  const data = buildCurriculumPublic()

  const body = `
export const PUBLIC_LESSONS: PublicLesson[] = ${JSON.stringify(data.lessons, null, 2)}

export const LEARNING_MODULES: LearningModule[] = ${JSON.stringify(data.modules, null, 2)}

export const LEARNING_PATHS: LearningPath[] = ${JSON.stringify(data.paths, null, 2)}

export const LESSONS_BY_SLUG: Record<string, PublicLesson> =
  Object.fromEntries(PUBLIC_LESSONS.map((l) => [l.slug, l]))

export const MODULES_BY_SLUG: Record<string, LearningModule> =
  Object.fromEntries(LEARNING_MODULES.map((m) => [m.slug, m]))

/** module_id -> lessons in that module */
export const LESSONS_BY_MODULE: Record<string, PublicLesson[]> =
  PUBLIC_LESSONS.reduce<Record<string, PublicLesson[]>>((acc, l) => {
    if (!acc[l.module_id]) acc[l.module_id] = []
    acc[l.module_id].push(l)
    return acc
  }, {})

/** path_id -> modules in that path */
export const MODULES_BY_PATH: Record<string, LearningModule[]> =
  LEARNING_MODULES.reduce<Record<string, LearningModule[]>>((acc, m) => {
    if (!acc[m.path_id]) acc[m.path_id] = []
    acc[m.path_id].push(m)
    return acc
  }, {})
`

  const outPath = path.resolve(__dirname, '../lib/learn/curriculumPublic.generated.ts')
  writeFileSync(outPath, HEADER + body)
  console.log(
    `Wrote curriculum public metadata: ${data.lessons.length} lessons, ` +
    `${data.modules.length} modules, ${data.paths.length} paths -> ${outPath}`,
  )
}
