// AUTO-GENERATED by scripts/generateCurriculumPublic.ts — DO NOT EDIT BY HAND.
// Run `npm run generate:curriculum-public` after changing curriculum.ts.
//
// Lesson METADATA only — `steps`/`chapters` (the actual interactive content
// and answer keys) are deliberately stripped. Import from here, never from
// '../curriculum', unless you are app/learn/lesson/[slug]/page.tsx itself or
// a backend equivalent. See generateCurriculumPublic.ts's module docstring.

import type { LearningModule, LearningPath, PublicLesson } from './types'

export const PUBLIC_LESSONS: PublicLesson[] = [
  {
    "id": "how-poker-works",
    "module_id": "poker-fundamentals-module",
    "slug": "how-poker-works",
    "title": "How Poker Works",
    "subtitle": "The absolute-beginner rules of Texas Hold’em, taught fast so the real course can begin.",
    "lesson_type": "micro",
    "concept_ids": [
      "holdem_objective",
      "hole_cards",
      "community_cards",
      "poker_terminology",
      "blinds",
      "streets",
      "basic_actions",
      "hand_rankings",
      "winning_the_pot",
      "table_position"
    ],
    "estimated_min": 12,
    "xp_reward": 220,
    "sort_order": 1,
    "step_count": 23
  },
  {
    "id": "your-seat-at-the-table",
    "module_id": "poker-fundamentals-module",
    "slug": "your-seat-at-the-table",
    "title": "Your Seat at the Table",
    "subtitle": "Position, action order, and why acting later is a real structural edge.",
    "lesson_type": "micro",
    "concept_ids": [
      "table_position",
      "relative_position",
      "ip_oop",
      "action_order"
    ],
    "estimated_min": 13,
    "xp_reward": 230,
    "sort_order": 2,
    "step_count": 17
  },
  {
    "id": "speak-the-language",
    "module_id": "poker-fundamentals-module",
    "slug": "speak-the-language",
    "title": "Speak the Language",
    "subtitle": "Infer the vocabulary of poker from real situations, not a glossary.",
    "lesson_type": "micro",
    "concept_ids": [
      "poker_terminology",
      "stack_depth",
      "effective_stack",
      "bet_size_notation",
      "nuts"
    ],
    "estimated_min": 13,
    "xp_reward": 230,
    "sort_order": 3,
    "step_count": 18
  },
  {
    "id": "hands-boards-and-what-can-change",
    "module_id": "poker-fundamentals-module",
    "slug": "hands-boards-and-what-can-change",
    "title": "Hands, Boards & What Can Change",
    "subtitle": "The bridge between knowing the rules and thinking strategically.",
    "lesson_type": "micro",
    "concept_ids": [
      "made_hand",
      "hand_vs_draw",
      "board_texture",
      "absolute_hand_strength",
      "contextual_hand_strength",
      "nuts",
      "effective_nuts"
    ],
    "estimated_min": 14,
    "xp_reward": 240,
    "sort_order": 4,
    "step_count": 19
  },
  {
    "id": "think-in-ranges",
    "module_id": "poker-fundamentals-module",
    "slug": "think-in-ranges",
    "title": "Think in Ranges",
    "subtitle": "Stop guessing one hand — learn to picture everything an opponent could hold.",
    "lesson_type": "micro",
    "concept_ids": [
      "range_thinking",
      "combinatorics",
      "range_morphology"
    ],
    "estimated_min": 15,
    "xp_reward": 260,
    "sort_order": 5,
    "step_count": 20
  },
  {
    "id": "foundation-lab",
    "module_id": "poker-fundamentals-module",
    "slug": "foundation-lab",
    "title": "Foundation Lab",
    "subtitle": "Apply everything from all five lessons together, under pressure.",
    "lesson_type": "puzzle_drill",
    "concept_ids": [
      "holdem_objective",
      "basic_actions",
      "hand_rankings",
      "table_position",
      "ip_oop",
      "action_order",
      "poker_terminology",
      "effective_stack",
      "nuts",
      "made_hand",
      "board_texture",
      "contextual_hand_strength",
      "range_thinking",
      "combinatorics",
      "range_morphology"
    ],
    "estimated_min": 14,
    "xp_reward": 320,
    "sort_order": 6,
    "next_lesson_teaser": "The Math Behind Every Decision",
    "step_count": 15
  },
  {
    "id": "the-price-of-a-call",
    "module_id": "math-foundations-module",
    "slug": "the-price-of-a-call",
    "title": "The Price of a Call",
    "subtitle": "Every call is a risk-versus-reward decision — learn to price it before you look at your cards.",
    "lesson_type": "micro",
    "concept_ids": [
      "pot_odds",
      "risk_reward",
      "required_equity",
      "break_even"
    ],
    "estimated_min": 12,
    "xp_reward": 150,
    "sort_order": 1,
    "next_lesson_teaser": "Count Your Ways to Win",
    "step_count": 10
  },
  {
    "id": "count-your-ways-to-win",
    "module_id": "math-foundations-module",
    "slug": "count-your-ways-to-win",
    "title": "Count Your Ways to Win",
    "subtitle": "Turn your outs into a real probability — and learn why the quick shortcuts are only estimates.",
    "lesson_type": "micro",
    "concept_ids": [
      "outs_probability",
      "clean_outs",
      "dead_outs",
      "drawing_probability"
    ],
    "estimated_min": 14,
    "xp_reward": 170,
    "sort_order": 2,
    "next_lesson_teaser": "Your Share of the Pot",
    "step_count": 15
  },
  {
    "id": "your-share-of-the-pot",
    "module_id": "math-foundations-module",
    "slug": "your-share-of-the-pot",
    "title": "Your Share of the Pot",
    "subtitle": "Equity only exists relative to an opponent — hand, range, or another range.",
    "lesson_type": "micro",
    "concept_ids": [
      "equity",
      "hand_vs_hand_equity",
      "hand_vs_range_equity",
      "range_vs_range_equity",
      "range_weighting"
    ],
    "estimated_min": 13,
    "xp_reward": 160,
    "sort_order": 3,
    "next_lesson_teaser": "Think in Expected Value",
    "step_count": 8
  },
  {
    "id": "think-in-expected-value",
    "module_id": "math-foundations-module",
    "slug": "think-in-expected-value",
    "title": "Think in Expected Value",
    "subtitle": "Judge decisions by what they earn over time, not by what happened this one time.",
    "lesson_type": "micro",
    "concept_ids": [
      "expected_value",
      "positive_ev",
      "negative_ev",
      "zero_ev",
      "decision_quality"
    ],
    "estimated_min": 16,
    "xp_reward": 220,
    "sort_order": 4,
    "next_lesson_teaser": "Winning Without Showdown",
    "step_count": 18
  },
  {
    "id": "winning-without-showdown",
    "module_id": "math-foundations-module",
    "slug": "winning-without-showdown",
    "title": "Winning Without Showdown",
    "subtitle": "A bet can profit two ways — by winning at showdown, or by ending the hand before it gets there.",
    "lesson_type": "micro",
    "concept_ids": [
      "fold_equity",
      "break_even_bluff",
      "semi_bluff"
    ],
    "estimated_min": 14,
    "xp_reward": 190,
    "sort_order": 5,
    "next_lesson_teaser": "Equity Isn't Everything",
    "step_count": 12
  },
  {
    "id": "equity-isnt-everything",
    "module_id": "math-foundations-module",
    "slug": "equity-isnt-everything",
    "title": "Equity Isn't Everything",
    "subtitle": "Learn why having equity and actually capturing it are two different things.",
    "lesson_type": "micro",
    "concept_ids": [
      "equity_realization",
      "position_realization",
      "suitedness_realization",
      "connectedness_realization",
      "range_advantage_realization",
      "spr_realization"
    ],
    "estimated_min": 18,
    "xp_reward": 260,
    "sort_order": 6,
    "next_lesson_teaser": "From Mathematics to Strategy",
    "step_count": 18
  },
  {
    "id": "decision-lab",
    "module_id": "math-foundations-module",
    "slug": "decision-lab",
    "title": "Decision Lab",
    "subtitle": "Three real hands. Every tool from this module, working together.",
    "lesson_type": "simulation",
    "concept_ids": [
      "pot_odds",
      "equity",
      "expected_value",
      "fold_equity",
      "equity_realization",
      "decision_quality"
    ],
    "estimated_min": 15,
    "xp_reward": 300,
    "sort_order": 7,
    "step_count": 18
  },
  {
    "id": "first-in",
    "module_id": "preflop-foundation-module",
    "slug": "first-in",
    "title": "First In",
    "subtitle": "Knowing what to do when everyone folds to you is one of poker's most important skills.",
    "lesson_type": "micro",
    "concept_ids": [
      "first_in",
      "rfi",
      "baseline_strategy"
    ],
    "estimated_min": 12,
    "xp_reward": 150,
    "sort_order": 1,
    "next_lesson_teaser": "What Makes a Hand Playable?",
    "step_count": 18
  },
  {
    "id": "more-than-two-cards",
    "module_id": "preflop-foundation-module",
    "slug": "more-than-two-cards",
    "title": "What Makes a Hand Playable?",
    "subtitle": "Equity, playability, blockers and nut potential all shape which hands belong in a range.",
    "lesson_type": "micro",
    "concept_ids": [
      "preflop_hand_selection",
      "high_card_value",
      "suitedness_preflop",
      "connectedness_preflop",
      "pocket_pair_value",
      "preflop_blockers",
      "preflop_playability"
    ],
    "estimated_min": 14,
    "xp_reward": 170,
    "sort_order": 2,
    "next_lesson_teaser": "Stack Depth Changes Everything",
    "step_count": 9
  },
  {
    "id": "stacks-change-the-range",
    "module_id": "preflop-foundation-module",
    "slug": "stacks-change-the-range",
    "title": "Stack Depth Changes Everything",
    "subtitle": "The same position can call for a completely different strategy at 15bb, 25bb, 40bb and 60bb.",
    "lesson_type": "micro",
    "concept_ids": [
      "stack_depth_preflop",
      "open_shove",
      "raise_fold"
    ],
    "estimated_min": 14,
    "xp_reward": 170,
    "sort_order": 3,
    "next_lesson_teaser": "UTG Mastery",
    "step_count": 10
  },
  {
    "id": "utg-mastery",
    "module_id": "preflop-foundation-module",
    "slug": "utg-mastery",
    "title": "UTG Mastery",
    "subtitle": "The tightest seat at the table — and the one that changes least with stack depth.",
    "lesson_type": "micro",
    "concept_ids": [
      "utg_rfi",
      "position_rfi",
      "range_construction",
      "stack_depth_preflop"
    ],
    "estimated_min": 18,
    "xp_reward": 220,
    "sort_order": 4,
    "next_lesson_teaser": "UTG+1 Mastery",
    "step_count": 21
  },
  {
    "id": "utg1-mastery",
    "module_id": "preflop-foundation-module",
    "slug": "utg1-mastery",
    "title": "UTG+1 Mastery",
    "subtitle": "Fairly linear — but the range actually narrows again at the deepest stacks.",
    "lesson_type": "micro",
    "concept_ids": [
      "utg1_rfi",
      "position_rfi",
      "range_construction",
      "stack_depth_preflop"
    ],
    "estimated_min": 18,
    "xp_reward": 220,
    "sort_order": 5,
    "next_lesson_teaser": "UTG+2 Mastery",
    "step_count": 21
  },
  {
    "id": "utg2-mastery",
    "module_id": "preflop-foundation-module",
    "slug": "utg2-mastery",
    "title": "UTG+2 Mastery",
    "subtitle": "The last true early-position seat — and where the open-jam disappears for good.",
    "lesson_type": "micro",
    "concept_ids": [
      "utg2_rfi",
      "position_rfi",
      "range_construction",
      "stack_depth_preflop"
    ],
    "estimated_min": 18,
    "xp_reward": 220,
    "sort_order": 6,
    "next_lesson_teaser": "Lojack Mastery",
    "step_count": 21
  },
  {
    "id": "lj-mastery",
    "module_id": "preflop-foundation-module",
    "slug": "lj-mastery",
    "title": "Lojack Mastery",
    "subtitle": "Plays like the Hijack, but tighter — the price of one extra player left to act.",
    "lesson_type": "micro",
    "concept_ids": [
      "lj_rfi",
      "position_rfi",
      "range_construction",
      "stack_depth_preflop"
    ],
    "estimated_min": 18,
    "xp_reward": 220,
    "sort_order": 7,
    "next_lesson_teaser": "Hijack Mastery",
    "step_count": 21
  },
  {
    "id": "hj-mastery",
    "module_id": "preflop-foundation-module",
    "slug": "hj-mastery",
    "title": "Hijack Mastery",
    "subtitle": "The widest true middle-position seat — and one where 25bb to 40bb barely changes anything.",
    "lesson_type": "micro",
    "concept_ids": [
      "hj_rfi",
      "position_rfi",
      "range_construction",
      "stack_depth_preflop"
    ],
    "estimated_min": 18,
    "xp_reward": 220,
    "sort_order": 8,
    "next_lesson_teaser": "Cutoff Mastery",
    "step_count": 21
  },
  {
    "id": "cutoff-ranges",
    "module_id": "preflop-foundation-module",
    "slug": "cutoff-ranges",
    "title": "Cutoff Mastery",
    "subtitle": "Only two players left to act — and one of the very few seats that widens steadily with depth.",
    "lesson_type": "micro",
    "concept_ids": [
      "co_rfi",
      "position_rfi",
      "range_construction",
      "stack_depth_preflop"
    ],
    "estimated_min": 18,
    "xp_reward": 220,
    "sort_order": 9,
    "next_lesson_teaser": "Button Mastery",
    "step_count": 21
  },
  {
    "id": "button-ranges",
    "module_id": "preflop-foundation-module",
    "slug": "button-ranges",
    "title": "Button Mastery",
    "subtitle": "No one can ever put the Button out of position — the widest non-blind opening range at the table.",
    "lesson_type": "micro",
    "concept_ids": [
      "btn_rfi",
      "position_rfi",
      "range_construction",
      "stack_depth_preflop"
    ],
    "estimated_min": 18,
    "xp_reward": 220,
    "sort_order": 10,
    "next_lesson_teaser": "Small Blind Mastery",
    "step_count": 21
  },
  {
    "id": "the-small-blind-is-different",
    "module_id": "preflop-foundation-module",
    "slug": "the-small-blind-is-different",
    "title": "Small Blind Mastery",
    "subtitle": "Guaranteed to play out of position if called — and the only seat where limping is a real weapon.",
    "lesson_type": "micro",
    "concept_ids": [
      "sb_first_in",
      "limping",
      "stack_depth_preflop",
      "range_construction"
    ],
    "estimated_min": 20,
    "xp_reward": 240,
    "sort_order": 11,
    "next_lesson_teaser": "Build the Opening Strategy",
    "step_count": 24
  },
  {
    "id": "preflop-foundation-lab",
    "module_id": "preflop-foundation-module",
    "slug": "preflop-foundation-lab",
    "title": "Preflop Range Mastery Lab",
    "subtitle": "Roughly 40 interleaved table decisions, boundary comparisons, stack-depth and position comparisons, and reconstructions — every position, every depth, in random order.",
    "lesson_type": "simulation",
    "concept_ids": [
      "first_in",
      "rfi",
      "position_rfi",
      "players_behind",
      "stack_depth_preflop",
      "preflop_sizing",
      "antes",
      "rake_adjustment",
      "limping",
      "sb_first_in",
      "range_construction",
      "preflop_planning",
      "utg_rfi",
      "utg1_rfi",
      "utg2_rfi",
      "lj_rfi",
      "hj_rfi",
      "co_rfi",
      "btn_rfi",
      "shallow_stack_rfi",
      "mid_stack_rfi",
      "deep_stack_rfi"
    ],
    "estimated_min": 30,
    "xp_reward": 400,
    "sort_order": 12,
    "step_count": 40
  },
  {
    "id": "the-3-bet",
    "module_id": "preflop-aggression-module",
    "slug": "the-3-bet",
    "title": "The 3-Bet",
    "subtitle": "Learn why reraising preflop is about far more than having a premium hand.",
    "lesson_type": "micro",
    "concept_ids": [
      "three_bet",
      "three_bet_motives",
      "range_vs_range",
      "opener_range_strength",
      "players_behind_aggression"
    ],
    "estimated_min": 11,
    "xp_reward": 140,
    "sort_order": 1,
    "next_lesson_teaser": "Building a 3-Bet Range",
    "step_count": 9
  },
  {
    "id": "building-a-3bet-range",
    "module_id": "preflop-aggression-module",
    "slug": "building-a-3bet-range",
    "title": "Building a 3-Bet Range",
    "subtitle": "A good 3-bet strategy is a range, not a collection of favorite hands.",
    "lesson_type": "micro",
    "concept_ids": [
      "three_bet_range_construction",
      "opener_range_strength",
      "card_removal"
    ],
    "estimated_min": 13,
    "xp_reward": 160,
    "sort_order": 2,
    "next_lesson_teaser": "Shape of Aggression",
    "step_count": 8
  },
  {
    "id": "linear-vs-polarized",
    "module_id": "preflop-aggression-module",
    "slug": "linear-vs-polarized",
    "title": "Shape of Aggression",
    "subtitle": "Why some 3-bet ranges attack from the top down while others split into value and bluffs.",
    "lesson_type": "micro",
    "concept_ids": [
      "linear_range",
      "polarized",
      "calling_range_effect"
    ],
    "estimated_min": 14,
    "xp_reward": 170,
    "sort_order": 3,
    "next_lesson_teaser": "Position and Equity Realization",
    "step_count": 10
  },
  {
    "id": "position-and-equity-realization",
    "module_id": "preflop-aggression-module",
    "slug": "position-and-equity-realization",
    "title": "Position and Equity Realization",
    "subtitle": "Position determines how much equity your hands can actually realize.",
    "lesson_type": "micro",
    "concept_ids": [
      "position_three_bet",
      "equity_realization_preflop",
      "opener_range_strength"
    ],
    "estimated_min": 13,
    "xp_reward": 160,
    "sort_order": 4,
    "next_lesson_teaser": "Block the Continue",
    "step_count": 11
  },
  {
    "id": "block-the-continue",
    "module_id": "preflop-aggression-module",
    "slug": "block-the-continue",
    "title": "Block the Continue",
    "subtitle": "Your cards change the hands your opponent can have.",
    "lesson_type": "micro",
    "concept_ids": [
      "card_removal",
      "blockers",
      "three_bet_range_construction"
    ],
    "estimated_min": 14,
    "xp_reward": 170,
    "sort_order": 5,
    "next_lesson_teaser": "Size the Pressure",
    "step_count": 9
  },
  {
    "id": "size-the-pressure",
    "module_id": "preflop-aggression-module",
    "slug": "size-the-pressure",
    "title": "Size the Pressure",
    "subtitle": "A 3-bet changes both the price of continuing and the geometry of the hand.",
    "lesson_type": "micro",
    "concept_ids": [
      "three_bet_sizing",
      "position_three_bet"
    ],
    "estimated_min": 13,
    "xp_reward": 160,
    "sort_order": 6,
    "next_lesson_teaser": "The Squeeze",
    "step_count": 7
  },
  {
    "id": "the-squeeze",
    "module_id": "preflop-aggression-module",
    "slug": "the-squeeze",
    "title": "The Squeeze",
    "subtitle": "When an open gets called, the extra player changes the incentives.",
    "lesson_type": "micro",
    "concept_ids": [
      "squeeze",
      "three_bet_range_construction",
      "opener_range_strength"
    ],
    "estimated_min": 20,
    "xp_reward": 250,
    "sort_order": 7,
    "next_lesson_teaser": "They Raised Back",
    "step_count": 15
  },
  {
    "id": "they-raised-back",
    "module_id": "preflop-aggression-module",
    "slug": "they-raised-back",
    "title": "They Raised Back",
    "subtitle": "Your opening range must survive resistance.",
    "lesson_type": "micro",
    "concept_ids": [
      "facing_three_bet",
      "position_three_bet",
      "three_bet_range_construction"
    ],
    "estimated_min": 30,
    "xp_reward": 326,
    "sort_order": 8,
    "next_lesson_teaser": "Raise Again",
    "step_count": 26
  },
  {
    "id": "raise-again",
    "module_id": "preflop-aggression-module",
    "slug": "raise-again",
    "title": "Raise Again",
    "subtitle": "Learn how stack depth transforms preflop re-aggression.",
    "lesson_type": "micro",
    "concept_ids": [
      "four_bet",
      "four_bet_bluff",
      "cold_four_bet",
      "five_bet",
      "rejam"
    ],
    "estimated_min": 16,
    "xp_reward": 190,
    "sort_order": 9,
    "next_lesson_teaser": "Attack the Leak",
    "step_count": 12
  },
  {
    "id": "attack-the-leak",
    "module_id": "preflop-aggression-module",
    "slug": "attack-the-leak",
    "title": "Attack the Leak",
    "subtitle": "GTO gives the baseline. Opponent mistakes tell you when to move away from it.",
    "lesson_type": "micro",
    "concept_ids": [
      "exploit_over_three_bet",
      "exploit_overfold",
      "exploit_overcall",
      "exploit_under_three_bet",
      "alpha_three_bet"
    ],
    "estimated_min": 17,
    "xp_reward": 200,
    "sort_order": 10,
    "next_lesson_teaser": "Preflop Aggression Lab",
    "step_count": 15
  },
  {
    "id": "preflop-aggression-lab",
    "module_id": "preflop-aggression-module",
    "slug": "preflop-aggression-lab",
    "title": "Preflop Aggression Lab",
    "subtitle": "Read the resistance. Build the response.",
    "lesson_type": "simulation",
    "concept_ids": [
      "three_bet",
      "squeeze",
      "four_bet",
      "cold_four_bet",
      "five_bet",
      "rejam",
      "linear_range",
      "polarized",
      "three_bet_range_construction",
      "blockers",
      "three_bet_sizing",
      "facing_three_bet",
      "exploit_over_three_bet"
    ],
    "estimated_min": 28,
    "xp_reward": 400,
    "sort_order": 11,
    "step_count": 35
  },
  {
    "id": "someone-opened",
    "module_id": "defending-the-open-module",
    "slug": "someone-opened",
    "title": "Facing an Open",
    "subtitle": "Your cards are only one part of the decision.",
    "lesson_type": "micro",
    "concept_ids": [
      "defending_opens",
      "opener_range_strength",
      "range_vs_range",
      "players_behind_aggression"
    ],
    "estimated_min": 12,
    "xp_reward": 150,
    "sort_order": 1,
    "next_lesson_teaser": "Defending as HJ",
    "step_count": 6
  },
  {
    "id": "defending-as-hj",
    "module_id": "defending-the-open-module",
    "slug": "defending-as-hj",
    "title": "Defending as HJ",
    "subtitle": "One seat past first-in — but still facing a tight, strong range.",
    "lesson_type": "micro",
    "concept_ids": [
      "defending_opens",
      "opener_range_strength",
      "domination",
      "range_construction"
    ],
    "estimated_min": 16,
    "xp_reward": 200,
    "sort_order": 2,
    "next_lesson_teaser": "Defending as CO",
    "step_count": 9
  },
  {
    "id": "defending-as-co",
    "module_id": "defending-the-open-module",
    "slug": "defending-as-co",
    "title": "Defending as CO",
    "subtitle": "Two openers behind you now — and equity realization starts to matter.",
    "lesson_type": "micro",
    "concept_ids": [
      "equity_realization_preflop",
      "domination",
      "suitedness_preflop",
      "connectedness_preflop",
      "pocket_pair_value",
      "opener_range_strength"
    ],
    "estimated_min": 18,
    "xp_reward": 220,
    "sort_order": 3,
    "next_lesson_teaser": "Defending as BTN",
    "step_count": 14
  },
  {
    "id": "the-big-blind-discount",
    "module_id": "defending-the-open-module",
    "slug": "defending-as-bb",
    "title": "Defending as BB",
    "subtitle": "You get the best price at the table — and some of the hardest postflop situations.",
    "lesson_type": "micro",
    "concept_ids": [
      "bb_defense",
      "opener_range_strength",
      "stack_depth_defense",
      "pot_odds_preflop",
      "range_construction"
    ],
    "estimated_min": 24,
    "xp_reward": 280,
    "sort_order": 6,
    "next_lesson_teaser": "Stack Depth Adjustments",
    "step_count": 25
  },
  {
    "id": "position-changes-everything-defense",
    "module_id": "defending-the-open-module",
    "slug": "defending-as-btn",
    "title": "Defending as BTN",
    "subtitle": "When you can call and keep position, more hands can survive.",
    "lesson_type": "micro",
    "concept_ids": [
      "btn_defense",
      "position_three_bet",
      "players_behind_aggression",
      "equity_realization_preflop",
      "range_construction"
    ],
    "estimated_min": 18,
    "xp_reward": 220,
    "sort_order": 4,
    "next_lesson_teaser": "Defending as SB",
    "step_count": 12
  },
  {
    "id": "the-small-blind-problem",
    "module_id": "defending-the-open-module",
    "slug": "defending-as-sb",
    "title": "Defending as SB",
    "subtitle": "A discount helps. Being out of position with the big blind behind hurts.",
    "lesson_type": "micro",
    "concept_ids": [
      "sb_defense",
      "players_behind_aggression",
      "position_three_bet",
      "stack_depth_defense"
    ],
    "estimated_min": 18,
    "xp_reward": 220,
    "sort_order": 5,
    "next_lesson_teaser": "Defending as BB",
    "step_count": 11
  },
  {
    "id": "same-hand-different-stack",
    "module_id": "defending-the-open-module",
    "slug": "same-hand-different-stack",
    "title": "Stack Depth Adjustments",
    "subtitle": "Stack depth changes what your hand is trying to accomplish.",
    "lesson_type": "micro",
    "concept_ids": [
      "stack_depth_defense",
      "rejam_awareness",
      "bb_defense",
      "sb_defense"
    ],
    "estimated_min": 20,
    "xp_reward": 230,
    "sort_order": 7,
    "next_lesson_teaser": "Build Your Defense Range",
    "step_count": 16
  },
  {
    "id": "range-architect-defense",
    "module_id": "defending-the-open-module",
    "slug": "range-architect-defense",
    "title": "Build Your Defense Range",
    "subtitle": "Stop solving one hand at a time.",
    "lesson_type": "micro",
    "concept_ids": [
      "range_construction",
      "range_adjustment",
      "defending_opens",
      "bb_defense"
    ],
    "estimated_min": 20,
    "xp_reward": 230,
    "sort_order": 8,
    "next_lesson_teaser": "Defense Room",
    "step_count": 13
  },
  {
    "id": "defense-room",
    "module_id": "defending-the-open-module",
    "slug": "defense-room",
    "title": "Defense Room",
    "subtitle": "Read the open. Read the table. Build the response.",
    "lesson_type": "simulation",
    "concept_ids": [
      "defending_opens",
      "bb_defense",
      "sb_defense",
      "btn_defense",
      "opener_range_strength",
      "pot_odds_preflop",
      "equity_realization_preflop",
      "stack_depth_defense",
      "range_construction",
      "range_adjustment",
      "players_behind_aggression"
    ],
    "estimated_min": 26,
    "xp_reward": 400,
    "sort_order": 9,
    "step_count": 18
  },
  {
    "id": "the-flop-has-a-language",
    "module_id": "flop-fundamentals-module",
    "slug": "the-flop-has-a-language",
    "title": "The Flop Has a Language",
    "subtitle": "Learn why classifying a flop beats memorizing one.",
    "lesson_type": "micro",
    "concept_ids": [
      "flop_classification",
      "suit_isomorphism"
    ],
    "estimated_min": 12,
    "xp_reward": 165,
    "sort_order": 1,
    "next_lesson_teaser": "Board Structure",
    "step_count": 14
  },
  {
    "id": "board-structure",
    "module_id": "flop-fundamentals-module",
    "slug": "board-structure",
    "title": "Board Structure",
    "subtitle": "Trips, paired, or unpaired — the first fork in the road.",
    "lesson_type": "micro",
    "concept_ids": [
      "flop_structure",
      "flop_texture"
    ],
    "estimated_min": 13,
    "xp_reward": 170,
    "sort_order": 2,
    "next_lesson_teaser": "Read the Suits",
    "step_count": 16
  },
  {
    "id": "read-the-suits",
    "module_id": "flop-fundamentals-module",
    "slug": "read-the-suits",
    "title": "Read the Suits",
    "subtitle": "Monotone, two-tone, rainbow — and the three flavors of two-tone.",
    "lesson_type": "micro",
    "concept_ids": [
      "flop_texture",
      "two_tone_subtypes"
    ],
    "estimated_min": 8,
    "xp_reward": 100,
    "sort_order": 3,
    "next_lesson_teaser": "Read the Ranks",
    "step_count": 10
  },
  {
    "id": "read-the-ranks",
    "module_id": "flop-fundamentals-module",
    "slug": "read-the-ranks",
    "title": "Read the Ranks",
    "subtitle": "Rank families, flop families, and counting possible straights.",
    "lesson_type": "micro",
    "concept_ids": [
      "flop_rank",
      "flop_families",
      "flopped_straights"
    ],
    "estimated_min": 9,
    "xp_reward": 110,
    "sort_order": 4,
    "next_lesson_teaser": "Will This Board Stay the Same?",
    "step_count": 10
  },
  {
    "id": "will-this-board-stay-the-same",
    "module_id": "flop-fundamentals-module",
    "slug": "will-this-board-stay-the-same",
    "title": "Will This Board Stay the Same?",
    "subtitle": "Static vs. dynamic — and why the runout matters.",
    "lesson_type": "micro",
    "concept_ids": [
      "board_volatility",
      "static_dynamic",
      "runout_awareness"
    ],
    "estimated_min": 8,
    "xp_reward": 105,
    "sort_order": 5,
    "next_lesson_teaser": "The Board Doesn't Play Alone",
    "step_count": 8
  },
  {
    "id": "the-board-doesnt-play-alone",
    "module_id": "flop-fundamentals-module",
    "slug": "the-board-doesnt-play-alone",
    "title": "The Board Doesn't Play Alone",
    "subtitle": "The same flop affects different ranges differently.",
    "lesson_type": "micro",
    "concept_ids": [
      "range_board_interaction"
    ],
    "estimated_min": 8,
    "xp_reward": 105,
    "sort_order": 6,
    "next_lesson_teaser": "How Strong Is Strong?",
    "step_count": 5
  },
  {
    "id": "how-strong-is-strong",
    "module_id": "flop-fundamentals-module",
    "slug": "how-strong-is-strong",
    "title": "How Strong Is Strong?",
    "subtitle": "Equity buckets — and why hand value is never fixed.",
    "lesson_type": "micro",
    "concept_ids": [
      "equity_buckets",
      "relative_hand_strength"
    ],
    "estimated_min": 25,
    "xp_reward": 330,
    "sort_order": 7,
    "next_lesson_teaser": "The Flop Scanner",
    "step_count": 31
  },
  {
    "id": "the-flop-scanner",
    "module_id": "flop-fundamentals-module",
    "slug": "the-flop-scanner",
    "title": "The Flop Scanner",
    "subtitle": "Put every dimension together — and preview where it leads.",
    "lesson_type": "micro",
    "concept_ids": [
      "flop_classification",
      "range_advantage",
      "nut_advantage"
    ],
    "estimated_min": 9,
    "xp_reward": 120,
    "sort_order": 8,
    "next_lesson_teaser": "The Flop Laboratory",
    "step_count": 10
  },
  {
    "id": "flop-laboratory",
    "module_id": "flop-fundamentals-module",
    "slug": "flop-laboratory",
    "title": "The Flop Laboratory",
    "subtitle": "Every skill from this module, mixed and tested.",
    "lesson_type": "puzzle_drill",
    "concept_ids": [
      "flop_classification",
      "flop_structure",
      "flop_texture",
      "two_tone_subtypes",
      "flop_rank",
      "flop_families",
      "flopped_straights",
      "board_volatility",
      "static_dynamic",
      "range_board_interaction",
      "equity_buckets"
    ],
    "estimated_min": 16,
    "xp_reward": 220,
    "sort_order": 9,
    "step_count": 24
  },
  {
    "id": "cbet-not-automatic",
    "module_id": "cbetting-fundamentals-module",
    "slug": "cbet-not-automatic",
    "title": "The C-Bet Is Not Automatic",
    "subtitle": "Preflop aggression does not determine flop strategy. Range interaction does.",
    "lesson_type": "micro",
    "concept_ids": [
      "cbet_definition",
      "range_advantage",
      "flop_range_strategy"
    ],
    "estimated_min": 14,
    "xp_reward": 170,
    "sort_order": 1,
    "next_lesson_teaser": "Read the Battlefield",
    "step_count": 9
  },
  {
    "id": "read-the-battlefield",
    "module_id": "cbetting-fundamentals-module",
    "slug": "read-the-battlefield",
    "title": "Read the Battlefield",
    "subtitle": "Turn flop classification into a strategic tool.",
    "lesson_type": "micro",
    "concept_ids": [
      "flop_range_strategy",
      "range_advantage"
    ],
    "estimated_min": 14,
    "xp_reward": 170,
    "sort_order": 2,
    "next_lesson_teaser": "Range Advantage Is Not Enough",
    "step_count": 9
  },
  {
    "id": "range-advantage-not-enough",
    "module_id": "cbetting-fundamentals-module",
    "slug": "range-advantage-not-enough",
    "title": "Range Advantage Is Not Enough",
    "subtitle": "Ask not just who has more equity — ask WHERE it is located.",
    "lesson_type": "micro",
    "concept_ids": [
      "range_composition",
      "equity_buckets",
      "strong_hand_density"
    ],
    "estimated_min": 18,
    "xp_reward": 232,
    "sort_order": 3,
    "next_lesson_teaser": "High-Frequency C-Bets",
    "step_count": 11
  },
  {
    "id": "high-frequency-cbets",
    "module_id": "cbetting-fundamentals-module",
    "slug": "high-frequency-cbets",
    "title": "High-Frequency C-Bets",
    "subtitle": "Understand why some boards allow frequent betting — and why look-alikes do not.",
    "lesson_type": "micro",
    "concept_ids": [
      "cbet_frequency",
      "range_advantage",
      "strong_hand_density"
    ],
    "estimated_min": 16,
    "xp_reward": 208,
    "sort_order": 4,
    "next_lesson_teaser": "When the C-Bet Slows Down",
    "step_count": 8
  },
  {
    "id": "cbet-slows-down",
    "module_id": "cbetting-fundamentals-module",
    "slug": "cbet-slows-down",
    "title": "When the C-Bet Slows Down",
    "subtitle": "The mirror image of Lesson 4 — what makes betting frequency drop.",
    "lesson_type": "micro",
    "concept_ids": [
      "cbet_frequency",
      "strong_hand_density",
      "range_advantage"
    ],
    "estimated_min": 17,
    "xp_reward": 214,
    "sort_order": 5,
    "next_lesson_teaser": "Small Bet or Big Bet?",
    "step_count": 8
  },
  {
    "id": "small-bet-or-big-bet",
    "module_id": "cbetting-fundamentals-module",
    "slug": "small-bet-or-big-bet",
    "title": "Small Bet or Big Bet?",
    "subtitle": "Bet sizing is a range decision, not a board-texture rule of thumb.",
    "lesson_type": "micro",
    "concept_ids": [
      "cbet_sizing",
      "polarization_advantage",
      "threebet_pot_cbet"
    ],
    "estimated_min": 32,
    "xp_reward": 448,
    "sort_order": 6,
    "next_lesson_teaser": "What Does My Hand Do?",
    "step_count": 20
  },
  {
    "id": "what-does-my-hand-do",
    "module_id": "cbetting-fundamentals-module",
    "slug": "what-does-my-hand-do",
    "title": "What Does My Hand Do?",
    "subtitle": "Every strategy is made of individual hands playing different roles.",
    "lesson_type": "micro",
    "concept_ids": [
      "cbet_hand_selection",
      "range_protection",
      "checking_range"
    ],
    "estimated_min": 18,
    "xp_reward": 226,
    "sort_order": 7,
    "next_lesson_teaser": "In Position vs Out of Position",
    "step_count": 6
  },
  {
    "id": "position-changes-everything",
    "module_id": "cbetting-fundamentals-module",
    "slug": "position-changes-everything",
    "title": "In Position vs Out of Position",
    "subtitle": "Checking means something different depending on who acts next.",
    "lesson_type": "micro",
    "concept_ids": [
      "position_postflop",
      "ip_cbet",
      "oop_cbet"
    ],
    "estimated_min": 16,
    "xp_reward": 218,
    "sort_order": 8,
    "next_lesson_teaser": "The C-Bet Decision Lab",
    "step_count": 5
  },
  {
    "id": "cbet-decision-lab",
    "module_id": "cbetting-fundamentals-module",
    "slug": "cbet-decision-lab",
    "title": "The C-Bet Decision Lab",
    "subtitle": "Every tool from this module, mixed and applied under pressure.",
    "lesson_type": "simulation",
    "concept_ids": [
      "cbet_definition",
      "range_advantage",
      "range_composition",
      "equity_buckets",
      "strong_hand_density",
      "polarization_advantage",
      "cbet_frequency",
      "cbet_sizing",
      "position_postflop",
      "ip_cbet",
      "oop_cbet",
      "checking_range",
      "range_protection",
      "cbet_hand_selection",
      "threebet_pot_cbet"
    ],
    "estimated_min": 30,
    "xp_reward": 462,
    "sort_order": 9,
    "step_count": 16
  },
  {
    "id": "stop-thinking-hand-vs-hand",
    "module_id": "range-vs-range-module",
    "slug": "stop-thinking-hand-vs-hand",
    "title": "Stop Thinking Hand vs Hand",
    "subtitle": "Your hand is strong. Is your range?",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "range_vs_range_equity",
      "hand_vs_range_strength",
      "range_advantage"
    ],
    "estimated_min": 8,
    "xp_reward": 170,
    "sort_order": 1,
    "next_lesson_teaser": "Range Advantage",
    "step_count": 10
  },
  {
    "id": "range-advantage",
    "module_id": "range-vs-range-module",
    "slug": "range-advantage",
    "title": "Range Advantage",
    "subtitle": "Same players. Different flop. Now put a number on it.",
    "lesson_type": "puzzle_drill",
    "concept_ids": [
      "board_texture_shift",
      "range_advantage",
      "range_vs_range_equity"
    ],
    "estimated_min": 16,
    "xp_reward": 340,
    "sort_order": 2,
    "next_lesson_teaser": "X-Ray the Range",
    "step_count": 15
  },
  {
    "id": "x-ray-the-range",
    "module_id": "range-vs-range-module",
    "slug": "x-ray-the-range",
    "title": "X-Ray the Range",
    "subtitle": "A range has 55% equity. Do you know enough?",
    "lesson_type": "micro",
    "concept_ids": [
      "equity_buckets",
      "equity_bucket_distribution",
      "strong_hand_density",
      "range_composition",
      "nut_advantage"
    ],
    "estimated_min": 12,
    "xp_reward": 260,
    "sort_order": 3,
    "next_lesson_teaser": "Why Strategy Changes",
    "step_count": 12
  },
  {
    "id": "why-strategy-changes",
    "module_id": "range-vs-range-module",
    "slug": "why-strategy-changes",
    "title": "Why Strategy Changes",
    "subtitle": "Range advantage does not simply mean \"bet.\"",
    "lesson_type": "puzzle_drill",
    "concept_ids": [
      "range_composition",
      "range_advantage",
      "board_coverage",
      "range_archaeology"
    ],
    "estimated_min": 13,
    "xp_reward": 250,
    "sort_order": 4,
    "next_lesson_teaser": "The Range Lab",
    "step_count": 12
  },
  {
    "id": "the-range-lab",
    "module_id": "range-vs-range-module",
    "slug": "the-range-lab",
    "title": "The Range Lab",
    "subtitle": "A small poker research laboratory — not an exam.",
    "lesson_type": "simulation",
    "concept_ids": [
      "range_vs_range_equity",
      "range_advantage",
      "equity_bucket_distribution",
      "hand_vs_range_strength",
      "nut_advantage",
      "board_coverage"
    ],
    "estimated_min": 20,
    "xp_reward": 500,
    "sort_order": 5,
    "step_count": 18
  },
  {
    "id": "from-hands-to-combos",
    "module_id": "blockers-module",
    "slug": "from-hands-to-combos",
    "title": "From Hands to Combos",
    "subtitle": "\"AA\" is not one hand. It is six.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "combo_counting",
      "card_removal"
    ],
    "estimated_min": 16,
    "xp_reward": 290,
    "sort_order": 1,
    "next_lesson_teaser": "Block the Value",
    "step_count": 23
  },
  {
    "id": "block-the-value",
    "module_id": "blockers-module",
    "slug": "block-the-value",
    "title": "Block the Value",
    "subtitle": "Which part of the range did your cards actually touch?",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "card_removal",
      "blocker_classification"
    ],
    "estimated_min": 10,
    "xp_reward": 185,
    "sort_order": 2,
    "next_lesson_teaser": "Same Strength, Different Cards",
    "step_count": 13
  },
  {
    "id": "same-strength-different-cards",
    "module_id": "blockers-module",
    "slug": "same-strength-different-cards",
    "title": "Same Strength, Different Cards",
    "subtitle": "Equal showdown value does not mean equal strategic value.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "blocker_classification",
      "card_removal"
    ],
    "estimated_min": 7,
    "xp_reward": 140,
    "sort_order": 3,
    "next_lesson_teaser": "The Nut Blocker",
    "step_count": 5
  },
  {
    "id": "the-nut-blocker",
    "module_id": "blockers-module",
    "slug": "the-nut-blocker",
    "title": "The Nut Blocker",
    "subtitle": "One card. Zero traps.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "nut_blocker",
      "blocker_classification"
    ],
    "estimated_min": 9,
    "xp_reward": 160,
    "sort_order": 6,
    "next_lesson_teaser": "A Blocker Is Not Always Good",
    "step_count": 5
  },
  {
    "id": "a-blocker-is-not-always-good",
    "module_id": "blockers-module",
    "slug": "a-blocker-is-not-always-good",
    "title": "A Blocker Is Not Always Good",
    "subtitle": "Same card logic. Different range structure.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "blocker_classification",
      "nut_blocker"
    ],
    "estimated_min": 8,
    "xp_reward": 150,
    "sort_order": 7,
    "next_lesson_teaser": "Blockers When Calling",
    "step_count": 5
  },
  {
    "id": "blockers-when-calling",
    "module_id": "blockers-module",
    "slug": "blockers-when-calling",
    "title": "Blockers When Calling",
    "subtitle": "The same logic, from the other side of the bet.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "card_removal",
      "blocker_classification"
    ],
    "estimated_min": 7,
    "xp_reward": 140,
    "sort_order": 8,
    "next_lesson_teaser": "Read the Removal",
    "step_count": 5
  },
  {
    "id": "read-the-removal",
    "module_id": "blockers-module",
    "slug": "read-the-removal",
    "title": "Read the Removal",
    "subtitle": "Same five stages. Less help each time.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "card_removal",
      "blocker_classification"
    ],
    "estimated_min": 8,
    "xp_reward": 150,
    "sort_order": 9,
    "next_lesson_teaser": "Blocker Lab",
    "step_count": 8
  },
  {
    "id": "blocker-lab",
    "module_id": "blockers-module",
    "slug": "blocker-lab",
    "title": "Blocker Lab",
    "subtitle": "One investigation, start to finish.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "card_removal",
      "blocker_classification",
      "nut_blocker",
      "combo_counting"
    ],
    "estimated_min": 12,
    "xp_reward": 200,
    "sort_order": 10,
    "step_count": 9
  },
  {
    "id": "your-move-changes-mine",
    "module_id": "game-theory-foundations-module",
    "slug": "your-move-changes-mine",
    "title": "Your Move Changes Mine",
    "subtitle": "A strategy is never good in isolation — only against a specific opponent.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "strategy_interdependence",
      "maximally_exploitative_strategy"
    ],
    "estimated_min": 14,
    "xp_reward": 270,
    "sort_order": 1,
    "next_lesson_teaser": "The Exploit Has a Cost",
    "step_count": 11
  },
  {
    "id": "the-exploit-has-a-cost",
    "module_id": "game-theory-foundations-module",
    "slug": "the-exploit-has-a-cost",
    "title": "The Exploit Has a Cost",
    "subtitle": "Your edge only lasts as long as the mistake does.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "counter_exploitation"
    ],
    "estimated_min": 8,
    "xp_reward": 140,
    "sort_order": 2,
    "next_lesson_teaser": "The Strategy Loop",
    "step_count": 5
  },
  {
    "id": "the-strategy-loop",
    "module_id": "game-theory-foundations-module",
    "slug": "the-strategy-loop",
    "title": "The Strategy Loop",
    "subtitle": "Push, respond, adjust, respond again — where does it end?",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "nash_equilibrium_source"
    ],
    "estimated_min": 9,
    "xp_reward": 150,
    "sort_order": 3,
    "next_lesson_teaser": "When Neither Player Can Improve",
    "step_count": 4
  },
  {
    "id": "when-neither-player-can-improve",
    "module_id": "game-theory-foundations-module",
    "slug": "when-neither-player-can-improve",
    "title": "When Neither Player Can Improve",
    "subtitle": "Nash equilibrium, tested by hand — not defined by decree.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "nash_equilibrium_source"
    ],
    "estimated_min": 9,
    "xp_reward": 160,
    "sort_order": 4,
    "next_lesson_teaser": "Make Them Indifferent",
    "step_count": 8
  },
  {
    "id": "make-them-indifferent",
    "module_id": "game-theory-foundations-module",
    "slug": "make-them-indifferent",
    "title": "Make Them Indifferent",
    "subtitle": "Your opponent's strategy is what makes your mix correct.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "indifference_principle"
    ],
    "estimated_min": 9,
    "xp_reward": 150,
    "sort_order": 5,
    "next_lesson_teaser": "The Clairvoyance Game",
    "step_count": 7
  },
  {
    "id": "the-clairvoyance-game",
    "module_id": "game-theory-foundations-module",
    "slug": "the-clairvoyance-game",
    "title": "The Clairvoyance Game",
    "subtitle": "The Clairvoyance Game — this is the centerpiece.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "clairvoyance_game"
    ],
    "estimated_min": 12,
    "xp_reward": 220,
    "sort_order": 6,
    "next_lesson_teaser": "How Much Must You Defend?",
    "step_count": 8
  },
  {
    "id": "how-much-must-you-defend",
    "module_id": "game-theory-foundations-module",
    "slug": "how-much-must-you-defend",
    "title": "How Much Must You Defend?",
    "subtitle": "Deriving Alpha and MDF instead of memorizing them.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "alpha_mdf_derivation"
    ],
    "estimated_min": 10,
    "xp_reward": 180,
    "sort_order": 7,
    "next_lesson_teaser": "MDF Is Not a Commandment",
    "step_count": 7
  },
  {
    "id": "mdf-is-not-a-commandment",
    "module_id": "game-theory-foundations-module",
    "slug": "mdf-is-not-a-commandment",
    "title": "MDF Is Not a Commandment",
    "subtitle": "A benchmark from a simplified model — not a universal rule.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "mdf_limitations"
    ],
    "estimated_min": 8,
    "xp_reward": 150,
    "sort_order": 8,
    "next_lesson_teaser": "Equilibrium Lab",
    "step_count": 6
  },
  {
    "id": "equilibrium-lab",
    "module_id": "game-theory-foundations-module",
    "slug": "equilibrium-lab",
    "title": "Equilibrium Lab",
    "subtitle": "The full reasoning chain, in one sitting.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "strategy_interdependence",
      "maximally_exploitative_strategy",
      "counter_exploitation",
      "nash_equilibrium_source",
      "indifference_principle",
      "alpha_mdf_derivation",
      "mdf_limitations"
    ],
    "estimated_min": 15,
    "xp_reward": 260,
    "sort_order": 9,
    "step_count": 11
  },
  {
    "id": "why-we-bet",
    "module_id": "polarized-module",
    "slug": "why-we-bet",
    "title": "Why We Bet",
    "subtitle": "Betting is not \"value or bluff\" — it is leveraging what you know that your opponent doesn't.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "informational_advantage"
    ],
    "estimated_min": 10,
    "xp_reward": 140,
    "sort_order": 1,
    "next_lesson_teaser": "The Same Range, Two Faces",
    "step_count": 7
  },
  {
    "id": "the-same-range-two-faces",
    "module_id": "polarized-module",
    "slug": "the-same-range-two-faces",
    "title": "The Same Range, Two Faces",
    "subtitle": "A range's shape was never fixed — it depends on who's looking.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "relative_range_shape",
      "capped_vs_condensed"
    ],
    "estimated_min": 11,
    "xp_reward": 150,
    "sort_order": 2,
    "next_lesson_teaser": "Composition Beats Equity",
    "step_count": 7
  },
  {
    "id": "composition-beats-equity",
    "module_id": "polarized-module",
    "slug": "composition-beats-equity",
    "title": "Composition Beats Equity",
    "subtitle": "A close-to-coinflip equity number can hide a range that's quietly dominating.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "range_composition"
    ],
    "estimated_min": 12,
    "xp_reward": 160,
    "sort_order": 3,
    "next_lesson_teaser": "Bluffs Have a Job",
    "step_count": 15
  },
  {
    "id": "bluffs-have-a-job",
    "module_id": "polarized-module",
    "slug": "bluffs-have-a-job",
    "title": "Bluffs Have a Job",
    "subtitle": "A polarized range's bluffs have an exact, non-negotiable size — not a matter of feel.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "bluff_to_value_ratio"
    ],
    "estimated_min": 12,
    "xp_reward": 160,
    "sort_order": 4,
    "next_lesson_teaser": "Protect the Checking Range",
    "step_count": 8
  },
  {
    "id": "protect-the-checking-range",
    "module_id": "polarized-module",
    "slug": "protect-the-checking-range",
    "title": "Protect the Checking Range",
    "subtitle": "The hands you don't bet aren't leftovers — they need their own construction.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "protected_checking_range"
    ],
    "estimated_min": 13,
    "xp_reward": 170,
    "sort_order": 5,
    "step_count": 6
  },
  {
    "id": "bet-size-is-a-sentence",
    "module_id": "bet-sizing-language-module",
    "slug": "bet-size-is-a-sentence",
    "title": "A Bet Size Is a Sentence",
    "subtitle": "A strategy fixes a small menu of sizes before any specific hand is even considered.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "sizing_as_action_abstraction"
    ],
    "estimated_min": 10,
    "xp_reward": 160,
    "sort_order": 1,
    "next_lesson_teaser": "What a Size Buys You",
    "step_count": 8
  },
  {
    "id": "what-a-size-buys-you",
    "module_id": "bet-sizing-language-module",
    "slug": "what-a-size-buys-you",
    "title": "What a Size Buys You",
    "subtitle": "Pot odds, Alpha, MDF, value:bluff ratio — one connected cascade from a single input.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "alpha_size_dependence"
    ],
    "estimated_min": 12,
    "xp_reward": 170,
    "sort_order": 2,
    "next_lesson_teaser": "One Size Rarely Fits All",
    "step_count": 8
  },
  {
    "id": "one-size-rarely-fits-all",
    "module_id": "bet-sizing-language-module",
    "slug": "one-size-rarely-fits-all",
    "title": "One Size Rarely Fits All",
    "subtitle": "A size survives on the menu only if it can survive being raised.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "size_abandonment_mechanism"
    ],
    "estimated_min": 12,
    "xp_reward": 180,
    "sort_order": 3,
    "next_lesson_teaser": "The Small Cost of Simplifying",
    "step_count": 8
  },
  {
    "id": "the-small-cost-of-simplifying",
    "module_id": "bet-sizing-language-module",
    "slug": "the-small-cost-of-simplifying",
    "title": "The Small Cost of Simplifying",
    "subtitle": "Collapsing to one size costs surprisingly little EV — with specific, nameable exceptions.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "simplification_ev_cost",
      "one_size_fits_board_caveat"
    ],
    "estimated_min": 13,
    "xp_reward": 190,
    "sort_order": 4,
    "next_lesson_teaser": "Why Your Range Shape Picks Your Bet Size",
    "step_count": 8
  },
  {
    "id": "why-your-range-shape-picks-your-bet-size",
    "module_id": "bet-sizing-language-module",
    "slug": "why-your-range-shape-picks-your-bet-size",
    "title": "Why Your Range Shape Picks Your Bet Size",
    "subtitle": "Relative polarization alone moves a strategy smoothly from pure-check to all-in-dominant.",
    "lesson_type": "concept_reveal",
    "concept_ids": [
      "polarization_sizing_direction"
    ],
    "estimated_min": 13,
    "xp_reward": 190,
    "sort_order": 5,
    "next_lesson_teaser": "The Geometry of Maximum Pressure",
    "step_count": 9
  }
]

export const LEARNING_MODULES: LearningModule[] = [
  {
    "id": "poker-fundamentals-module",
    "path_id": "beginner",
    "slug": "poker-fundamentals-module",
    "title": "Poker Fundamentals",
    "description": "A complete foundation for everything that follows — the rules, the seat you sit in, the language, how hands and boards interact, and how to think in ranges.",
    "concept_ids": [
      "holdem_objective",
      "basic_actions",
      "hand_rankings",
      "winning_the_pot",
      "table_position",
      "ip_oop",
      "action_order",
      "poker_terminology",
      "effective_stack",
      "nuts",
      "made_hand",
      "hand_vs_draw",
      "board_texture",
      "contextual_hand_strength",
      "effective_nuts",
      "range_thinking",
      "combinatorics",
      "range_morphology"
    ],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 350,
    "subtitle": "A genuinely complete foundation for every module that follows.",
    "learningObjectives": [
      "Know the rules of Texas Hold’em and how a pot is won",
      "Read position, action order, and speak the language of the game",
      "Judge a hand in context — board texture, made hands vs draws, and a nuts that keeps moving",
      "Think in ranges instead of guessing a single hand"
    ],
    "difficulty": "beginner",
    "estimatedLessons": 6,
    "stageId": "foundations",
    "order": 1,
    "contentStatus": "complete",
    "access": "free"
  },
  {
    "id": "math-foundations-module",
    "path_id": "beginner",
    "slug": "math-foundations-module",
    "title": "The Math Behind Every Decision",
    "description": "Learn how risk, reward, probability and long-term value determine the right poker decision.",
    "concept_ids": [
      "pot_odds",
      "outs_probability",
      "equity",
      "expected_value",
      "fold_equity",
      "equity_realization"
    ],
    "unlock_after": [
      "poker-fundamentals-module"
    ],
    "sort_order": 1,
    "xp_reward": 600,
    "subtitle": "Learn how risk, reward, probability and long-term value determine the right poker decision.",
    "learningObjectives": [
      "Price a call using pot odds and required equity",
      "Count outs and estimate drawing probability under time pressure",
      "Reason in expected value, fold equity, and equity realization"
    ],
    "difficulty": "beginner",
    "estimatedLessons": 6,
    "stageId": "foundations",
    "order": 2,
    "prerequisiteModuleId": "poker-fundamentals-module",
    "contentStatus": "complete",
    "access": "free"
  },
  {
    "id": "preflop-foundation-module",
    "path_id": "beginner",
    "slug": "preflop-foundation-module",
    "title": "Building Your Preflop Foundation",
    "description": "Move from knowing what a range is to understanding how real preflop strategy is constructed.",
    "concept_ids": [
      "first_in",
      "rfi",
      "position_rfi",
      "players_behind",
      "preflop_hand_selection",
      "stack_depth_preflop",
      "preflop_sizing",
      "antes",
      "limping",
      "sb_first_in",
      "range_construction",
      "utg_rfi",
      "utg1_rfi",
      "utg2_rfi",
      "lj_rfi",
      "hj_rfi",
      "co_rfi",
      "btn_rfi",
      "shallow_stack_rfi",
      "mid_stack_rfi",
      "deep_stack_rfi"
    ],
    "unlock_after": [
      "math-foundations-module"
    ],
    "sort_order": 2,
    "xp_reward": 700,
    "subtitle": "Learn why position, ranges and stack depth determine which hands enter the pot.",
    "learningObjectives": [
      "Understand how position shapes which hands are profitable to play",
      "Reconstruct real MTT baseline opening strategies from every seat at 15bb-60bb",
      "See how stack depth, sizing, antes and rake reshape a preflop plan"
    ],
    "difficulty": "beginner",
    "estimatedLessons": 12,
    "stageId": "preflop-strategy",
    "order": 3,
    "prerequisiteModuleId": "math-foundations-module",
    "contentStatus": "complete",
    "access": "free"
  },
  {
    "id": "preflop-aggression-module",
    "path_id": "beginner",
    "slug": "preflop-aggression-module",
    "title": "Preflop Aggression",
    "description": "Move from \"should I enter the pot?\" to \"how should I respond when someone already has?\" — 3-bets, squeezes, 4-bets and the battle for initiative.",
    "concept_ids": [
      "three_bet",
      "three_bet_motives",
      "range_vs_range",
      "opener_range_strength",
      "three_bet_range_construction",
      "linear_range",
      "polarized",
      "calling_range_effect",
      "position_three_bet",
      "players_behind_aggression",
      "blockers",
      "card_removal",
      "three_bet_sizing",
      "squeeze",
      "facing_three_bet",
      "four_bet",
      "four_bet_bluff",
      "cold_four_bet",
      "five_bet",
      "rejam",
      "alpha_three_bet",
      "exploit_over_three_bet"
    ],
    "unlock_after": [
      "preflop-foundation-module"
    ],
    "sort_order": 3,
    "xp_reward": 800,
    "subtitle": "Understand 3-bets, 4-bets, squeezes and the battle for initiative.",
    "learningObjectives": [
      "Build and read 3-bet ranges as a function of the opener’s range, not just hand strength",
      "Distinguish linear from polarized construction and know when each applies",
      "Handle 4-bets, 5-bets, squeezes and short-stack rejams from both sides of the aggression"
    ],
    "difficulty": "beginner",
    "estimatedLessons": 11,
    "stageId": "preflop-strategy",
    "order": 4,
    "prerequisiteModuleId": "preflop-foundation-module",
    "contentStatus": "complete",
    "access": "free"
  },
  {
    "id": "defending-the-open-module",
    "path_id": "beginner",
    "slug": "defending-the-open-module",
    "title": "Defending the Open",
    "description": "Learn to defend from every seat — HJ, CO, BTN, SB and BB — building a complete fold/call/3-bet response to an open raise position by position, the same way you built your opening ranges.",
    "concept_ids": [
      "defending_opens",
      "opener_range_strength",
      "pot_odds_preflop",
      "equity_realization_preflop",
      "position_three_bet",
      "players_behind_aggression",
      "bb_defense",
      "sb_defense",
      "btn_defense",
      "domination",
      "suitedness_preflop",
      "connectedness_preflop",
      "pocket_pair_value",
      "stack_depth_defense",
      "range_adjustment",
      "range_construction"
    ],
    "unlock_after": [
      "preflop-aggression-module"
    ],
    "sort_order": 4,
    "xp_reward": 850,
    "subtitle": "I am in the CO. Someone opened. What do I do? Learn every seat's defense, one position at a time.",
    "learningObjectives": [
      "Build a complete fold/call/3-bet defense range from HJ, CO, BTN, SB and BB against a real open",
      "Judge a hand by how it performs against THIS open from THIS seat, not by raw strength alone",
      "Weigh price, equity realization, position, players behind and stack depth together before continuing"
    ],
    "difficulty": "beginner",
    "estimatedLessons": 9,
    "stageId": "preflop-strategy",
    "order": 5,
    "prerequisiteModuleId": "preflop-aggression-module",
    "contentStatus": "complete",
    "access": "free"
  },
  {
    "id": "flop-fundamentals-module",
    "path_id": "beginner",
    "slug": "flop-fundamentals-module",
    "title": "Understanding the Flop",
    "description": "Learn to read the board before deciding what to do on it — flop structure, texture, rank families, possible straights, static vs dynamic boards, and how a flop interacts with the ranges in play.",
    "concept_ids": [
      "flop_classification",
      "flop_structure",
      "flop_texture",
      "two_tone_subtypes",
      "flop_rank",
      "flop_families",
      "flopped_straights",
      "suit_isomorphism",
      "board_volatility",
      "static_dynamic",
      "range_board_interaction",
      "equity_buckets",
      "relative_hand_strength",
      "runout_awareness"
    ],
    "unlock_after": [
      "defending-the-open-module"
    ],
    "sort_order": 5,
    "xp_reward": 900,
    "subtitle": "Learn to read the board before deciding what to do on it.",
    "learningObjectives": [
      "Classify any flop by structure, suit texture, and rank family — and know exactly how many straights it can make",
      "Judge whether a board is likely to stay static or turn dynamic as more cards come",
      "See that the same flop does not affect every preflop range equally, and place a hand-vs-range equity into its bucket"
    ],
    "difficulty": "intermediate",
    "estimatedLessons": 9,
    "stageId": "postflop-foundations",
    "order": 6,
    "prerequisiteModuleId": "defending-the-open-module",
    "contentStatus": "complete",
    "access": "free"
  },
  {
    "id": "cbetting-fundamentals-module",
    "path_id": "beginner",
    "slug": "cbetting-fundamentals-module",
    "title": "C-Betting Fundamentals",
    "description": "Turn range advantage into pressure — move from \"should I bet?\" to reasoning about how two full ranges interact with a flop, and where your exact hand belongs inside that strategy.",
    "concept_ids": [
      "cbet_definition",
      "range_advantage",
      "range_composition",
      "equity_buckets",
      "strong_hand_density",
      "polarization_advantage",
      "cbet_frequency",
      "cbet_sizing",
      "equity_realization",
      "position_postflop",
      "ip_cbet",
      "oop_cbet",
      "checking_range",
      "range_protection",
      "cbet_hand_selection",
      "flop_range_strategy",
      "threebet_pot_cbet"
    ],
    "unlock_after": [
      "flop-fundamentals-module"
    ],
    "sort_order": 6,
    "xp_reward": 950,
    "subtitle": "Turn range advantage into pressure.",
    "learningObjectives": [
      "Judge how Hero's whole range interacts with a flop before asking what Hero's exact hand wants to do",
      "Read range composition (Strong/Good/Weak/Trash) rather than raw equity alone to explain a betting incentive",
      "Connect c-bet frequency and sizing to range advantage, polarization, and position instead of memorized rules"
    ],
    "difficulty": "intermediate",
    "estimatedLessons": 9,
    "stageId": "postflop-foundations",
    "order": 7,
    "prerequisiteModuleId": "flop-fundamentals-module",
    "contentStatus": "complete",
    "access": "free"
  },
  {
    "id": "range-vs-range-module",
    "path_id": "beginner",
    "slug": "range-vs-range-module",
    "title": "Range vs Range",
    "description": "Stop analyzing isolated hands and start seeing the entire strategy — how two full preflop ranges collide on a flop, why the preflop favorite can lose its edge, and why raw equity alone never tells the whole story.",
    "concept_ids": [
      "range_vs_range_equity",
      "board_texture_shift",
      "range_advantage",
      "equity_buckets",
      "range_composition",
      "strong_hand_density",
      "equity_bucket_distribution",
      "board_coverage",
      "preflop_raiser_advantage",
      "hand_vs_range_strength",
      "range_archaeology"
    ],
    "unlock_after": [
      "cbetting-fundamentals-module"
    ],
    "sort_order": 7,
    "xp_reward": 1520,
    "subtitle": "Stop analyzing isolated hands and start seeing the entire strategy.",
    "learningObjectives": [
      "Distinguish hand-vs-hand thinking from range-vs-range thinking, and recognize when a strong individual hand sits inside a weak overall range",
      "Read an Equity Bucket (Strong/Good/Weak/Trash) distribution and explain where a range's strong hands actually come from, not just its raw equity number",
      "Judge which preflop range a board favors and why that advantage can shift after the flop, without assuming \"range advantage\" always means \"bet\"",
      "Tell range advantage and nut advantage apart, and recognize when a single board hands one to each player instead of both to the same one"
    ],
    "difficulty": "intermediate",
    "estimatedLessons": 5,
    "stageId": "range-thinking",
    "order": 8,
    "prerequisiteModuleId": "cbetting-fundamentals-module",
    "contentStatus": "complete",
    "access": "free"
  },
  {
    "id": "blockers-module",
    "path_id": "intermediate",
    "slug": "blockers-module",
    "title": "Blockers & Card Removal",
    "description": "See the hands that disappear. Learn to reason about card removal at the level of concrete combinations — not just \"I hold a blocker\" — and why a blocker's value depends entirely on which part of an opponent's range it actually touches.",
    "concept_ids": [
      "card_removal",
      "combo_counting",
      "blocker_classification",
      "nut_blocker",
      "blocker_conditional_value"
    ],
    "unlock_after": [
      "range-vs-range-module"
    ],
    "sort_order": 8,
    "xp_reward": 1000,
    "subtitle": "See the hands that disappear.",
    "learningObjectives": [
      "Convert a hand-class (\"AA\", \"AK\") into its concrete 2-card combinations, and compute exactly how known cards remove some of them",
      "Distinguish removing an opponent's value combos from removing their bluff combos, and reason about what that does to a decision",
      "Recognize that a blocker's strategic value depends on which part of the opponent's range survives — not on the blocker card's rank alone"
    ],
    "difficulty": "intermediate",
    "estimatedLessons": 8,
    "stageId": "range-thinking",
    "order": 9,
    "prerequisiteModuleId": "range-vs-range-module",
    "contentStatus": "complete",
    "access": "free"
  },
  {
    "id": "game-theory-foundations-module",
    "path_id": "intermediate",
    "slug": "game-theory-foundations-module",
    "title": "Game Theory Foundations",
    "description": "Not a glossary of GTO terms — a strategy lab. Manipulate strategies, exploit mistakes, trigger counter-adjustments, and derive equilibrium and MDF yourself from the underlying EV logic.",
    "concept_ids": [
      "strategy_interdependence",
      "maximally_exploitative_strategy",
      "counter_exploitation",
      "nash_equilibrium_source",
      "indifference_principle",
      "clairvoyance_game",
      "alpha_mdf_derivation",
      "mdf_limitations"
    ],
    "unlock_after": [
      "blockers-module"
    ],
    "sort_order": 9,
    "xp_reward": 1000,
    "subtitle": "Understand what it means to build a strategy that cannot be easily exploited.",
    "learningObjectives": [
      "Explain why a strategy's value depends on how opponents respond to it, and trace the opponent-strategy → best-response → counter-response feedback loop that produces equilibrium",
      "Derive the Indifference Principle and Minimum Defense Frequency from explicit EV logic in a toy game — not memorize them as formulas",
      "Recognize what Nash equilibrium actually means (no player can improve by unilaterally changing strategy) and where MDF's simplifying assumptions stop applying"
    ],
    "difficulty": "intermediate",
    "estimatedLessons": 9,
    "stageId": "game-theory",
    "order": 10,
    "prerequisiteModuleId": "blockers-module",
    "contentStatus": "complete",
    "access": "free"
  },
  {
    "id": "polarized-module",
    "path_id": "intermediate",
    "slug": "polarized-module",
    "title": "Polarization & Range Construction",
    "description": "A range is not a list of hands — it is an ecosystem in which every combo has a strategic function. Learn why betting works at all, why a range's shape is relative (never fixed), why bluffs need an exact ratio and the right blockers, and why the hands you check need protecting just as much as the hands you bet.",
    "concept_ids": [
      "informational_advantage",
      "relative_range_shape",
      "capped_vs_condensed",
      "range_composition",
      "bluff_to_value_ratio",
      "protected_checking_range"
    ],
    "unlock_after": [
      "game-theory-foundations-module"
    ],
    "sort_order": 10,
    "xp_reward": 1000,
    "subtitle": "A range is an ecosystem, not a list — every hand has a job.",
    "learningObjectives": [
      "Explain why betting exists at all — leveraging the informational edge of knowing your exact hand, and realizing/denying equity — not a \"value bet vs. bluff\" binary",
      "Recognize that a range's shape (polarized/linear/condensed/capped/uncapped) is relative to a specific opponent and a specific moment, never a fixed label",
      "Reason about range composition (Equity Buckets) as a sharper, more reliable lens than a range's raw aggregate equity",
      "Derive the exact bluff-to-value ratio a polarized betting range needs from its bet-size (Alpha), and know when that math is exact (river) versus an approximation (flop/turn)",
      "Identify which specific hands belong in a protected checking range, and why a checking range with zero real strength becomes exploitable"
    ],
    "difficulty": "intermediate",
    "estimatedLessons": 5,
    "stageId": "game-theory",
    "order": 11,
    "prerequisiteModuleId": "game-theory-foundations-module",
    "access": "free"
  },
  {
    "id": "bet-sizing-language-module",
    "path_id": "intermediate",
    "slug": "bet-sizing-language-module",
    "title": "The Language of Bet Sizing",
    "description": "A bet-size is never chosen per-hand — it is one entry from a small menu a strategy commits to in advance. Learn what a size actually buys (pot odds, Alpha, MDF, value:bluff ratio, as one connected cascade), why a strategy abandons a size the instant it can be raised rather than using it less, why that abandonment costs surprisingly little EV on average, and why relative polarization — not hand strength — sets both the direction and size of every bet.",
    "concept_ids": [
      "sizing_as_action_abstraction",
      "alpha_size_dependence",
      "size_abandonment_mechanism",
      "simplification_ev_cost",
      "one_size_fits_board_caveat",
      "polarization_sizing_direction"
    ],
    "unlock_after": [
      "polarized-module"
    ],
    "sort_order": 11,
    "xp_reward": 1000,
    "subtitle": "A bet-size is a sentence, not a chip count — learn to read and construct its meaning.",
    "learningObjectives": [
      "State the formal definitions of bet-size, minbet, minraise, overbet, c-bet, and donk bet, and explain why a strategy must fix a finite menu of sizes before any specific hand is considered",
      "Compute, from any stated bet-size, the pot odds it offers, the resulting Alpha, the MDF it implies, and the value:bluff ratio a polarized range needs — as one connected cascade, not four separate facts",
      "Explain, using the book's own [0-1] Toy Game evidence, why a strategy abandons a bet-size entirely the instant it can be safely raised, rather than simply using it less often",
      "State the book's own quantified EV cost of simplifying to a single bet-size, and identify the specific, nameable exceptions (the all-in size, low SPR) where that default stops applying",
      "Predict a strategy's sizing direction — from pure-check to all-in-dominant — directly from a range's polarization relative to its opponent's, without needing raw equity numbers"
    ],
    "difficulty": "intermediate",
    "estimatedLessons": 5,
    "stageId": "bet-sizing-defense",
    "order": 12,
    "prerequisiteModuleId": "polarized-module",
    "access": "free"
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "defending-bets-module",
    "path_id": "intermediate",
    "slug": "defending-bets-module",
    "title": "Defending Against Bets",
    "subtitle": "Learn how calling, folding and raising interact with an opponent's betting strategy.",
    "description": "Teach the defender's side of the sizing conversation from Module 11.",
    "learningObjectives": [
      "Apply minimum defense frequency against different bet sizes",
      "Choose bluff-catchers, value raises and bluff raises deliberately",
      "Build a full range-defense plan rather than single-hand reactions"
    ],
    "difficulty": "intermediate",
    "stageId": "bet-sizing-defense",
    "order": 13,
    "prerequisiteModuleId": "bet-sizing-language-module",
    "plannedLessons": [
      {
        "title": "Facing Small Bets"
      },
      {
        "title": "Facing Large Bets"
      },
      {
        "title": "MDF Revisited"
      },
      {
        "title": "Bluff Catchers"
      },
      {
        "title": "Calling Thresholds"
      },
      {
        "title": "Raising for Value"
      },
      {
        "title": "Raising as a Bluff"
      },
      {
        "title": "Check-Raising"
      },
      {
        "title": "Range Defense"
      },
      {
        "title": "Defense Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "flop-strategy-module",
    "path_id": "intermediate",
    "slug": "flop-strategy-module",
    "title": "Flop Strategy",
    "subtitle": "Build complete flop strategies from ranges, boards and bet sizes.",
    "description": "Move from flop fundamentals into serious strategic construction.",
    "learningObjectives": [
      "Build IP and OOP flop strategies across different board types",
      "Use multiple bet sizes and check-raises as part of one coherent plan",
      "Practice full flop range construction, not isolated decisions"
    ],
    "difficulty": "intermediate",
    "stageId": "street-mastery",
    "order": 14,
    "prerequisiteModuleId": "defending-bets-module",
    "plannedLessons": [
      {
        "title": "IP C-Betting"
      },
      {
        "title": "OOP Strategy"
      },
      {
        "title": "High-Card Boards"
      },
      {
        "title": "Low Connected Boards"
      },
      {
        "title": "Paired Boards"
      },
      {
        "title": "Monotone Boards"
      },
      {
        "title": "Check-Raising"
      },
      {
        "title": "Multi-Sizing Strategy"
      },
      {
        "title": "Flop Range Construction"
      },
      {
        "title": "Flop Decision Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "turn-strategy-module",
    "path_id": "intermediate",
    "slug": "turn-strategy-module",
    "title": "Turn Strategy",
    "subtitle": "Learn how one card transforms ranges and future betting plans.",
    "description": "Extend range and sizing thinking onto the turn.",
    "learningObjectives": [
      "Distinguish range-changing turns, blank turns and scare cards",
      "Choose between double barreling and delayed c-betting",
      "Start planning the river while still on the turn"
    ],
    "difficulty": "intermediate",
    "stageId": "street-mastery",
    "order": 15,
    "prerequisiteModuleId": "flop-strategy-module",
    "plannedLessons": [
      {
        "title": "How Turns Change Equity"
      },
      {
        "title": "Range-Changing Turns"
      },
      {
        "title": "Blank Turns"
      },
      {
        "title": "Scare Cards"
      },
      {
        "title": "Double Barreling"
      },
      {
        "title": "Delayed C-Betting"
      },
      {
        "title": "Turn Check-Raising"
      },
      {
        "title": "Turn Overbets"
      },
      {
        "title": "Planning the River"
      },
      {
        "title": "Turn Decision Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "river-strategy-module",
    "path_id": "intermediate",
    "slug": "river-strategy-module",
    "title": "River Strategy",
    "subtitle": "Master the street where equity becomes final and ranges become most polarized.",
    "description": "Apply everything learned to the final, most polarized street.",
    "learningObjectives": [
      "Separate thin value bets from bluffs and bluff-catches on the river",
      "Choose river bluffs deliberately using blockers",
      "Handle polarized overbets from both sides of the pot"
    ],
    "difficulty": "intermediate",
    "stageId": "street-mastery",
    "order": 16,
    "prerequisiteModuleId": "turn-strategy-module",
    "plannedLessons": [
      {
        "title": "River Fundamentals"
      },
      {
        "title": "Value Betting"
      },
      {
        "title": "Thin Value"
      },
      {
        "title": "Bluff Catching"
      },
      {
        "title": "Choosing Bluffs"
      },
      {
        "title": "Blockers on the River"
      },
      {
        "title": "Polarized River Betting"
      },
      {
        "title": "River Overbets"
      },
      {
        "title": "Facing Polarization"
      },
      {
        "title": "River Decision Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "multistreet-planning-module",
    "path_id": "intermediate",
    "slug": "multistreet-planning-module",
    "title": "Multi-Street Planning",
    "subtitle": "Stop making isolated decisions and start planning complete hands.",
    "description": "Teach strategic continuity across flop, turn and river.",
    "learningObjectives": [
      "Plan a hand at least one street ahead instead of street-by-street",
      "Identify barrel and give-up candidates as a range evolves",
      "Build a full river range from a flop and turn plan"
    ],
    "difficulty": "intermediate",
    "stageId": "multi-street-poker",
    "order": 17,
    "prerequisiteModuleId": "river-strategy-module",
    "plannedLessons": [
      {
        "title": "Thinking One Street Ahead"
      },
      {
        "title": "Range Evolution"
      },
      {
        "title": "Barrel Candidates"
      },
      {
        "title": "Give-Up Candidates"
      },
      {
        "title": "Future Runouts"
      },
      {
        "title": "Planning Bet Sizes"
      },
      {
        "title": "Building River Ranges"
      },
      {
        "title": "Multi-Street Bluffing"
      },
      {
        "title": "Multi-Street Value Lines"
      },
      {
        "title": "Full Hand Simulation Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "three-bet-pots-module",
    "path_id": "advanced",
    "slug": "three-bet-pots-module",
    "title": "3-Bet Pots",
    "subtitle": "Learn how compressed ranges and lower SPR change postflop strategy.",
    "description": "Apply range and sizing theory to the structurally distinct 3-bet pot.",
    "learningObjectives": [
      "Recognize how 3-bet pot ranges and SPR differ from single-raised pots",
      "Build IP and OOP 3-bet pot strategies across streets",
      "Adjust c-betting and checking frequencies for compressed ranges"
    ],
    "difficulty": "advanced",
    "stageId": "special-pot-types",
    "order": 18,
    "prerequisiteModuleId": "multistreet-planning-module",
    "plannedLessons": [
      {
        "title": "Anatomy of a 3-Bet Pot"
      },
      {
        "title": "Range Structure"
      },
      {
        "title": "SPR Changes"
      },
      {
        "title": "IP 3-Bet Pots"
      },
      {
        "title": "OOP 3-Bet Pots"
      },
      {
        "title": "C-Betting"
      },
      {
        "title": "Checking"
      },
      {
        "title": "Turn Strategy"
      },
      {
        "title": "River Strategy"
      },
      {
        "title": "3-Bet Pot Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "four-bet-pots-module",
    "path_id": "advanced",
    "slug": "four-bet-pots-module",
    "title": "4-Bet Pots",
    "subtitle": "Navigate narrow ranges, low SPR and high-value decisions.",
    "description": "Extend special-pot-type theory to the even more compressed 4-bet pot.",
    "learningObjectives": [
      "Reason about very low SPR postflop decisions",
      "Set stack-off thresholds for narrow, high-value ranges",
      "Identify where bluffing still belongs in a 4-bet pot"
    ],
    "difficulty": "advanced",
    "stageId": "special-pot-types",
    "order": 19,
    "prerequisiteModuleId": "three-bet-pots-module",
    "plannedLessons": [
      {
        "title": "4-Bet Pot Ranges"
      },
      {
        "title": "Low SPR Strategy"
      },
      {
        "title": "Range Advantage"
      },
      {
        "title": "Small C-Bets"
      },
      {
        "title": "Checking"
      },
      {
        "title": "Stack-Off Thresholds"
      },
      {
        "title": "Turn Decisions"
      },
      {
        "title": "River Decisions"
      },
      {
        "title": "Bluffing in 4-Bet Pots"
      },
      {
        "title": "4-Bet Pot Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "blind-vs-blind-module",
    "path_id": "advanced",
    "slug": "blind-vs-blind-module",
    "title": "Blind vs Blind",
    "subtitle": "Master the widest ranges in poker.",
    "description": "Apply the full toolkit to the widest-range pot type in poker.",
    "learningObjectives": [
      "Adjust standard theory for the unusually wide blind-vs-blind ranges",
      "Compare limping, raising and defending approaches from the blinds",
      "Carry range- and nut-advantage thinking through to the river in wide pots"
    ],
    "difficulty": "advanced",
    "stageId": "special-pot-types",
    "order": 20,
    "prerequisiteModuleId": "four-bet-pots-module",
    "plannedLessons": [
      {
        "title": "Why Blind vs Blind Is Different"
      },
      {
        "title": "Small Blind Opening"
      },
      {
        "title": "Big Blind Defense"
      },
      {
        "title": "Limp Strategies"
      },
      {
        "title": "Raising vs Limp"
      },
      {
        "title": "Wide Range Postflop Play"
      },
      {
        "title": "Range Advantage"
      },
      {
        "title": "Aggression"
      },
      {
        "title": "River Strategy"
      },
      {
        "title": "Blind Battle Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "short-stack-strategy-module",
    "path_id": "advanced",
    "slug": "short-stack-strategy-module",
    "title": "Short-Stack Strategy",
    "subtitle": "Learn how shrinking stacks transform ranges and decision thresholds.",
    "description": "Apply strategy across the shrinking-stack side of the SPR spectrum.",
    "learningObjectives": [
      "Adjust ranges and thresholds across 40bb, 30bb, 20bb and 15bb depths",
      "Reason about shove/fold and rejamming decisions",
      "Simplify postflop play appropriately at low SPR"
    ],
    "difficulty": "advanced",
    "stageId": "stack-depth",
    "order": 21,
    "prerequisiteModuleId": "blind-vs-blind-module",
    "plannedLessons": [
      {
        "title": "Stack Depth Revisited"
      },
      {
        "title": "40bb Strategy"
      },
      {
        "title": "30bb Strategy"
      },
      {
        "title": "20bb Strategy"
      },
      {
        "title": "15bb Strategy"
      },
      {
        "title": "Shove / Fold Concepts"
      },
      {
        "title": "Rejamming"
      },
      {
        "title": "Low-SPR Postflop"
      },
      {
        "title": "Short-Stack Adjustments"
      },
      {
        "title": "Short-Stack Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "deep-stack-strategy-module",
    "path_id": "advanced",
    "slug": "deep-stack-strategy-module",
    "title": "Deep-Stack Strategy",
    "subtitle": "Learn why deep stacks increase the importance of position, nuttiness and future streets.",
    "description": "Apply strategy across the deep-stack side of the SPR spectrum.",
    "learningObjectives": [
      "Explain why nut potential and position matter more as stacks get deeper",
      "Reason about reverse implied odds in large, deep-stacked pots",
      "Use river leverage deliberately when building deep-stack bluffing lines"
    ],
    "difficulty": "advanced",
    "stageId": "stack-depth",
    "order": 22,
    "prerequisiteModuleId": "short-stack-strategy-module",
    "plannedLessons": [
      {
        "title": "Deep Stack Fundamentals"
      },
      {
        "title": "SPR at Depth"
      },
      {
        "title": "Nut Potential"
      },
      {
        "title": "Reverse Implied Odds"
      },
      {
        "title": "Position"
      },
      {
        "title": "Suited / Connected Hands"
      },
      {
        "title": "Large Pots"
      },
      {
        "title": "Deep-Stack Bluffing"
      },
      {
        "title": "River Leverage"
      },
      {
        "title": "Deep-Stack Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "tournament-foundations-module",
    "path_id": "advanced",
    "slug": "tournament-foundations-module",
    "title": "Tournament Foundations",
    "subtitle": "Understand how changing stacks and tournament structure reshape poker strategy.",
    "description": "Introduce the tournament-specific pressures that don't exist in cash play.",
    "learningObjectives": [
      "Explain how antes and shrinking stacks change strategy over a tournament",
      "Weigh survival against chip accumulation at different stages",
      "Recognize short-stack pressure and rejam dynamics at the table"
    ],
    "difficulty": "advanced",
    "stageId": "tournament-poker",
    "order": 23,
    "prerequisiteModuleId": "deep-stack-strategy-module",
    "plannedLessons": [
      {
        "title": "Tournament Stack Dynamics"
      },
      {
        "title": "Antes"
      },
      {
        "title": "Stack Preservation"
      },
      {
        "title": "Short-Stack Pressure"
      },
      {
        "title": "Rejams"
      },
      {
        "title": "Table Dynamics"
      },
      {
        "title": "Tournament Stages"
      },
      {
        "title": "Chip Accumulation"
      },
      {
        "title": "Survival vs Growth"
      },
      {
        "title": "Tournament Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "icm-module",
    "path_id": "advanced",
    "slug": "icm-module",
    "title": "ICM",
    "subtitle": "Learn why tournament chips do not always equal tournament value.",
    "description": "Teach the conversion from chip stacks to real tournament equity near pay jumps.",
    "learningObjectives": [
      "Explain the difference between chip EV and money EV",
      "Apply risk premium and bubble pressure to calling/shoving decisions",
      "Adjust ranges by stack size at a final table"
    ],
    "difficulty": "advanced",
    "stageId": "tournament-poker",
    "order": 24,
    "prerequisiteModuleId": "tournament-foundations-module",
    "plannedLessons": [
      {
        "title": "What Is ICM?"
      },
      {
        "title": "Chip EV vs Money EV"
      },
      {
        "title": "Risk Premium"
      },
      {
        "title": "Bubble Pressure"
      },
      {
        "title": "Calling vs Shoving"
      },
      {
        "title": "Big Stack Pressure"
      },
      {
        "title": "Medium Stack Dynamics"
      },
      {
        "title": "Short Stack Dynamics"
      },
      {
        "title": "Final Tables"
      },
      {
        "title": "ICM Decision Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "population-exploits-module",
    "path_id": "advanced",
    "slug": "population-exploits-module",
    "title": "Population Exploits",
    "subtitle": "Learn how to profit when opponents systematically deviate from strong strategy.",
    "description": "Teach exploitation only after a strong theoretical GTO baseline is in place.",
    "learningObjectives": [
      "Compare a GTO baseline against common population tendencies",
      "Recognize over-folding, over-calling, over- and under-bluffing patterns",
      "Adjust preflop and postflop ranges to exploit systematic population leaks"
    ],
    "difficulty": "advanced",
    "stageId": "exploitative-poker",
    "order": 25,
    "prerequisiteModuleId": "icm-module",
    "plannedLessons": [
      {
        "title": "GTO Baseline vs Exploitation"
      },
      {
        "title": "Population Tendencies"
      },
      {
        "title": "Overfolding"
      },
      {
        "title": "Underfolding"
      },
      {
        "title": "Underbluffing"
      },
      {
        "title": "Overbluffing"
      },
      {
        "title": "Sizing Tendencies"
      },
      {
        "title": "Preflop Population Leaks"
      },
      {
        "title": "Postflop Population Leaks"
      },
      {
        "title": "Exploit Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "player-exploitation-module",
    "path_id": "advanced",
    "slug": "player-exploitation-module",
    "title": "Player-Specific Exploitation",
    "subtitle": "Turn reliable opponent tendencies into targeted strategic adjustments.",
    "description": "Move from population-level exploits to individual, reliable reads.",
    "learningObjectives": [
      "Judge sample size and confidence before committing to an exploit",
      "Adjust value ranges, bluffing and calling against a specific opponent",
      "Know when and how to return to a balanced baseline"
    ],
    "difficulty": "advanced",
    "stageId": "exploitative-poker",
    "order": 26,
    "prerequisiteModuleId": "population-exploits-module",
    "plannedLessons": [
      {
        "title": "Identifying Reliable Leaks"
      },
      {
        "title": "Sample Size"
      },
      {
        "title": "Exploit Confidence"
      },
      {
        "title": "Adjusting Value Ranges"
      },
      {
        "title": "Adjusting Bluffing"
      },
      {
        "title": "Adjusting Calls"
      },
      {
        "title": "Adjusting Bet Sizes"
      },
      {
        "title": "Counter-Exploitation"
      },
      {
        "title": "Returning to Baseline"
      },
      {
        "title": "Exploit Decision Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "think-like-solver-module",
    "path_id": "pro",
    "slug": "think-like-solver-module",
    "title": "Think Like a Solver",
    "subtitle": "Learn to predict strategy instead of memorizing outputs.",
    "description": "One of the final transformations of the Poker Journey — reasoning toward solver-like strategies using everything learned previously. The learner predicts a frequency, size or range first, then compares it against a reference strategy.",
    "learningObjectives": [
      "Predict betting and checking ranges before seeing a reference solve",
      "Reason about game-tree construction and range constraints",
      "Read and interpret mixed-strategy solver output"
    ],
    "difficulty": "elite",
    "stageId": "elite-strategy",
    "order": 27,
    "prerequisiteModuleId": "player-exploitation-module",
    "plannedLessons": [
      {
        "title": "What Solvers Actually Solve"
      },
      {
        "title": "Building the Game Tree"
      },
      {
        "title": "Ranges and Constraints"
      },
      {
        "title": "Predict the Frequency"
      },
      {
        "title": "Predict the Bet Size"
      },
      {
        "title": "Predict the Betting Range"
      },
      {
        "title": "Predict the Checking Range"
      },
      {
        "title": "Reading Solver Output"
      },
      {
        "title": "Understanding Mixed Strategies"
      },
      {
        "title": "Solver Prediction Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "range-reconstruction-module",
    "path_id": "pro",
    "slug": "range-reconstruction-module",
    "title": "Advanced Range Reconstruction",
    "subtitle": "Rebuild an opponent's range from every decision they made.",
    "description": "Apply filtering street-by-street to rebuild a complete, weighted opponent range.",
    "learningObjectives": [
      "Filter a starting range through preflop, flop, turn and river action",
      "Apply combination removal and frequency weighting to a final range",
      "Judge bluff density and value density in a reconstructed range"
    ],
    "difficulty": "elite",
    "stageId": "elite-strategy",
    "order": 28,
    "prerequisiteModuleId": "think-like-solver-module",
    "plannedLessons": [
      {
        "title": "Starting Range"
      },
      {
        "title": "Preflop Filtering"
      },
      {
        "title": "Flop Filtering"
      },
      {
        "title": "Turn Filtering"
      },
      {
        "title": "River Range"
      },
      {
        "title": "Combination Removal"
      },
      {
        "title": "Frequency Weighting"
      },
      {
        "title": "Bluff Density"
      },
      {
        "title": "Value Density"
      },
      {
        "title": "Full Range Reconstruction Lab"
      }
    ]
  },
  {
    "concept_ids": [],
    "unlock_after": [],
    "sort_order": 0,
    "xp_reward": 0,
    "estimatedLessons": 10,
    "contentStatus": "planned",
    "access": "free",
    "id": "elite-decision-making-module",
    "path_id": "pro",
    "slug": "elite-decision-making-module",
    "title": "Elite Decision Making",
    "subtitle": "Combine every major poker concept into complete strategic reasoning.",
    "description": "The final core module — full hand simulations that progressively build a decision from ranges and SPR up to the highest-EV strategy, rather than jumping straight to an answer.",
    "learningObjectives": [
      "Work a hand from range advantage through SPR to sizing, in order",
      "Integrate blockers, polarization and multi-street planning into one decision",
      "Reach a highest-EV strategy through progressive reasoning, not memorized rules"
    ],
    "difficulty": "elite",
    "stageId": "elite-strategy",
    "order": 29,
    "prerequisiteModuleId": "range-reconstruction-module",
    "plannedLessons": [
      {
        "title": "What Are the Ranges?"
      },
      {
        "title": "Who Has Range Advantage?"
      },
      {
        "title": "Who Has Nut Advantage?"
      },
      {
        "title": "What Is the SPR?"
      },
      {
        "title": "Which Hands Want Value?"
      },
      {
        "title": "Which Hands Can Bluff?"
      },
      {
        "title": "Which Blockers Matter?"
      },
      {
        "title": "What Sizing Makes Strategic Sense?"
      },
      {
        "title": "What Happens on Future Streets?"
      },
      {
        "title": "What Is the Highest-EV Strategy?"
      }
    ]
  }
]

export const LEARNING_PATHS: LearningPath[] = [
  {
    "id": "beginner",
    "title": "Foundations",
    "description": "Master the fundamentals of poker strategy",
    "tier_required": "free",
    "sort_order": 1
  },
  {
    "id": "intermediate",
    "title": "Range Thinking",
    "description": "Think in ranges and dominate postflop",
    "tier_required": "pro",
    "sort_order": 2
  },
  {
    "id": "advanced",
    "title": "GTO Mastery",
    "description": "Exploit-proof your game with game theory",
    "tier_required": "premium",
    "sort_order": 3
  },
  {
    "id": "pro",
    "title": "Pro / Elite",
    "description": "Solver-level thinking, ICM mastery, and exploit balancing for serious players",
    "tier_required": "premium",
    "sort_order": 4
  }
]

export const LESSONS_BY_SLUG: Record<string, PublicLesson> =
  Object.fromEntries(PUBLIC_LESSONS.map((l) => [l.slug, l]))

/** Keyed by lesson.id — the identifier persisted to progress records (see
 *  curriculum.ts's own LESSONS_BY_ID docstring; never substitute
 *  LESSONS_BY_SLUG for this). */
export const LESSONS_BY_ID: Record<string, PublicLesson> =
  Object.fromEntries(PUBLIC_LESSONS.map((l) => [l.id, l]))

export const MODULES_BY_SLUG: Record<string, LearningModule> =
  Object.fromEntries(LEARNING_MODULES.map((m) => [m.slug, m]))

/** module_id -> lessons in that module */
export const LESSONS_BY_MODULE: Record<string, PublicLesson[]> =
  PUBLIC_LESSONS.reduce<Record<string, PublicLesson[]>>((acc, l) => {
    if (!acc[l.module_id]) acc[l.module_id] = []
    acc[l.module_id].push(l)
    return acc
  }, {})

/** path_id -> modules in that path */
export const MODULES_BY_PATH: Record<string, LearningModule[]> =
  LEARNING_MODULES.reduce<Record<string, LearningModule[]>>((acc, m) => {
    if (!acc[m.path_id]) acc[m.path_id] = []
    acc[m.path_id].push(m)
    return acc
  }, {})
