/**
 * Poker Journey — Curriculum Roadmap Skeleton
 *
 * The complete 13-stage / 28-module linear "Poker Academy" roadmap. Stages 2–13
 * (Modules 3–28) are roadmap-only: metadata, ordering, prerequisites, and
 * "Coming Soon" descriptors — no playable lesson content yet. Stage 1
 * (Modules 1–2) already lives in ./curriculum.ts and is only referenced here
 * by id for stage grouping.
 *
 * Do not add `Lesson`/`LessonStep` objects here — `plannedLessons` is a
 * display-only descriptor list, never routed into the lesson player.
 */

import type { JourneyStage, LearningModule } from './types'

// ── Stages ────────────────────────────────────────────────────────────────────

export const JOURNEY_STAGES: JourneyStage[] = [
  {
    id: 'foundations',
    order: 1,
    title: 'Foundations',
    subtitle: 'Learn the language.',
    moduleIds: ['poker-fundamentals-module', 'math-foundations-module'],
  },
  {
    id: 'preflop-strategy',
    order: 2,
    title: 'Preflop Strategy',
    subtitle: 'Learn how ranges begin.',
    moduleIds: ['preflop-foundation-module', 'preflop-aggression-module', 'defending-the-open-module'],
  },
  {
    id: 'postflop-foundations',
    order: 3,
    title: 'Postflop Foundations',
    subtitle: 'Learn how boards transform ranges.',
    moduleIds: ['flop-fundamentals-module', 'betting-checking-module'],
  },
  {
    id: 'range-thinking',
    order: 4,
    title: 'Range Thinking',
    subtitle: 'Learn to reason with complete strategies.',
    moduleIds: ['range-vs-range-module', 'blockers-module'],
  },
  {
    id: 'game-theory',
    order: 5,
    title: 'Game Theory',
    subtitle: 'Learn why balanced strategies work.',
    moduleIds: ['game-theory-foundations-module', 'polarized-module'],
  },
  {
    id: 'bet-sizing-defense',
    order: 6,
    title: 'Bet Sizing & Defense',
    subtitle: 'Learn how range structure determines aggression.',
    moduleIds: ['bet-sizing-language-module', 'defending-bets-module'],
  },
  {
    id: 'street-mastery',
    order: 7,
    title: 'Street Mastery',
    subtitle: 'Apply those ideas across flop, turn and river.',
    moduleIds: ['flop-strategy-module', 'turn-strategy-module', 'river-strategy-module'],
  },
  {
    id: 'multi-street-poker',
    order: 8,
    title: 'Multi-Street Poker',
    subtitle: 'Connect decisions across the entire hand.',
    moduleIds: ['multistreet-planning-module'],
  },
  {
    id: 'special-pot-types',
    order: 9,
    title: 'Special Pot Types',
    subtitle: 'Adapt to different pot structures.',
    moduleIds: ['three-bet-pots-module', 'four-bet-pots-module', 'blind-vs-blind-module'],
  },
  {
    id: 'stack-depth',
    order: 10,
    title: 'Stack Depth',
    subtitle: 'Adapt strategy to changing stack sizes.',
    moduleIds: ['short-stack-strategy-module', 'deep-stack-strategy-module'],
  },
  {
    id: 'tournament-poker',
    order: 11,
    title: 'Tournament Poker',
    subtitle: 'Adapt strategy to changing incentives.',
    moduleIds: ['tournament-foundations-module', 'icm-module'],
  },
  {
    id: 'exploitative-poker',
    order: 12,
    title: 'Exploitative Poker',
    subtitle: 'Punish systematic mistakes.',
    moduleIds: ['population-exploits-module', 'player-exploitation-module'],
  },
  {
    id: 'elite-strategy',
    order: 13,
    title: 'Elite Strategy',
    subtitle: 'Reason like a solver instead of memorizing one.',
    moduleIds: ['think-like-solver-module', 'range-reconstruction-module', 'elite-decision-making-module'],
  },
]

// ── Roadmap modules (Modules 3–28) ───────────────────────────────────────────

/** Shared defaults for every roadmap-only module — overridden per-module below. */
const ROADMAP_DEFAULTS = {
  concept_ids: [] as string[],
  unlock_after: [] as string[],
  sort_order: 0,
  xp_reward: 0,
  estimatedLessons: 10,
  contentStatus: 'planned' as const,
  access: 'free' as const,
}

export const ROADMAP_MODULES: LearningModule[] = [
  // ── Stage 2 — Preflop Strategy ──────────────────────────────────────────────
  // preflop-foundation-module, preflop-aggression-module and
  // defending-the-open-module have all been promoted to real content — see
  // `LEARNING_MODULES` in ./curriculum.ts (same pattern Modules 1/2 went through).

  // ── Stage 3 — Postflop Foundations ──────────────────────────────────────────
  {
    ...ROADMAP_DEFAULTS,
    id: 'flop-fundamentals-module',
    path_id: 'intermediate',
    slug: 'flop-fundamentals-module',
    title: 'Understanding the Flop',
    subtitle: 'Learn how the board changes the relationship between two ranges.',
    description: 'Introduce the foundations of postflop strategy.',
    learningObjectives: [
      'Classify boards as dry/wet and static/dynamic',
      'Identify which range has the advantage on a given flop',
      'Connect board texture to a first, simple continuation-betting framework',
    ],
    difficulty: 'intermediate',
    stageId: 'postflop-foundations',
    order: 6,
    prerequisiteModuleId: 'defending-the-open-module',
    plannedLessons: [
      { title: 'Reading Board Texture' },
      { title: 'Dry vs Wet Boards' },
      { title: 'Static vs Dynamic Boards' },
      { title: 'Range Interaction' },
      { title: 'Range Advantage' },
      { title: 'Nut Advantage' },
      { title: 'Who Has the Stronger Range?' },
      { title: 'Introduction to Continuation Betting' },
      { title: 'Why We Check' },
      { title: 'Flop Strategy Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'betting-checking-module',
    path_id: 'intermediate',
    slug: 'betting-checking-module',
    title: 'Betting & Checking',
    subtitle: 'Understand why strong strategies need both bets and checks.',
    description: 'Teach the strategic purpose behind betting rather than treating betting as simply "I have a good hand."',
    learningObjectives: [
      'Separate the value, bluff, protection and equity-denial purposes of a bet',
      'Understand why strong and medium hands sometimes check',
      'Start building a checking range, not just a betting range',
    ],
    difficulty: 'intermediate',
    stageId: 'postflop-foundations',
    order: 7,
    prerequisiteModuleId: 'flop-fundamentals-module',
    plannedLessons: [
      { title: 'Why Do We Bet?' },
      { title: 'Betting for Value' },
      { title: 'Bluffing' },
      { title: 'Protection' },
      { title: 'Denying Equity' },
      { title: 'Checking Strong Hands' },
      { title: 'Checking Medium-Strength Hands' },
      { title: 'Betting Frequencies' },
      { title: 'Building a Checking Range' },
      { title: 'Bet or Check Decision Lab' },
    ],
  },

  // ── Stage 4 — Range Thinking ─────────────────────────────────────────────────
  {
    ...ROADMAP_DEFAULTS,
    id: 'range-vs-range-module',
    path_id: 'intermediate',
    slug: 'range-vs-range-module',
    title: 'Range vs Range',
    subtitle: 'Stop analyzing isolated hands and start seeing the entire strategy.',
    description: 'Deepen the range-thinking foundation introduced in Module 1.',
    learningObjectives: [
      'Construct and weight a full range rather than a single hand',
      'Compare range composition, distribution and nut density between two ranges',
      'See how actions taken so far transform what a range can still contain',
    ],
    difficulty: 'intermediate',
    stageId: 'range-thinking',
    order: 8,
    prerequisiteModuleId: 'betting-checking-module',
    plannedLessons: [
      { title: 'Constructing a Range' },
      { title: 'Weighted Ranges' },
      { title: 'Range Composition' },
      { title: 'Range Equity' },
      { title: 'Range Distribution' },
      { title: 'Range Advantage Revisited' },
      { title: 'Nut Distribution' },
      { title: 'Capped and Uncapped Ranges' },
      { title: 'How Actions Transform Ranges' },
      { title: 'Range Reconstruction Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'blockers-module',
    path_id: 'intermediate',
    slug: 'blockers-module',
    title: 'Blockers & Card Removal',
    subtitle: 'Learn how the cards you hold change what your opponent can have.',
    description: 'Take the introductory blocker concept from Module 1 and turn it into a strategic tool.',
    learningObjectives: [
      'Use card removal to judge which value hands and bluffs a blocker supports',
      'Apply blocker logic separately preflop and on the river',
      'Recognize when blockers matter less than raw hand strength',
    ],
    difficulty: 'intermediate',
    stageId: 'range-thinking',
    order: 9,
    prerequisiteModuleId: 'range-vs-range-module',
    plannedLessons: [
      { title: 'Card Removal Revisited' },
      { title: 'Blocking Value Hands' },
      { title: 'Blocking Bluffs' },
      { title: 'Unblocking Folds' },
      { title: 'Bluff Blockers' },
      { title: 'Bluff-Catching Blockers' },
      { title: 'Preflop Blockers' },
      { title: 'River Blockers' },
      { title: 'When Blockers Matter Less' },
      { title: 'Blocker Decision Lab' },
    ],
  },

  // ── Stage 5 — Game Theory ────────────────────────────────────────────────────
  {
    ...ROADMAP_DEFAULTS,
    id: 'game-theory-foundations-module',
    path_id: 'intermediate',
    slug: 'game-theory-foundations-module',
    title: 'Game Theory Foundations',
    subtitle: 'Understand what it means to build a strategy that cannot be easily exploited.',
    description: 'Introduce game-theoretic poker without turning the module into an abstract mathematics course.',
    learningObjectives: [
      'Explain exploitation and counter-exploitation in plain terms',
      'Understand indifference and why mixed strategies exist',
      'Connect minimum defense frequency to an intuitive sense of equilibrium',
    ],
    difficulty: 'intermediate',
    stageId: 'game-theory',
    order: 10,
    prerequisiteModuleId: 'blockers-module',
    plannedLessons: [
      { title: 'What Is Game Theory?' },
      { title: 'Exploitation' },
      { title: 'Counter-Exploitation' },
      { title: 'Balanced Strategy' },
      { title: 'Indifference' },
      { title: 'Mixed Strategies' },
      { title: 'Frequencies' },
      { title: 'Minimum Defense Frequency' },
      { title: 'Equilibrium Intuition' },
      { title: 'GTO Decision Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'polarized-module',
    path_id: 'intermediate',
    slug: 'polarized-module',
    title: 'Polarization & Range Construction',
    subtitle: 'Learn how value hands, bluffs and medium-strength hands form betting ranges.',
    description: 'Teach the architecture of strategically sound betting ranges.',
    learningObjectives: [
      'Distinguish polarized, linear and merged betting range structures',
      'Reason about bluff-to-value ratios inside a betting range',
      'Match range structure to bet size across a hand',
    ],
    difficulty: 'intermediate',
    stageId: 'game-theory',
    order: 11,
    prerequisiteModuleId: 'game-theory-foundations-module',
    plannedLessons: [
      { title: 'Polarization Revisited' },
      { title: 'Value Regions' },
      { title: 'Bluff Regions' },
      { title: 'Medium-Strength Hands' },
      { title: 'Bluff-to-Value Relationships' },
      { title: 'Thin Value' },
      { title: 'Merged / Linear Betting' },
      { title: 'Polarized Betting' },
      { title: 'Range Construction by Bet Size' },
      { title: 'Build the Betting Range Lab' },
    ],
  },

  // ── Stage 6 — Bet Sizing & Defense ──────────────────────────────────────────
  {
    ...ROADMAP_DEFAULTS,
    id: 'bet-sizing-language-module',
    path_id: 'intermediate',
    slug: 'bet-sizing-language-module',
    title: 'The Language of Bet Sizing',
    subtitle: 'Learn why different range structures want different bet sizes.',
    description: 'Move beyond "bet small" or "bet big" rules and teach why sizing exists.',
    learningObjectives: [
      'Explain what a bet size is actually trying to accomplish',
      'Connect range/nut advantage and polarization to sizing choice',
      'Reason about when a strategy wants multiple bet sizes at once',
    ],
    difficulty: 'intermediate',
    stageId: 'bet-sizing-defense',
    order: 12,
    prerequisiteModuleId: 'polarized-module',
    plannedLessons: [
      { title: 'What Bet Size Accomplishes' },
      { title: 'Small Bets' },
      { title: 'Medium Bets' },
      { title: 'Large Bets' },
      { title: 'Overbets' },
      { title: 'Range Advantage and Sizing' },
      { title: 'Nut Advantage and Sizing' },
      { title: 'Polarization and Sizing' },
      { title: 'Multiple Bet Sizes' },
      { title: 'Bet Sizing Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'defending-bets-module',
    path_id: 'intermediate',
    slug: 'defending-bets-module',
    title: 'Defending Against Bets',
    subtitle: 'Learn how calling, folding and raising interact with an opponent\'s betting strategy.',
    description: 'Teach the defender\'s side of the sizing conversation from Module 11.',
    learningObjectives: [
      'Apply minimum defense frequency against different bet sizes',
      'Choose bluff-catchers, value raises and bluff raises deliberately',
      'Build a full range-defense plan rather than single-hand reactions',
    ],
    difficulty: 'intermediate',
    stageId: 'bet-sizing-defense',
    order: 13,
    prerequisiteModuleId: 'bet-sizing-language-module',
    plannedLessons: [
      { title: 'Facing Small Bets' },
      { title: 'Facing Large Bets' },
      { title: 'MDF Revisited' },
      { title: 'Bluff Catchers' },
      { title: 'Calling Thresholds' },
      { title: 'Raising for Value' },
      { title: 'Raising as a Bluff' },
      { title: 'Check-Raising' },
      { title: 'Range Defense' },
      { title: 'Defense Lab' },
    ],
  },

  // ── Stage 7 — Street Mastery ─────────────────────────────────────────────────
  {
    ...ROADMAP_DEFAULTS,
    id: 'flop-strategy-module',
    path_id: 'intermediate',
    slug: 'flop-strategy-module',
    title: 'Flop Strategy',
    subtitle: 'Build complete flop strategies from ranges, boards and bet sizes.',
    description: 'Move from flop fundamentals into serious strategic construction.',
    learningObjectives: [
      'Build IP and OOP flop strategies across different board types',
      'Use multiple bet sizes and check-raises as part of one coherent plan',
      'Practice full flop range construction, not isolated decisions',
    ],
    difficulty: 'intermediate',
    stageId: 'street-mastery',
    order: 14,
    prerequisiteModuleId: 'defending-bets-module',
    plannedLessons: [
      { title: 'IP C-Betting' },
      { title: 'OOP Strategy' },
      { title: 'High-Card Boards' },
      { title: 'Low Connected Boards' },
      { title: 'Paired Boards' },
      { title: 'Monotone Boards' },
      { title: 'Check-Raising' },
      { title: 'Multi-Sizing Strategy' },
      { title: 'Flop Range Construction' },
      { title: 'Flop Decision Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'turn-strategy-module',
    path_id: 'intermediate',
    slug: 'turn-strategy-module',
    title: 'Turn Strategy',
    subtitle: 'Learn how one card transforms ranges and future betting plans.',
    description: 'Extend range and sizing thinking onto the turn.',
    learningObjectives: [
      'Distinguish range-changing turns, blank turns and scare cards',
      'Choose between double barreling and delayed c-betting',
      'Start planning the river while still on the turn',
    ],
    difficulty: 'intermediate',
    stageId: 'street-mastery',
    order: 15,
    prerequisiteModuleId: 'flop-strategy-module',
    plannedLessons: [
      { title: 'How Turns Change Equity' },
      { title: 'Range-Changing Turns' },
      { title: 'Blank Turns' },
      { title: 'Scare Cards' },
      { title: 'Double Barreling' },
      { title: 'Delayed C-Betting' },
      { title: 'Turn Check-Raising' },
      { title: 'Turn Overbets' },
      { title: 'Planning the River' },
      { title: 'Turn Decision Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'river-strategy-module',
    path_id: 'intermediate',
    slug: 'river-strategy-module',
    title: 'River Strategy',
    subtitle: 'Master the street where equity becomes final and ranges become most polarized.',
    description: 'Apply everything learned to the final, most polarized street.',
    learningObjectives: [
      'Separate thin value bets from bluffs and bluff-catches on the river',
      'Choose river bluffs deliberately using blockers',
      'Handle polarized overbets from both sides of the pot',
    ],
    difficulty: 'intermediate',
    stageId: 'street-mastery',
    order: 16,
    prerequisiteModuleId: 'turn-strategy-module',
    plannedLessons: [
      { title: 'River Fundamentals' },
      { title: 'Value Betting' },
      { title: 'Thin Value' },
      { title: 'Bluff Catching' },
      { title: 'Choosing Bluffs' },
      { title: 'Blockers on the River' },
      { title: 'Polarized River Betting' },
      { title: 'River Overbets' },
      { title: 'Facing Polarization' },
      { title: 'River Decision Lab' },
    ],
  },

  // ── Stage 8 — Multi-Street Poker ─────────────────────────────────────────────
  {
    ...ROADMAP_DEFAULTS,
    id: 'multistreet-planning-module',
    path_id: 'intermediate',
    slug: 'multistreet-planning-module',
    title: 'Multi-Street Planning',
    subtitle: 'Stop making isolated decisions and start planning complete hands.',
    description: 'Teach strategic continuity across flop, turn and river.',
    learningObjectives: [
      'Plan a hand at least one street ahead instead of street-by-street',
      'Identify barrel and give-up candidates as a range evolves',
      'Build a full river range from a flop and turn plan',
    ],
    difficulty: 'intermediate',
    stageId: 'multi-street-poker',
    order: 17,
    prerequisiteModuleId: 'river-strategy-module',
    plannedLessons: [
      { title: 'Thinking One Street Ahead' },
      { title: 'Range Evolution' },
      { title: 'Barrel Candidates' },
      { title: 'Give-Up Candidates' },
      { title: 'Future Runouts' },
      { title: 'Planning Bet Sizes' },
      { title: 'Building River Ranges' },
      { title: 'Multi-Street Bluffing' },
      { title: 'Multi-Street Value Lines' },
      { title: 'Full Hand Simulation Lab' },
    ],
  },

  // ── Stage 9 — Special Pot Types ──────────────────────────────────────────────
  {
    ...ROADMAP_DEFAULTS,
    id: 'three-bet-pots-module',
    path_id: 'advanced',
    slug: 'three-bet-pots-module',
    title: '3-Bet Pots',
    subtitle: 'Learn how compressed ranges and lower SPR change postflop strategy.',
    description: 'Apply range and sizing theory to the structurally distinct 3-bet pot.',
    learningObjectives: [
      'Recognize how 3-bet pot ranges and SPR differ from single-raised pots',
      'Build IP and OOP 3-bet pot strategies across streets',
      'Adjust c-betting and checking frequencies for compressed ranges',
    ],
    difficulty: 'advanced',
    stageId: 'special-pot-types',
    order: 18,
    prerequisiteModuleId: 'multistreet-planning-module',
    plannedLessons: [
      { title: 'Anatomy of a 3-Bet Pot' },
      { title: 'Range Structure' },
      { title: 'SPR Changes' },
      { title: 'IP 3-Bet Pots' },
      { title: 'OOP 3-Bet Pots' },
      { title: 'C-Betting' },
      { title: 'Checking' },
      { title: 'Turn Strategy' },
      { title: 'River Strategy' },
      { title: '3-Bet Pot Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'four-bet-pots-module',
    path_id: 'advanced',
    slug: 'four-bet-pots-module',
    title: '4-Bet Pots',
    subtitle: 'Navigate narrow ranges, low SPR and high-value decisions.',
    description: 'Extend special-pot-type theory to the even more compressed 4-bet pot.',
    learningObjectives: [
      'Reason about very low SPR postflop decisions',
      'Set stack-off thresholds for narrow, high-value ranges',
      'Identify where bluffing still belongs in a 4-bet pot',
    ],
    difficulty: 'advanced',
    stageId: 'special-pot-types',
    order: 19,
    prerequisiteModuleId: 'three-bet-pots-module',
    plannedLessons: [
      { title: '4-Bet Pot Ranges' },
      { title: 'Low SPR Strategy' },
      { title: 'Range Advantage' },
      { title: 'Small C-Bets' },
      { title: 'Checking' },
      { title: 'Stack-Off Thresholds' },
      { title: 'Turn Decisions' },
      { title: 'River Decisions' },
      { title: 'Bluffing in 4-Bet Pots' },
      { title: '4-Bet Pot Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'blind-vs-blind-module',
    path_id: 'advanced',
    slug: 'blind-vs-blind-module',
    title: 'Blind vs Blind',
    subtitle: 'Master the widest ranges in poker.',
    description: 'Apply the full toolkit to the widest-range pot type in poker.',
    learningObjectives: [
      'Adjust standard theory for the unusually wide blind-vs-blind ranges',
      'Compare limping, raising and defending approaches from the blinds',
      'Carry range- and nut-advantage thinking through to the river in wide pots',
    ],
    difficulty: 'advanced',
    stageId: 'special-pot-types',
    order: 20,
    prerequisiteModuleId: 'four-bet-pots-module',
    plannedLessons: [
      { title: 'Why Blind vs Blind Is Different' },
      { title: 'Small Blind Opening' },
      { title: 'Big Blind Defense' },
      { title: 'Limp Strategies' },
      { title: 'Raising vs Limp' },
      { title: 'Wide Range Postflop Play' },
      { title: 'Range Advantage' },
      { title: 'Aggression' },
      { title: 'River Strategy' },
      { title: 'Blind Battle Lab' },
    ],
  },

  // ── Stage 10 — Stack Depth ───────────────────────────────────────────────────
  {
    ...ROADMAP_DEFAULTS,
    id: 'short-stack-strategy-module',
    path_id: 'advanced',
    slug: 'short-stack-strategy-module',
    title: 'Short-Stack Strategy',
    subtitle: 'Learn how shrinking stacks transform ranges and decision thresholds.',
    description: 'Apply strategy across the shrinking-stack side of the SPR spectrum.',
    learningObjectives: [
      'Adjust ranges and thresholds across 40bb, 30bb, 20bb and 15bb depths',
      'Reason about shove/fold and rejamming decisions',
      'Simplify postflop play appropriately at low SPR',
    ],
    difficulty: 'advanced',
    stageId: 'stack-depth',
    order: 21,
    prerequisiteModuleId: 'blind-vs-blind-module',
    plannedLessons: [
      { title: 'Stack Depth Revisited' },
      { title: '40bb Strategy' },
      { title: '30bb Strategy' },
      { title: '20bb Strategy' },
      { title: '15bb Strategy' },
      { title: 'Shove / Fold Concepts' },
      { title: 'Rejamming' },
      { title: 'Low-SPR Postflop' },
      { title: 'Short-Stack Adjustments' },
      { title: 'Short-Stack Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'deep-stack-strategy-module',
    path_id: 'advanced',
    slug: 'deep-stack-strategy-module',
    title: 'Deep-Stack Strategy',
    subtitle: 'Learn why deep stacks increase the importance of position, nuttiness and future streets.',
    description: 'Apply strategy across the deep-stack side of the SPR spectrum.',
    learningObjectives: [
      'Explain why nut potential and position matter more as stacks get deeper',
      'Reason about reverse implied odds in large, deep-stacked pots',
      'Use river leverage deliberately when building deep-stack bluffing lines',
    ],
    difficulty: 'advanced',
    stageId: 'stack-depth',
    order: 22,
    prerequisiteModuleId: 'short-stack-strategy-module',
    plannedLessons: [
      { title: 'Deep Stack Fundamentals' },
      { title: 'SPR at Depth' },
      { title: 'Nut Potential' },
      { title: 'Reverse Implied Odds' },
      { title: 'Position' },
      { title: 'Suited / Connected Hands' },
      { title: 'Large Pots' },
      { title: 'Deep-Stack Bluffing' },
      { title: 'River Leverage' },
      { title: 'Deep-Stack Lab' },
    ],
  },

  // ── Stage 11 — Tournament Poker ──────────────────────────────────────────────
  {
    ...ROADMAP_DEFAULTS,
    id: 'tournament-foundations-module',
    path_id: 'advanced',
    slug: 'tournament-foundations-module',
    title: 'Tournament Foundations',
    subtitle: 'Understand how changing stacks and tournament structure reshape poker strategy.',
    description: 'Introduce the tournament-specific pressures that don\'t exist in cash play.',
    learningObjectives: [
      'Explain how antes and shrinking stacks change strategy over a tournament',
      'Weigh survival against chip accumulation at different stages',
      'Recognize short-stack pressure and rejam dynamics at the table',
    ],
    difficulty: 'advanced',
    stageId: 'tournament-poker',
    order: 23,
    prerequisiteModuleId: 'deep-stack-strategy-module',
    plannedLessons: [
      { title: 'Tournament Stack Dynamics' },
      { title: 'Antes' },
      { title: 'Stack Preservation' },
      { title: 'Short-Stack Pressure' },
      { title: 'Rejams' },
      { title: 'Table Dynamics' },
      { title: 'Tournament Stages' },
      { title: 'Chip Accumulation' },
      { title: 'Survival vs Growth' },
      { title: 'Tournament Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'icm-module',
    path_id: 'advanced',
    slug: 'icm-module',
    title: 'ICM',
    subtitle: 'Learn why tournament chips do not always equal tournament value.',
    description: 'Teach the conversion from chip stacks to real tournament equity near pay jumps.',
    learningObjectives: [
      'Explain the difference between chip EV and money EV',
      'Apply risk premium and bubble pressure to calling/shoving decisions',
      'Adjust ranges by stack size at a final table',
    ],
    difficulty: 'advanced',
    stageId: 'tournament-poker',
    order: 24,
    prerequisiteModuleId: 'tournament-foundations-module',
    plannedLessons: [
      { title: 'What Is ICM?' },
      { title: 'Chip EV vs Money EV' },
      { title: 'Risk Premium' },
      { title: 'Bubble Pressure' },
      { title: 'Calling vs Shoving' },
      { title: 'Big Stack Pressure' },
      { title: 'Medium Stack Dynamics' },
      { title: 'Short Stack Dynamics' },
      { title: 'Final Tables' },
      { title: 'ICM Decision Lab' },
    ],
  },

  // ── Stage 12 — Exploitative Poker ────────────────────────────────────────────
  {
    ...ROADMAP_DEFAULTS,
    id: 'population-exploits-module',
    path_id: 'advanced',
    slug: 'population-exploits-module',
    title: 'Population Exploits',
    subtitle: 'Learn how to profit when opponents systematically deviate from strong strategy.',
    description: 'Teach exploitation only after a strong theoretical GTO baseline is in place.',
    learningObjectives: [
      'Compare a GTO baseline against common population tendencies',
      'Recognize over-folding, over-calling, over- and under-bluffing patterns',
      'Adjust preflop and postflop ranges to exploit systematic population leaks',
    ],
    difficulty: 'advanced',
    stageId: 'exploitative-poker',
    order: 25,
    prerequisiteModuleId: 'icm-module',
    plannedLessons: [
      { title: 'GTO Baseline vs Exploitation' },
      { title: 'Population Tendencies' },
      { title: 'Overfolding' },
      { title: 'Underfolding' },
      { title: 'Underbluffing' },
      { title: 'Overbluffing' },
      { title: 'Sizing Tendencies' },
      { title: 'Preflop Population Leaks' },
      { title: 'Postflop Population Leaks' },
      { title: 'Exploit Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'player-exploitation-module',
    path_id: 'advanced',
    slug: 'player-exploitation-module',
    title: 'Player-Specific Exploitation',
    subtitle: 'Turn reliable opponent tendencies into targeted strategic adjustments.',
    description: 'Move from population-level exploits to individual, reliable reads.',
    learningObjectives: [
      'Judge sample size and confidence before committing to an exploit',
      'Adjust value ranges, bluffing and calling against a specific opponent',
      'Know when and how to return to a balanced baseline',
    ],
    difficulty: 'advanced',
    stageId: 'exploitative-poker',
    order: 26,
    prerequisiteModuleId: 'population-exploits-module',
    plannedLessons: [
      { title: 'Identifying Reliable Leaks' },
      { title: 'Sample Size' },
      { title: 'Exploit Confidence' },
      { title: 'Adjusting Value Ranges' },
      { title: 'Adjusting Bluffing' },
      { title: 'Adjusting Calls' },
      { title: 'Adjusting Bet Sizes' },
      { title: 'Counter-Exploitation' },
      { title: 'Returning to Baseline' },
      { title: 'Exploit Decision Lab' },
    ],
  },

  // ── Stage 13 — Elite Strategy ────────────────────────────────────────────────
  {
    ...ROADMAP_DEFAULTS,
    id: 'think-like-solver-module',
    path_id: 'pro',
    slug: 'think-like-solver-module',
    title: 'Think Like a Solver',
    subtitle: 'Learn to predict strategy instead of memorizing outputs.',
    description:
      'One of the final transformations of the Poker Journey — reasoning toward solver-like strategies using everything learned previously. The learner predicts a frequency, size or range first, then compares it against a reference strategy.',
    learningObjectives: [
      'Predict betting and checking ranges before seeing a reference solve',
      'Reason about game-tree construction and range constraints',
      'Read and interpret mixed-strategy solver output',
    ],
    difficulty: 'elite',
    stageId: 'elite-strategy',
    order: 27,
    prerequisiteModuleId: 'player-exploitation-module',
    plannedLessons: [
      { title: 'What Solvers Actually Solve' },
      { title: 'Building the Game Tree' },
      { title: 'Ranges and Constraints' },
      { title: 'Predict the Frequency' },
      { title: 'Predict the Bet Size' },
      { title: 'Predict the Betting Range' },
      { title: 'Predict the Checking Range' },
      { title: 'Reading Solver Output' },
      { title: 'Understanding Mixed Strategies' },
      { title: 'Solver Prediction Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'range-reconstruction-module',
    path_id: 'pro',
    slug: 'range-reconstruction-module',
    title: 'Advanced Range Reconstruction',
    subtitle: 'Rebuild an opponent\'s range from every decision they made.',
    description: 'Apply filtering street-by-street to rebuild a complete, weighted opponent range.',
    learningObjectives: [
      'Filter a starting range through preflop, flop, turn and river action',
      'Apply combination removal and frequency weighting to a final range',
      'Judge bluff density and value density in a reconstructed range',
    ],
    difficulty: 'elite',
    stageId: 'elite-strategy',
    order: 28,
    prerequisiteModuleId: 'think-like-solver-module',
    plannedLessons: [
      { title: 'Starting Range' },
      { title: 'Preflop Filtering' },
      { title: 'Flop Filtering' },
      { title: 'Turn Filtering' },
      { title: 'River Range' },
      { title: 'Combination Removal' },
      { title: 'Frequency Weighting' },
      { title: 'Bluff Density' },
      { title: 'Value Density' },
      { title: 'Full Range Reconstruction Lab' },
    ],
  },
  {
    ...ROADMAP_DEFAULTS,
    id: 'elite-decision-making-module',
    path_id: 'pro',
    slug: 'elite-decision-making-module',
    title: 'Elite Decision Making',
    subtitle: 'Combine every major poker concept into complete strategic reasoning.',
    description:
      'The final core module — full hand simulations that progressively build a decision from ranges and SPR up to the highest-EV strategy, rather than jumping straight to an answer.',
    learningObjectives: [
      'Work a hand from range advantage through SPR to sizing, in order',
      'Integrate blockers, polarization and multi-street planning into one decision',
      'Reach a highest-EV strategy through progressive reasoning, not memorized rules',
    ],
    difficulty: 'elite',
    stageId: 'elite-strategy',
    order: 29,
    prerequisiteModuleId: 'range-reconstruction-module',
    plannedLessons: [
      { title: 'What Are the Ranges?' },
      { title: 'Who Has Range Advantage?' },
      { title: 'Who Has Nut Advantage?' },
      { title: 'What Is the SPR?' },
      { title: 'Which Hands Want Value?' },
      { title: 'Which Hands Can Bluff?' },
      { title: 'Which Blockers Matter?' },
      { title: 'What Sizing Makes Strategic Sense?' },
      { title: 'What Happens on Future Streets?' },
      { title: 'What Is the Highest-EV Strategy?' },
    ],
  },
]
